### ISSUE TITLE
SDK CRASH

### ISSUE THREAD

**Issue by goelay** [aws/amazon-chime-sdk-ios#101]
Hello,
On the latest SDK Bitcode enabled if I cancel the call asap its crashing - VideoClient is uninitialized so cannot be stopped and destroyed as I call stop

**Comment by hokyungh** [comment]
Hi would you be able to provide me with logs and SDK version/SDK media version you are using?

**Comment by g-malinov** [comment]
I am getting this issue with SDK version 14 and Media version 10
