### ISSUE TITLE
connectionDidRecover does not fire

### ISSUE THREAD

**Issue by duraz0rz** [aws/amazon-chime-sdk-ios#102]
**Describe the bug**
We added logic to log when `connectionDidRecover` and `connectionBecamePoor` fire so we can keep track of how often a user's connection becomes unstable enough. While we can get `connectionBecamePoor` to fire by throttling down an attendee's bandwidth, `connectionDidRecover` does not fire when the bandwidth is restored.

**To Reproduce**
1. Start a meeting with several users (4 should probably suffice).
2. Throttle down one attendee's bandwidth to 0.1Mb/s upload and download if your router supports it.
3. Observe `connectionBecamePoor` firing.
4. Remove the restrictions on the above attendee.
5. Observe `connectionDidRecover` **not** firing.

**Expected behavior**
`connectionDidRecover` should fire when connection exits the poor state.

**Test environment Info (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14 beta 6
 - Version AmazonChimeSDK: 0.7.0
 - Version AmazonChimeSDKMedia: 0.5.0

**Comment by hokyungh** [comment]
Thank you for reporting. Is AmazonChimeSDKMedia version supposed to be 0.6.0 or is it 0.5.0?

When you say `connectionDidRecover` did not fire, does it take time to fire or it didn't fire at all?

I have used Network Link conditioner on my iPhone and I do get `connectionDidRecover` fired.

**Comment by duraz0rz** [comment]
`connectionDidRecover` didn't fire at all. I _think_ I remember observing the metrics tab not reflecting the device's bandwidth after giving back the full bandwidth.

You have to background the Chime sample app when you use Network Link conditioner, right? I did it straight from my router so I didn't exit the app at all.

**Comment by linsang21** [comment]
Hi there, one thing worth mentioning is the state of session.
When the ```connectionBecamePoor``` is fired, the state is still **connected** but weak. In the meantime, sdk tries to reconnect. After certain amount of time, if it successes, ```connectionDidRecover``` will be triggered, otherwise, session gets **disconnected** entirely and ```audioSessionDidStopWithStatus``` will be called.

Do you mind check if  you get ```audioSessionDidStopWithStatus``` in the experiment?
