### ISSUE TITLE
What is the equivalent of "getAllVideoTiles" in iOS SDK?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [aws/amazon-chime-sdk-ios#108]
In Amazon JS SDK, there is a method which is quite useful when I want to get the video tiles of people in an ongoing video call:

https://aws.github.io/amazon-chime-sdk-js/interfaces/videotilecontroller.html#getallvideotiles

What is the equivalent of it in iOS SDK?

**Comment by linsang21** [comment]
Sorry we don't have the equivalent of that API at the moment. 
As a workaround, builders could manage the all the video tile states based on ```videoTileDidAdd``` and ```videoTileDidRemove```, to at least track the tiles with it's id.

But we would love to hear more about your use case which would help us in prioritizing this feature. Could you please fill out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "Tell us about your project”. You can put the link of this GitHub issue there.

Meanwhile, I'll put enhancement label.
