### ISSUE TITLE
Microphone got disabled when a Webview starts to play media

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [aws/amazon-chime-sdk-ios#118]
**Describe the bug**
This is a very special case that I bumped into. I'm developing an app in React Native, and using `react-native-webview` (WKWebview under the hood) to show some data from my source, nothing fancy.

In the same screen, there is a button to connect to Chime video call. And I implemented it correctly (video shown and the audio does not have any problem up to this point).

But when the Webview starts to play media (a small remote mp3 file), the microphone doesn't work anymore and there're lots of noise start to burst out from built-in speaker. Everything I speak into the mic isn't transmitted to the audience.

**Expected behavior**
Sound from Webview and from Chime can be mixed together (nothing ducked) and the microphone works normally.

**Test environment Info (please complete the following information):**
 - Device: Any iOS device
 - OS: iOS 10+
 - Version AmazonChimeSDK: 0.10.0
 - Version AmazonChimeSDKMedia: 0.6.2

**Additional context**
When I try to play a song using iTunes Music, put iTunes Music to background (music is still playing), then open my app, open the Webview and let it play the remote file, music playback from iTunes Music stops immediately. Not sure if it's useful for debbuging.

**Comment by Doko-Demo-Doa** [comment]
Alright I found the root cause.

`WKWebView` runs on a different thread (unlike UIWebView). When playing media, it shifts the `AVAudioSessionCategory` from (whatever) to `AVAudioSessionCategorySoloAmbient`.

The solution is simple: When it (the webview) plays, trigger this method with a small delay to regain the "right" to use the media for your app:

```objectivec
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord 
                                 withOptions:AVAudioSessionCategoryOptionMixWithOthers
                                       error:&error];
```

or with Swift:

```swift
do {
    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
}
catch let error as NSError {
    print(error)
}
```

seems hacky, but it works for me.

**Comment by tianyux-amz** [comment]
Thanks @Doko-Demo-Doa for the additional info!
