### ISSUE TITLE
Integrate Chime with CallKit for VOIP

### ISSUE THREAD

**Issue by anasna83** [aws/amazon-chime-sdk-ios#12]
I'm assuming that chime sdk has the ability to serve as VOIP service since Amazon Chime has VOIP feature. Would you please show this in your demo if this is correct.

 I tried to run MeetingSession.audioVideo.start() when app didReceiveIncomingPushWith but it doesn't work
 

Does chime works with CallKit and voip ?

Thank you !

**Comment by mitankit** [comment]
Amazon Chime app is fully integrated with Call kit. 
However, Chime SDK currently leaves Call kit integration up to the builder. We might in future provide integration with Callkit directly in the SDK depending on customer ask. But for now Builders would have to implement it.

If you are facing a problem in integrating the callkit, could you please give us the list of steps you have performed and where are you getting the problem?

**Comment by anasna83** [comment]
Thank you for your replay! I'm looking for what options do we have to implement VOIP in our apps, so I tried to implement chime SDK but didn't go too deep because it was not clear for me if it could be integrated with callKit. I was expecting to be implemented directly.

 I had some issues making the SDK works when the phone is locked. I'll repost again if we decided to go with chime and stuck in the implementation. Thanks again!

**Comment by mitankit** [comment]
Sure. You can reopen the issue whenever you have more details. I am putting a Feature enhancement label as its a new feature.
We would also love to hear more about your use case which would help us in prioritizing this feature. Could you please fill out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "“Tell us about your project:”. You can put the link of this GitHub issue there.

**Comment by jadhavd183** [comment]
Hey @mitankit , it would be so practical if really look forward to do it with CallKit, these days every meeting application is having CallKit integrated, in one of my application has quick requirement in realtime communication module, so I went through the chime sdk , found it very interesting. CallKit would have been a more  perfect suit to it .😑

**Comment by zhinang-amazon** [comment]
SDK v0.8.0 is released and the Demo app is integrated with CallKit, which can be used as a reference. One thing to note is that our Demo app does not have VoIP Push integration so both outgoing/incoming calls are triggered locally. Our team is also working on a blog post to provide a written guide on how to integrate CallKit with Chime SDK. We will update this issue once the blog post is out.

**Comment by zhinang-amazon** [comment]
Our [CallKit Integration Guide](https://aws.amazon.com/blogs/business-productivity/how-to-integrate-apples-callkit-into-ios-applications-using-the-amazon-chime-sdk/ ) is out. Closing this issue.

**Comment by h-kurebayashi** [comment]
Hi Mr.zhinang
I'm having trouble with Amazon Chime's Callkit.
I am developing an iOS app.
Callkit usually receives calls normally.
However, due to an unknown reason, there is a problem that Callkit cannot receive calls.
If Callkit can no longer receive calls, you will not be able to receive calls for about 5 minutes no matter how many times you call.
So I end the call.
However, if I leave the app for a while, Callkit suddenly arrives.
Do you understand this phenomenon?
Please let me know if there is a solution.
