### ISSUE TITLE
setting up a video call results in TURN CreatePermission error

### ISSUE THREAD

**Issue by TomaszStoklosaFP** [aws/amazon-chime-sdk-ios#126]
**Describe the bug**
When I try to start call this error always occurs.
 
**Expected behavior**
I expect connection to be established, and call start without errors.
 
**Logs**
 
[ERROR] MeetingModel - audio cues: others_joined.wav err: 7
[ERROR] MeetingModel - audio cues: others_left.wav err: 7
[ERROR] MeetingModel - audio cues: reconnecting.wav err: 7
[ERROR] MeetingModel - audio cues: reconnected.wav err: 7
[ERROR] MeetingModel - audio cues: reconnect_failed.wav err: 7
[ERROR] MeetingModel - audio cues: rumble_strips.wav err: 7
[ERROR] MeetingModel - audio cues: first_caller.wav err: 7
[ERROR] MeetingModel - audio cues: remote_muted.wav err: 7
[ERROR] MeetingModel - audio cues: call_waiting.wav err: 7
[ERROR] MeetingModel - audio cues: ring_back.wav err: 7
[ERROR] MeetingModel - audio cues: first_caller_beep.wav err: 7
device model is iPhone10,4
hardware model is D201AP
[INFO] MeetingModel - Initializing VideoClient
[INFO] MeetingModel - Starting VideoClient
[INFO] MeetingModel - API/DefaultAudioVideoFacade/start(callKitEnabled: false)
[INFO] MeetingModel - Starting remote video
[INFO] MeetingModel - Audio started connecting. Reconnecting: false
[INFO] MeetingModel - Requesting TURN creds
[INFO] MeetingModel - Audio successfully started. Reconnecting: false
[INFO] MeetingModel - TURN request success
[INFO] MeetingModel - videoClientIsConnecting
[INFO] MeetingModel - Video connecting
[INFO] MeetingModel - videoClientDidConnect, 0
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[INFO] MeetingModel - Video started ok
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[ERROR] MeetingModel - [002:004] [71687] (turn_port.cc:1848): Received TURN CreatePermission error response, code=403; pruned connection.
[ERROR] MeetingModel - [002:004] [71687] (turn_port.cc:1848): Received TURN CreatePermission error response, code=403; pruned connection.
[ERROR] MeetingModel - [002:020] [71687] (turn_port.cc:1848): Received TURN CreatePermission error response, code=403; pruned connection.
[ERROR] MeetingModel - [002:024] [71687] (turn_port.cc:1848): Received TURN CreatePermission error response, code=403; pruned connection.
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[ERROR] MeetingModel - [003:060] [56579] (webrtc_video_engine.cc:3264): Absent receive stream; ignoring clearing encoded frame sink for ssrc 0
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[INFO] MeetingModel - videoClientCameraSendIsAvailable
[INFO] MeetingModel - videoClientCameraSendIsAvailable
 
**Test environment Info** 
 - Device: iPhone8
- OS: 13.7
- Version AmazonChimeSDK:  0.10.0
- Version AmazonChimeSDKMedia: 0.6.2
 
**Additional context**
In Info.plist 2 parameters was added :
 

Privacy - Microphone Usage Description : Required by Audio / Video

Privacy - Camera Usage Description : Required by Video

**Comment by haifengx** [comment]
Hi @TomaszStoklosaFP,

The "TURN CreatePermission 403 error response" can happen in normal condition, usually just means one (but not all) of the connections had some error.

I saw in logs "Video started ok". Were you able to see remote video tiles or local video streams being sent? If not, can you see if you can find more error logs in addition to those you posted initially? Thanks!

**Comment by TomaszStoklosaFP** [comment]
Thank you very much for help. I analyzed the code again and I missed the "self.startLocalVideo()".
It works now.
