### ISSUE TITLE
XCFramework support

### ISSUE THREAD

**Issue by haifengx** [aws/amazon-chime-sdk-ios#129]
**Is your feature request related to a problem? Please describe.**
Amazon Chime iOS SDK is currently distributed in .framework binary format which is not compatible with Swift Packages. Xcode 11 introduced a new binary format .XCFramework which is compatible with Swift Packages and Swift Package Manager (SPM) starting Xcode 12.

Providing XCFramework enables developers to manage Amazon Chime SDK dependency with the official tool, and deprecate third party solutions such as CocoaPods, in addition to other benefits it brings.

**Describe the solution you'd like**
Build and distribute SDK in .XCFramework format

**Describe alternatives you've considered**
CocoaPods, which may have compatibility issue with Xcode

**Comment by haifengx** [comment]
Related WWDC videos:
"Binary Frameworks in Swift" WWDC 2019: https://developer.apple.com/videos/play/wwdc2019/416
"Distribute binary frameworks as Swift packages" WWDC 2020: https://developer.apple.com/videos/play/wwdc2020/10147

**Comment by jatindervrify** [comment]
Just wanted to chime in (pun heavily intended) that we're looking forward to this enhancement as well. Any updates on progress or if it's being considered? Alternatively, providing the sdk as a SPM package would be even more ideal vs the current solution of embedding the framework.

**Comment by zhinang-amazon** [comment]
Hi @jatindervrify, 
Our team is actively looking into this since this may help resolve #195  #197 
We will update this issue once we have a confirmed release date

**Comment by zhinang-amazon** [comment]
Hi @jatindervrify 
Our team just release v0.15.0 with XCFramework support. You can find the new `.xcframework` format after unzipping  the `.tar.gz` file
https://github.com/aws/amazon-chime-sdk-ios/releases/latest

**Comment by georgezy-amzn** [comment]
Hi all,

SPM support is available now! https://github.com/aws/amazon-chime-sdk-ios-spm
