### ISSUE TITLE
No Screen Share Video Recieved.

### ISSUE THREAD

**Issue by BenjoBastatas** [aws/amazon-chime-sdk-ios#13]
I have been using [demo](https://github.com/aws/amazon-chime-sdk-js) while building the mobile app. Thanks to you guys here, I have been able to view the videos from the other participants by implementing [VideoTileObserver extension](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#L448) and other codes to receive videoTileState.

**But when:**
web([demo](https://github.com/aws/amazon-chime-sdk-js)) and mobile app join the meeting -> web turns screen share on -> no videoTileState.isContent==true in mobile app side
is received. 

Is it because they are technically running only in a single machine?
Thus filtering out its own, through its network identity to prevent video content loop?

I even tried using [iOS demo](https://github.com/aws/amazon-chime-sdk-ios/tree/master/AmazonChimeSDKDemo) as the testing mobile app with the same result.

**Environment:**
Device: iPhone 11 Pro (Simulator)
iOS version: 13.3
Language: Swift 4

**Comment by hokyungh** [comment]
Do you know if you are using [Meeting V1](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meeting) or [Meeting V2](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2)? 

If you used serverless demo, would you be able to check if [serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) is run after they defaulted to V2?

Mobile SDK is only compatible with V2 currently.

**Comment by BenjoBastatas** [comment]
I was able to confirm that I was using [MeetingV1](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meeting).

Switch to [MeetingV2](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2) and now it is working properly.

Many thanks!
