### ISSUE TITLE
Video Tile from web showing other tile screenshots when paused

### ISSUE THREAD

**Issue by mj8894** [aws/amazon-chime-sdk-ios#130]
**The bug**
When web users joined a meeting and their video pauses, then other video tile content is shown as a screenshot in the Web tiles. This happens only for participants joined via Web. I am using `prepareForReuse()` as mentioned in the demo. and also calling proper `reloadData()`. Please suggest how to fix this.

**To Reproduce**
1. Go to tile listing
2. Have participants join from Web and iOS whenever Web video pauses due to poor connection there will be remnants of videos from other participants

**Expected behavior**
The web video should remain paused in its content view without any external remnants and resume when video resumes.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone SE2
 - OS: iOS 14.0.1
 - Version AmazonChimeSDK: 0.10.0
 - Version AmazonChimeSDKMedia: 0.6.2

**Comment by zhinang-amazon** [comment]
Hi @mj8894 
Are you able to reproduce this with our demo app?
Since we do not have access to your app and your view logic, it will be really helpful if you can provide reproduce step with our demo app.

**Comment by mj8894** [comment]
Hi @zhinang-amazon,

You can use the older demo version which had UICollectionview for video listing and with 4-5 paticipants you should be able to reproduce the issue, unfortunately there aren't any reproduction steps as such. However, I do believe this might be happening due to concurrent UICollectionView from different sources (For ex. Someone joined the meeting when you were rotating the screen)
