### ISSUE TITLE
SwiftUI Example

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#131]
**Is your feature request related to a problem? Please describe.**
Can your team help us do a Blog post of the SwiftUI Demo example?

**Describe the solution you'd like**
Please can your team help us out with a SwiftUI Demo example

**Describe alternatives you've considered**
we know one can do a UIViewRepresentable and UIViewControllerRepresentable but this is not very easy considering that most of us are still trying to get familiar with the SDK and then again having to blend all of that with an existing project and adding our own creativity. Can your team help us do a Blog post of the SwiftUI example?

**Additional context**
Your team did a great job with the Android SDK example blogpost and our Android App is market ready just the iOS version still looking strange but the SwiftUI demo example will really help a lot of us.
Thanks

**Comment by haifengx** [comment]
@adesun2k thanks for cutting a feature request. We will use https://github.com/aws/amazon-chime-sdk-ios/issues/120 to track SwiftUI demo app if you like and close this one for easier tracking. Thanks!
