### ISSUE TITLE
Add uplink/downlink policy to control video resolution

### ISSUE THREAD

**Issue by tianyux-amz** [aws/amazon-chime-sdk-ios#137]
**Is your feature request related to a problem? Please describe.**
Builders do not have way to control the resolution of sending/receiving videos

**Describe the solution you'd like**
An API to control either send/receive video.

**Additional context**
JS SDK has `chooseVideoInputQuality` API: https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#choosevideoinputquality
Corresponding Android SDK issue: https://github.com/aws/amazon-chime-sdk-android/issues/140

**Comment by jonah-katz** [comment]
+1 , especially for receiving video. That way, only devices with poor network conditions can have lower quality video.

**Comment by JozefLipovsky** [comment]
+1, this would be really useful.

**Comment by nank1ro** [comment]
+1, really need this

**Comment by ashrafhere** [comment]
Really need this, calls don't show video on the Cellular network.

**Comment by ziyiz-amzn** [comment]
The downlink policy API to control video resolution is released in [v0.19.0](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.19.0).

The guidance of how to use downlink policy APIs can be found [here](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/configuring_remote_video_subscriptions.md).
You can follow [this guidance](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/custom_video.md) to implement a custom video source.
