### ISSUE TITLE
Unable to Build the Demo Project. AmazoChimeSdkMedia.framework is missing

### ISSUE THREAD

**Issue by umairjamalcuremd** [aws/amazon-chime-sdk-ios#138]
Hi,

I have cloned the Master branch and trying to run the project. Getting this error "No such module 'AmazonChimeSDKMedia'".

In frameworks folder 'AmazonChimeSDKMedia' is appearing in Red color.

I'm unable to locate the framework in project folder.

Please assist.

**Comment by ishwarATanveshak** [comment]
Hey @umairjamalcuremd did you able to resolve this issue. I am kind of stuck here.

**Comment by umairjamalcuremd** [comment]
> Hey @umairjamalcuremd did you able to resolve this issue. I am kind of stuck here.

@ishwarATanveshak 

https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.18.0
Please download the binary from this URL.

**Comment by ishwarATanveshak** [comment]
Hey @umairjamalcuremd, thanks for reply. But I have already downloaded these binary files and I did insert them into the project. but still it gives me this error => **No such module 'AmazonChimeSDKMedia'**
<img width="1115" alt="Screenshot 2022-01-19 at 4 16 26 PM" src="https://user-images.githubusercontent.com/88021875/150115400-b1ac6e35-992e-4e47-acdd-5c115ae5223a.png">
 I have checked Framework Search Paths also in Build Setting (In case if it is about import issues.) which is in the image for your reference.
<img width="996" alt="Screenshot 2022-01-19 at 4 19 03 PM" src="https://user-images.githubusercontent.com/88021875/150115891-cfdc27c1-0384-473e-8d4c-d7d87368f6a7.png">
But still no luck.

**Comment by umairjamalcuremd** [comment]
@ishwarATanveshak 
Have you also added the both
AmazonChimeSDk.framework and AmazonChimeSDKMedia.framework in embed Framework section in Build Phases?

**Comment by ishwarATanveshak** [comment]
Yes. I have added both of the mention .framework files in **AmazonChimeSDKDemo**

**Comment by umairjamalcuremd** [comment]
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/72920209/150118993-9498cd91-cf83-4891-8d45-c941bb721426.png)

This is how I have added it in the framework search path.

**Comment by ishwarATanveshak** [comment]
Okay, Will do that. And let you know. Thanks for help and any leads will be appreciated.

**Comment by ishwarATanveshak** [comment]
Hey can you please tell me how did you get that `PATH/"build/Debug-iphineos` for framework search path. If you have steps for it, Can you provide them here!
Thanks man great help. really appreciated.

**Comment by umairjamalcuremd** [comment]
@YumTheDeathGod 
Sure.
1- Double Click on Debug Paths, A list will appear with all existing added parts.
2- while the list is opened and visible, Drag-drop the AmazonChimeSDK.xcodeproj over the list.
3- Once added, remove the "AmazonChimeSDK.xcodeproj" from the path string.

That's it.

I hope it will help.

**Comment by YumTheDeathGod** [comment]
Thank you very much for your time and knowledge. Really appreciated. I think it will work now.
