### ISSUE TITLE
iOS Device Screen Sharing support

### ISSUE THREAD

**Issue by papercuptech** [aws/amazon-chime-sdk-ios#14]
**Is your feature request related to a problem? Please describe.**
Want to get off of Opentok, but our app requires sharing iPad/iPhone screen, which OT's SDK supports.

**Describe the solution you'd like**
Sharing iPad/iPhone Screen.

**Describe alternatives you've considered**
Opentok. currently using

**Comment by mitankit** [comment]
Currently we only support viewing screen share and not initiating screen share from both the Mobile SDKs. I am putting a Feature enhancement label as its a new feature. 
We would love to hear more about your use case which would help us in prioritizing this feature. Could you please fill out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "“Tell us about your project:”. You can put the link of this GitHub issue there.

**Comment by AshrafJaddo** [comment]
@mitankit just to confirm from what you said above, in a call between an iOS client and a web client. iOS only can see the other screen but it can't share the iOS screen.

**Comment by mitankit** [comment]
> @mitankit just to confirm from what you said above, in a call between an iOS client and a web client. iOS only can see the other screen but it can't share the iOS screen.

That is correct

**Comment by HRK44** [comment]
is this still valid in 2021?

**Comment by zhinang-amazon** [comment]
Hi all, we added support for screen sharing from iOS and Android devices in the latest  0.14.0 release.

Take a look at this [blog post](https://aws.amazon.com/blogs/business-productivity/how-to-screen-share-from-ios-devices-using-amazon-chime-sdk/) and our Swift demo app in this repo for reference.
