### ISSUE TITLE
Is there any way of adding this to my project without committing the framework to git?

### ISSUE THREAD

**Issue by alexmccabe** [aws/amazon-chime-sdk-ios#142]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add this to my project without committing a 225mb file to git. The max file size is 100mb, so maybe CocoaPods support?

Would be happy with another solution / workaround if there are any?

**Describe the solution you'd like**
Add the framework SDK to CocoaPods.

**Describe alternatives you've considered**
There are no real alternatives outside of committing a super large file to git.

**Additional context**
`remote: error: File src/ios/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia is 224.98 MB; this exceeds GitHub's file size limit of 100.00 MB`

**Comment by zhinang-amazon** [comment]
Hi @alexmccabe 
I see that you have already found our open issue for CocoaPods support #59 and a workaround.
I will close this issue and use that for tracking purpose.
