### ISSUE TITLE
App Crashing when binding newly-added video tile

### ISSUE THREAD

**Issue by antonrenzoreyes** [aws/amazon-chime-sdk-ios#145]
**Describe the bug**
Sometimes, app crashes when binding newly-added video tile in `[-videoTileDidAddWithTileState]`

**Expected behavior**
App should not crash.

**Logs**
[20201023132724.txt](https://github.com/aws/amazon-chime-sdk-ios/files/5437760/20201023132724.txt)

**Test environment Info (please complete the following information):**
 - Device: iPad4,1
 - OS: iOS 12.2
 - Version AmazonChimeSDK: 0.8.0
 - Version AmazonChimeSDKMedia: 0.5.2

**Additional context**
Please note that this was not experienced before, and is only being experienced now.

Thanks

**Comment by zhinang-amazon** [comment]
Hi @antonrenzobenedict 

Thanks for providing the crash log with this issue.
I was able to symbolicate the crash, and it's crashing on [this line](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/DefaultVideoTileController.swift#L85) which is strange given that it's only initializing a `NSValue`. And this code is not recently updated.

How often is this happening for you? We haven't heard about this issue from other builders. If it's frequent, we can file a bug report to Apple.

**Comment by antonrenzobenedict** [comment]
Hi @zhinang-amazon, 

No need, this issue is not always replicated.

Thanks!

**Comment by linsang21** [comment]
Hi @antonrenzobenedict,
Just want to check if you still experiencing the crash, or anything we can help out with?

**Comment by zhinang-amazon** [comment]
Closing since we have not heard back. Feel free to reopen if this is still an issue.
