### ISSUE TITLE
Error in constructor of DefaultActiveSpeakerPolicy

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-ios#153]
**Describe the bug**
When the app is setting up the meeting and adds an ActiveSpeakerObserver to the audioVideoFacade, the constructor of DefaultActiveSpeakerPolicy fails.

**Expected behavior**
That the constructor of DefaultActiveSpeaker does not fail.

**Logs**
Fatal error: Use of unimplemented initializer 'init()' for class 'AmazonChimeSDK.DefaultActiveSpeakerPolicy'
2020-10-30 15:50:35.774133+0100 Runner[91902:5806432] Fatal error: Use of unimplemented initializer 'init()' for class 'AmazonChimeSDK.DefaultActiveSpeakerPolicy'

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone 8 (my device), iPhone 12 (on emulator)
 - OS: 14.1
 - Version AmazonChimeSDK: 0.11.1
 - Version AmazonChimeSDKMedia: 0.7.1

**Additional context**
I have gone back to SDK 0.8.1 and SDKMedia 0.6.1 where it is still working.

**Comment by zhinang-amazon** [comment]
This is a new issue introduced with Xcode 12.
We already have a fix for this that will go out with the next release. 
In the meantime, the workaround is use the init with parameters:
`DefaultActiveSpeakerPolicy(speakerWeight:cutoffThreshold:takeoverRate:)`

**Comment by linsang21** [comment]
Fix has been release in [0.12.0](https://github.com/aws/amazon-chime-sdk-ios/blob/master/CHANGELOG.md#0120---2020-11-17), you can always just try out our latest release : ). Please let us know if there's further question.
