### ISSUE TITLE
Locking orientation

### ISSUE THREAD

**Issue by fredericdupir** [aws/amazon-chime-sdk-ios#161]
**Describe the bug**
`DefaultVideoRenderView` ignores rotation setting through UIViewController `shouldAutorotate` + `supportedInterfaceOrientations` or AppDelegate `application(supportedInterfaceOrientationsForWindow:)`
Is there any way to prevent this behavior and keep it locked to portrait?

**Expected behavior**
On an iOS app that only supports portrait, `DefaultVideoRenderView` locks orientation to portrait and don't rotate in landscape.

**Test environment Info (please complete the following information):**
 - Device: iPhoneX, iPhone11
 - OS: iOS14.0
 - Version AmazonChimeSDK: 0.11.1
 - Version AmazonChimeSDKMedia: 0.7.1

**Comment by zhinang-amazon** [comment]
Hi @fredericdupir 
Our `DefaultVideoRenderView` supports orientation changes. If you want to keep the view in portrait, you can create a custom view that implements `VideoRenderView`, and use that for `bindVideoView(videoView:tileId:)`. You need to implement your own logic to handle the case where the video stream received is in landscape, whether that means cropping or resizing.

**Comment by fredericdupir** [comment]
Hi @zhinang-amazon,
I'll try that.
Thanks!

**Comment by LilianAlvarez123** [comment]
Hello,

I experienced the same problem.

However, while the orientation change, the size of the view also changes. Is there a way to prevent the view from changing size while rotating ?

Thanks for the feedback.

**Comment by zhinang-amazon** [comment]
Hi @LilianAlvarez123 
The same recommendation applies, you need to create a custom `VideoRenderView` that keeps the same width and height, and crop/resize the frames received to fit your need when the raw video frame size does not match.
