### ISSUE TITLE
User did not receive [RealtimeObserverMethods -attendeesDidJoinWithAttendeeInfo] for 1 attendee

### ISSUE THREAD

**Issue by antonrenzoreyes** [aws/amazon-chime-sdk-ios#165]
**Describe the bug**
User 1 was able to receive all (3/3) attendee information in the meeting
User 2 was only able to receive (2/3) attendee information in the meeting

**To Reproduce**
This was only replicable once, users were using a 4G network.
Please note that after they all reconnected, User 2 was now able to get all attendee info.

**Expected behavior**
User 2 should be able to receive all attendee info

**Logs**

***User 1 Logs:***
> 2020-10-22 16:20:09:287 (538960) [INF] RTCAmazonChimeCallProvider: user with ID: 2506 connected
> 2020-10-22 16:20:09:288 (538960) [INF] RTCAmazonChimeCallProvider: user with ID: 2572 connected
> 2020-10-22 16:20:09:288 (538960) [INF] RTCAmazonChimeCallProvider: user with ID: 2570 connected

***User 2 Logs:***
> 2020-10-22 16:20:04:552 (5496) [INF] RTCAmazonChimeCallProvider: user with ID: 2572 connected.   
> 2020-10-22 16:20:10:152 (5496) [INF] RTCAmazonChimeCallProvider: user with ID: 2570 connected

**Test environment Info (please complete the following information):**
 - Device: User 1 - iPad5,3, User 2 - iPad8,5
 - OS: User 1 - 13.2.2, User 2- 13.5.1
 - Version AmazonChimeSDK: 0.8.0
 - Version AmazonChimeSDKMedia: 0.5.2

**Comment by hokyungh** [comment]
Do you mind providing little more details to following?
1. Do you mind providing us with detailed setup?
2. Did User3 already present in the meeting? 
3. Did user2 join the second time and only saw two attendee or join the last and saw only two attendee? 
4. If you check all the logs, do you only see two attendees joined log?
5. Do you remember if there was any difference between when you were able to replicate it and when you weren't able to replicate it? Like was it first time joining? Was it on different network?
6. Any error message?

**Comment by antonrenzobenedict** [comment]
> Do you mind providing little more details to following?
> 
> 1. Do you mind providing us with detailed setup?

What do you mean by this?
> 2. Did User3 already present in the meeting?

Yes
> 3. Did user2 join the second time and only saw two attendee or join the last and saw only two attendee?

Last and only saw 2 attendees
> 4. If you check all the logs, do you only see two attendees joined log?

Yes
> 5. Do you remember if there was any difference between when you were able to replicate it and when you weren't able to replicate it? Like was it first time joining? Was it on different network?

No

> 6. Any error message?

None, but there are times when -videoTileSizeDidChangeWithTileState is called but tileState.attendeeId is null based from the logs

**Comment by hokyungh** [comment]
Do you mind giving us full logs for User2? It does sound very related to `videoTileSizeDidChangeWithTileState is called but tileState.attendeeId is null`

**Comment by antonrenzobenedict** [comment]
Hi @hokyungh, please see attached for the full logs


[user2logs.txt](https://github.com/aws/amazon-chime-sdk-ios/files/5551196/user2logs.txt)


The assertions might came from -videoTileDidAddWithTileState, -videoTileDidPauseWithTileState, -videoTileDidRemoveWithTileState, -videoTileSizeDidChangeWithTileState due to attendeeID being null

**Comment by alnlau** [comment]
Hello @antonrenzobenedict,

There was an improvement made in the media library in the most recent release (v0.9.0 for AmazonChimeSDKMedia) regarding attendee update callbacks not received. Retries were added so that the update was not lost if there was an issue. Let us know if you encounter this issue again after upgrading.

**Comment by zhinang-amazon** [comment]
Closing since we have now received any response.
Feel free to reopen if this is still an issue after upgrading to latest SDK version.
