### ISSUE TITLE
Can't resume video tile after pause.

### ISSUE THREAD

**Issue by LilianAlvarez123** [aws/amazon-chime-sdk-ios#166]
**Describe the bug**
Contexte : 
In the spirit of networking optimization, we decided to pause all remote video tile id when the app goes to background.
When the app come back, we call the method `[meetingSession.audioVideo resumeRemoteVideoTileWithTileId: [tileId integerValue]];` in order to unpause the video and to display it on the screen.

Except that even if the method is call there is no video stream coming back. We can observe it thought the Network report section inside Xcode.

So, even if, the resume method is being called, the video never resume.

**To Reproduce**
1. Start a meeting from the mobile.
2. Join the from the web with an active camera and mic.
3. Pause the video tile id from the Web and go to the background mode with the app.
4. Set the web camera and mic on.
5. Come back to the foreground and resume the video tile id of the web.  
6. The video is not showing up.

**Expected behavior**
We should video should appear in the step 6.

**Test environment Info (please complete the following information):**
 - iPhone 11 Pro Max 
 - iOS 12.1
 - Version AmazonChimeSDK: [e.g. 0.11.1]
 - Version AmazonChimeSDKMedia: [e.g. 0.7.1]
- React Native app.

**Additional context**
Here is the added methods inside the bridge (NativeMobileSDKBridge.m) : 
```
RCT_EXPORT_METHOD(pauseRemoteVideoId:(NSNumber * _Nonnull)tileId) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [meetingSession.audioVideo pauseRemoteVideoTileWithTileId: [tileId integerValue]];
  });
}

RCT_EXPORT_METHOD(resumeRemoteVideoId:(NSNumber * _Nonnull)tileId) {
  dispatch_async(dispatch_get_main_queue(), ^{
    [logger infoWithMsg:[NSString stringWithFormat:@"resumeRemoteVideoId %ld", (long)tileId]];
    [meetingSession.audioVideo resumeRemoteVideoTileWithTileId: [tileId integerValue]];
  });
}
```

**Comment by hokyungh** [comment]
@LilianAlvarez123 could you confirm if you are calling any [stopRemoteVideo](https://aws.github.io/amazon-chime-sdk-ios/Classes/DefaultAudioVideoController.html#/c:@M@AmazonChimeSDK@objc(pl)AudioVideoControllerFacade(im)startRemoteVideo)? Do you have details what happens (like code path) on when app is backgrounded.  There is Do you also mind opening this issue in [react-native github](https://github.com/aws-samples/amazon-chime-react-native-demo)?

**Comment by LilianAlvarez123** [comment]
Hello @hokyungh !

Thanks for the quick feedback. I did some extensive tests this morning and the problem occurs without going to background too. As long as we try to optimize the video stream network. If we pause the video, it's not possible to resume it.

We never call stopRemoteVideo() method.

I will put a message on the github repository.

**Comment by hokyungh** [comment]
Closing for https://github.com/aws-samples/amazon-chime-react-native-demo/issues/29
