### ISSUE TITLE
chooseAudioDevice with newly created MediaDeviceType

### ISSUE THREAD

**Issue by alexmccabe** [aws/amazon-chime-sdk-ios#167]
**Describe the bug**
I am using React Native to choose the `MediaDevice` on an iPhone. Initially I created a new `MediaDeviceType` to pass into the `chooseAudioDevice` method. Unfortunately this does not work as the SDK stores the media devices in-memory, and creating a new instance of one will not select it.

**To Reproduce**
Converting the string to the `MediaDeviceType` enum type:

```swift
private func getMediaTypeStringToEnum(type: String) -> MediaDeviceType? {
    switch (type) {
    case "audioBluetooth":
      return .audioBluetooth
    case "audioWiredHeadset":
      return .audioWiredHeadset
    case "audioBuiltInSpeaker":
      return .audioBuiltInSpeaker
    case "audioHandset":
      return .audioHandset
    case "videoFrontCamera":
      return .videoFrontCamera
    case "videoBackCamera":
      return .videoBackCamera
    case "other":
      return .other
    default:
      return nil
    }
  }
```

Basic example:

```swift
let stringType = "audioBluetooth"
let label = "Media Device Label"
guard let enumType = getMediaTypeStringToEnum(type: mediaType) else { throw MeetingModelError.invalidAudioDevice }
let mediaDevice = MediaDevice(label, enumType)
```

**Expected behavior**
I would expect the chosen media device to have changed when creating a new instance of `MediaDevice`. This works in the Android SDK. Or at the very least have this problem documented either on the GitHub, or in the source code if it's marked as a non-issue.

**Test environment Info (please complete the following information):**
 - Device: [iPhone6s]
 - OS: [iOS14]
 - Version AmazonChimeSDK: [e.g. 0.11.1]
 - Version AmazonChimeSDKMedia: [e.g. 0.7.1]

**Additional context**
I was able to workaround this by re-fetching the device list and matching against the label to get the actual media device that's stored in-memory.

```swift
let audioDevices = self.meetingSession.audioVideo.listAudioDevices()
    
guard let nextDevice = audioDevices.first(where: { $0.label == label})
else {
  throw MeetingModelError.invalidAudioDevice
}

self.meetingSession.audioVideo.chooseAudioDevice(mediaDevice: nextDevice)
```
I realise that this is a non-issue for entirely native iOS developers, however this may be something that could trip up anyone working on their own React Native Bridge, or have any other external API be able to switch audio source.

**Comment by hokyungh** [comment]
Thank you for reporting. @alexmccabe we'll make sure to update the doc. 

For iOS audio device, we are expecting `AVAudioSessionPortDescription.` You can use `MediaDevice.fromAVSessionPort(AVAudioSessionPortDescription)` to create one if you have reference to `AVAudioSessionPortDescription`.

**Comment by alexmccabe** [comment]
I don't have an `AVAudioSessionPortDescription`, I'm using the more simplistic `init` method, which takes a `MediaDeviceType` as the second parameter. This is because I'm building a universal app using React Native, and need as similar functionality with Android as possible (not the only person on the team, and we are all non-native developers).

Anyway, thanks for getting back to me and adding to the docs!

**Comment by zhinang-amazon** [comment]
Hi @alexmccabe, we added usage documentation regarding [choosing audio device](https://github.com/aws/amazon-chime-sdk-ios#use-case-4-choose-audio-device-by-passing-mediadevice-object). 
Closing the issue, let us know if you still have questions.

**Comment by alexmccabe** [comment]
Thanks! I'm no longer on the project that this was related to, but I've passed it on.
