### ISSUE TITLE
Video calling is not working on Simulator as like other video calling SDK

### ISSUE THREAD

**Issue by pravintate** [aws/amazon-chime-sdk-ios#17]
I'm using Chime iOS demo app. 
So when I'm trying video calling feature on real device like iPhone and iPad i'm able to see my and other side person video with audio as well.
But when I'm checking same thing on iOS simulator (iOS: 13) then audio is working fine from both side. but in video i can only able to see next calling person video not mine. 
Due to that reason I'm not able to test Video feature on iOS simulator.

**Comment by hokyungh** [comment]
Would you be able to elaborate on statement "Video calling is not working on Simulator as like other video calling SDK?" 
For instance,
1. What are some of other video calling SDK you are referring? 
2. If it is not working, are you not receiving any video from server or turning self video is not working? If it is latter case, I think iOS simulator does not support camera. Correct if I am wrong.

Let us know these details or if you have logs, it might help us debug as well. Thank you!

**Comment by pravintate** [comment]
@hokyungh  Thanks for replied. 
As like zoom we can do video calling on simulator. 
I have checked video calling response and I'm able to see other side person video and we can also talk at both side. (Audio is working fine)
But my video is not visible to me on iOS simulator, so is there any setup for that?

**Comment by hokyungh** [comment]
Thank you for response. I am not too sure how other SDK bypass it, but according to [Apple's doc](https://help.apple.com/simulator/mac/current/#/devb0244142d), simulator does not support camera, so you won't be able to see yourself with simulator. Let us know if you have further question.

**Comment by pravintate** [comment]
@hokyungh  Thanks.

**Comment by pravintate** [comment]
Hey, i'm facing one issue which is presented in chime app as well as chime
ios demo app.

When any joining leave meeting or i leaves the meeting app is crashing.

I have checked it in you app there also facing problem.

**Comment by hokyungh** [comment]
@pravintate would you be able to open new issue with this problem and provide details on it?

**Comment by pravintate** [comment]
Same ticket already created on github from my teammates
