### ISSUE TITLE
Play audio through speaker instead of earpiece

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-ios#184]
When I start the Chime meeting on my device using :

```
NSError* error = nil;
BOOL started = [meetingSession.audioVideo startAndReturnError:&error];
```

The audio from the other attendees comes out of the iPhone earpiece. I'm not sure it's the right way to call it. I mean I can hear the other attendees by putting my ear at the top of the iPhone, as if I was speaking to someone on the phone.

However, I would like to be able to interact with the other attendees by receiving the audio from the iPhone speakers (the bottom part of the phone).

Is there a way to do so ?

Thanks in advance !

**Test environment Info (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.2
 - Version AmazonChimeSDK: 0.12.1
 - Version AmazonChimeSDKMedia: 0.8.1

**Comment by hokyungh** [comment]
@rlebosse have you tried using [listAudioDevices](https://aws.github.io/amazon-chime-sdk-ios/Classes/DefaultDeviceController.html#/c:@M@AmazonChimeSDK@objc(pl)DeviceController(im)listAudioDevices) which should return speaker and then you can call [chooseAudioDeivce](https://aws.github.io/amazon-chime-sdk-ios/Classes/DefaultDeviceController.html#/c:@M@AmazonChimeSDK@objc(pl)DeviceController(im)chooseAudioDeviceWithMediaDevice:). You can also see [Demo](https://github.com/aws/amazon-chime-sdk-ios/blob/9bf810ac1c4adbbd87e5eaab4346180c6ae397f3/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#L348). Let us know if you have further question.

**Comment by zhinang-amazon** [comment]
Closing since we have not heard back. Feel free to reopen if this remains an issue.

**Comment by rlebosse** [comment]
Hello, sorry I did not respond to the issue. I did exactly what @hokyungh advised and it works really well.
Thanks a lot !
