### ISSUE TITLE
URL INCONSISTENCY ON ANDROID/IOS IS CAUSING "Unable to join meeting please try different meeting ID"

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#188]
On android url is supplied as https://yurid.execute-api.us-east-1.amazonaws.com/Prod
But I tried to supply the same url (https://yurid.execute-api.us-east-1.amazonaws.com/Prod) on iOS but was getting "Unable to join meeting please try different meeting ID" I was very confused and was about giving up on the SDK because I have spent months and still getting the same error until I started tracing the HTTP response then I added slash(/) to the end i.e https://yurid.execute-api.us-east-1.amazonaws.com/Prod/ then it worked miraculously.

**Comment by hokyungh** [comment]
Thank you for the report and sorry for the confusion. We'll update our demo app to handle those cases as well.

**Comment by hokyungh** [comment]
There has been new release with this change in the demo application. I'll close this issue. Feel free to reopen if you have any question.
