### ISSUE TITLE
Video Call Issue IOS app (Swift 5)

### ISSUE THREAD

**Issue by prashanth-icliniq** [aws/amazon-chime-sdk-ios#19]
**Describe the bug**

I give join button on ViewController screen and then it moves MeetingViewController on Button Some messages Showing and then am not getting Roster list& Videos also it's Empty Not Show anything 

URL - xxxx-xxx.amazonaws.com/Prod/join?title=987&name=xdxd&region=us-east-1

**Screenshots**
i Attach Roster Screen & Videos Screen

![Screen Shot 2020-04-27 at 1 13 14 PM](https://user-images.githubusercontent.com/52283574/80346772-e65ce980-8888-11ea-80a5-667fb8fd5653.png)

![Screen Shot 2020-04-27 at 1 13 14 PM](https://user-images.githubusercontent.com/52283574/80346808-f96fb980-8888-11ea-9bff-ff12651c3ed2.png)

![Screen Shot 2020-04-27 at 1 18 35 PM](https://user-images.githubusercontent.com/52283574/80347209-a4807300-8889-11ea-92eb-a967fa678a47.png)

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone SE]
 - OS: [e.g. iOS13.3.1]
 - Version AmazonChimeSDK: 0.5.1
 - Version AmazonChimeSDKMedia: 0.4.1

**Comment by hokyungh** [comment]
Thank you for reporting issue. The UI seems odd as well. It should be mic -> camera -> speaker -> phone down icons. Is it because you have changed it or is this actually what you get from our demo app? 

For your issue, we might need little more details in order to figure out what is going on. Would you be able to put logs in [attendeeDidJoin](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#L386).

Would you also be able to provide logs after putting logs?

**Comment by hokyungh** [comment]
Any updates on this issue?

**Comment by prashanth-icliniq** [comment]
I don't know now it's work  automatically i just change icon only on that
speaker and etc... i need example for multiple video function code because
am facing index error pls send demo how do I do

**Comment by prashanth-icliniq** [comment]
hi Nick,
   one more thing how do I change video quality on iOS SDK because of that
video quality very low when I look that iOS video in another platform or
same platform very low

Prashanth T D
IOS Developer
www.icliniq.com <https://www.icliniq.com/?utm_campaign=mail_sign_internal>

**Comment by prashanth-icliniq** [comment]
hi Nick,

I don't know how it's works automatically I just change icon only on that
speaker and etc... otherwise I use same code only **I need example for multiple video function code because am facing index error pls send demo how do I do**

one more thing how do I change **video quality** on iOS SDK because of that
video quality very low when I look that iOS video in another platform or
same platform **very low**

**Comment by hokyungh** [comment]
Thank you. Good that it works. 

Example for multiple video is not currently in demo app, but my suggestion would be 
Change the number [here](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#L571) and change [ratio](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingViewController.swift#L608). Make sure to keep the list of current video tiles that is rendering.

Changing Video quality is not supported currently. Based on network condition, it should increase or decrease the quality, so if you are in good network it should display good video quality
We would love to hear use cases. Could you fill out [form](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html)?

**Comment by prashanth-icliniq** [comment]
Thanks i find that how to connect multiple video calls and i facing issues
on camera screen(our screen) zoom-in and zoom-out automatically that time
screen blinking i don't know why I facing that you have any idea on that

**Comment by prashanth-icliniq** [comment]
Hello 
  how do I install chime as a cocoa pod in our project we using pod framework only

**Comment by prashanth-icliniq** [comment]
![Screenshot 2020-05-02 at 12 54 50 PM](https://user-images.githubusercontent.com/52283574/80858782-3832b480-8c79-11ea-9bd3-3ddd33c2514b.png)
 when I try to build App i facing this issue

**Comment by mitankit** [comment]
@prashanth-icliniq We would prefer if you create new github issue for any new problem you are facing. Grouping all the problems in a single thread makes it more difficult to track them and difficult to search for any new person who is facing the same problem.

**Comment by hokyungh** [comment]
@prashanth-icliniq. It will be great if you can open new issues. 
To answer your questions one by one
> zoom-in and zoom-out automatically that time

I think if network is unstable, it might try to adjust the resolution or ratio, which might end up zooming in or out.

> how do I install chime as a cocoa pod in our project we using pod framework only

As answered [here](https://github.com/aws/amazon-chime-sdk-ios/issues/15). Currently SDK is not on-boarded with CocoaPods, Carthage, Swift Package Manage yet. We are working on on-boarding them to these popular platforms.

Thank you!

**Comment by mitankit** [comment]
@prashanth-icliniq Wanted to check if any of your question is still unanswered or unresolved?

**Comment by mitankit** [comment]
Since there is no more questions from reporter, I am closing this issue. Feel free to reopen or create a new one if you see any issue.
