### ISSUE TITLE
Render Video In SWIFTUI

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#192]
My project is completely built using SWIFTUI no storyboard. I was able to get this to work and the audio call works perfectly fine but I don't know how to render the video signal in SWIFTUI any help on this?  I have tried meetingModel.videoModel but don't know where or how to bind this to a view in SWIFTUI. Any help or idea please?

**Comment by hokyungh** [comment]
We'll use https://github.com/aws/amazon-chime-sdk-ios/issues/120 as reference and close this issue. Unfortunately, we don't have any complete example of swift UI. We have added to our backlog and we'll update the issue ticket whenever we have any updates.
