### ISSUE TITLE
Error when building project using XCode 12.3

### ISSUE THREAD

**Issue by josechagas** [aws/amazon-chime-sdk-ios#195]
**Describe the bug**
When I try to run my project on a real device I get the error bellow
**Building for iOS, but the linked and embedded framework 'AmazonChimeSDK.framework' was built for iOS + iOS Simulator.**

**To Reproduce**
1. Go to 'Your project directory'
2. Click on 'Run'
3. Wait for the error

**Expected behavior**
The build should not fail. It was working on the previous version of Xcode.

**Logs**
Building for iOS, but the linked and embedded framework 'AmazonChimeSDK.framework' was built for iOS + iOS Simulator.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS14.2]
 - Version AmazonChimeSDK: [e.g. 0.13.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.9.0]

**Comment by speedmetal** [comment]
Try this solution:
https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built

It worked for me.

**Comment by abdulrehman87** [comment]
I fixed this issue by following these steps in Xcode 12.3

1. Facing error "Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulator"
2. Buildsetting -> ValidateWorkspace change it to YES & Build library for distribution change it to YES & Skip Install No
3. Archive app again it will fail
4. Buildsetting -> Build library for distribution and change it to NO
5. Archive
6. Archive successful

**Comment by hokyungh** [comment]
We'll add enhancement label for this issue. It looks like XCFramework is the way to go.

**Comment by abdulrehman87** [comment]
@hokyungh when we can expect XCFramework for the problem ? Because we are unable to archive

**Comment by hokyungh** [comment]
@abdulrehman87 Sorry for inconvenience. As mentioned in #129 , we are actively working on it. We'll update the thread when it is released.

**Comment by zhinang-amazon** [comment]
Hi @abdulrehman87,
Our team just released v0.15.0 with XCFramework support. You can find the new `.xcframework` format after unzipping the `.tar.gz` files.
Can you see if this resolves your issue?

**Comment by abdulrehman87** [comment]
@zhinang-amazon  thanks for your efforts. we will integrate and let you know

**Comment by k-zahid** [comment]
@zhinang-amazon  Thanks for informing us and glad it worked.

**Comment by zhinang-amazon** [comment]
Will close for now. Feel free to reopen if this is still an issue.

**Comment by SeanRenet** [comment]
I am getting this issue in XCode 12.5

**Comment by hokyungh** [comment]
@SeanRenet are you using xcframework or normal framework?

**Comment by SeanRenet** [comment]
@hokyungh, 

> @SeanRenet are you using xcframework or normal framework?

xcframework.  It is what is generated from npx-create-react-native-app

**Comment by mahesh-reddy-ios** [comment]
> I was facing issue on Archiving and fixed the issue by following these steps in Xcode 12.3
> 
> 1. Facing error "Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulator"
> 2. Buildsetting -> ValidateWorkspace change it to YES & Build library for distribution change it to YES & Skip Install No
> 3. Archive app again it will fail
> 4. Buildsetting -> Build library for distribution and change it to NO
> 5. Archive
> 6. Archive successful

@abdulrehman87  can u please let me know process for building simulator and device which is called fat binary file
