### ISSUE TITLE
Unable to install app after archiving and distributing

### ISSUE THREAD

**Issue by abdulrehman87** [aws/amazon-chime-sdk-ios#197]
**Describe the bug**
Unable to install app after archiving and distributing but working fine in debug mode, app icon staying gray

**To Reproduce**
1. Install Xcode 12.3
2. go to framworks, libraries and embedded content and make Amazon chime sdk & media sdk Embed & sign
3. Archive app 
4. Facing error "Building for iOS Simulator, but the linked and embedded framework was built for iOS + iOS Simulator"
5. Buildsetting -> ValidateWorkspace change it to  YES & Build library for distribution change it to  YES & Skip Install No
6. Archive app again it will fail
7. Buildsetting -> Build library for distribution  and change it to NO 
8. Archive
9. Archive successful 
10. Install app to iphone
11. App staying Gray and unable to install
12. Repeated same steps on another iMac 
13.  there facing code signing AmazonChime.framwork failed on archiving app
14. if goto framworks, libraries and embedded content and make Amazon chime sdk & media sdk and convert it to do not embed
15. don't use amazon services then
15. app installation succesfull and working fine.

**Expected behavior**
App should install after archiving as it was starting normally before 26 dec 2020
  
![Screen Shot 2021-01-03 at 3 57 02 PM](https://user-images.githubusercontent.com/69900506/103479727-b0411380-4de0-11eb-844f-282c3777a772.png)
![Screen Shot 2021-01-03 at 4 30 27 PM](https://user-images.githubusercontent.com/69900506/103479772-04e48e80-4de1-11eb-81e1-e5f8125102e6.png)

**Comment by hokyungh** [comment]
Thank you for reporting. Were you using 12.2 or older version of Xcode before Dec 26? Do you also know if you run any script as described https://github.com/aws/amazon-chime-sdk-ios/issues/29?

**Comment by abdulrehman87** [comment]
Yes I was using Xcode 12.0 before dec 26 and Yes I was using script described in #29. Suddenly I start facing this gray app icon issue even in Xcode 12.  Then I updated app certificates and profiles but still same issue. Also tried updating Xcode to 12.3 still same gray app icon issue I am facing.
I think some code signing issue with Amazon chime sdk even I tried bitcode and bitcode free SDKs. Once I removed Amazon Chime SDK App start archiving and installing normally.

**Comment by k-zahid** [comment]
@hokyungh  any update on this?

**Comment by k-zahid** [comment]
@zhinang-amazon Is there any update or a temporary solution to fix the issue and prepare a build?

**Comment by zhinang-amazon** [comment]
Hi @k-zahid 
Our team just released v0.15.0 with XCFramework support. You can find the new .xcframework format after unzipping the .tar.gz files.
Can you see if this resolves your issue?

**Comment by zhinang-amazon** [comment]
Closing since @k-zahid commented on #195 that XCFramework is working.
