### ISSUE TITLE
Ionic|Cordova support

### ISSUE THREAD

**Issue by karthikarul20** [aws/amazon-chime-sdk-ios#20]
I see that there are already requests to support cross platforms like react-native and flutter. Do you guys intend to create a Cordova plugin? It would be great if guys can do one.

**Comment by mitankit** [comment]
There is a problem to support it on iOS. Cordova operates on webview and iOS's webview ([wkwebview](https://developer.apple.com/documentation/webkit/wkwebview)) doesn't support webrtc which is required for amazon-chime-sdk-ios to work.

**Comment by Nkay** [comment]
I think the answer is not really suitable for the question asked, as he was probably aware that it does not work with native cordova, thats why he asked for a plugin, that has access to the native streams.
