### ISSUE TITLE
Green light remains active even after meeting end

### ISSUE THREAD

**Issue by nealmanaktola** [aws/amazon-chime-sdk-ios#200]
**Describe the bug**
When calling audioVideo.stop(), the green light indicator is still on. 

Workaround: Manually turning the video off resolves issue and turns off the green light. 

To read more about the green light indicator: https://support.apple.com/en-ca/HT211876

**To Reproduce**
1. Start Meeting
2. Turn on video
3. Notice green light
4. End meeting
5. Green light remains active

**Expected behavior**
Green light should turn off when a meeting ends.

**Logs**
If applicable, add logs from console to help explain your problem.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.3
 - Version AmazonChimeSDK: [e.g. 0.12.2]
 - Version AmazonChimeSDKMedia: [e.g. 0.8.2]

**Additional context**

**Comment by tianyux-amz** [comment]
Hi @nealmanaktola,

I tried to reproduce your issue using iPhone 12 Pro with iOS 14.3 and iPhone 6s with iOS 14.3, but I couldn't reproduce the issue.

- What's the ratio to reproduce this issue on your side? I tired 50 times but did not repro once.
- After you call `audioVideo.stop()`, did you get `videoSessionDidStopWithStatus()` and `audioSessionDidStopWithStatus()` callbacks as expected? Did you get any error in the logs? Could you share your logs if possible?

Best,
Tianyu

**Comment by nealmanaktola** [comment]
1. Ratio was 100%.
2. I'll provide you logs, and I'll validate if I get those statuses.

Thanks!

**Comment by tianyux-amz** [comment]
@nealmanaktola Just to be clear, were you running the ReactNative demo, the iOS demo, or your own application?

**Comment by tianyux-amz** [comment]
I was able to reproduce the issue in the latest ReactNative demo.

Env: iPhone 6s with iOS 14.3, running SDK v0.12.2 and Media v0.8.2.

Steps:
1. UserA joined meeting via web serverless demo.
2. UserB joined meeting via RN demo and enabled video. Noticed the gree light in the status bar.
3. UserB left meeting. Noticed the green light is still on. In the log I saw video client was stopped though:
```
RNDemo[4032:183886] [INFO] NativeMobileSDKBridge - API/DefaultAudioVideoFacade/stop
RNDemo[4032:183803] [INFO] NativeMobileSDKBridge - Stopping VideoClient
RNDemo[4032:183339] [INFO] NativeMobileSDKBridge - videoClientDidStop
```
4. AudioClient was not disconnected successfully. UserA can still hear voice from UserB.

**Comment by LilianAlvarez123** [comment]
Hello,

I did reproduce a very very similar problem on iOS with the latest version of Amazon Chime iOS : "0.13.0" and Media SDK "0.9.0".

To reproduce : 
1 - Launch a live with an iPhone 
2 - Join it from the web
3 - Mute your Camera and Microphone with the iPhone
4 - Leave the live while keeping it open with the iPhone => **still got the green light after leaving** 
Log : "OnError Failed to set mute state"
5 - Re join the live with the iPhone.
6 - Live failed to start.
Logs :  OnError Failed to start meeting, error: illegalState 


I get this error one out of four times.
I am using an iPhone 11 Pro with iOS 14.1

**Comment by tianyux-amz** [comment]
@LilianAlvarez123 Are you running ReactNative application, or native application on iOS?

**Comment by LilianAlvarez123** [comment]
it's a React Native application.

**Comment by tianyux-amz** [comment]
Thanks for confirming. Will get back once we found the root cause of the issue.

**Comment by nealmanaktola** [comment]
React native for me as well

**Comment by tianyux-amz** [comment]
The issue was introduced in #155. Will talk to the PR authors and come up with a proper fix.

**Comment by tianyux-amz** [comment]
PR for the fix is being reviewed.

**Comment by tianyux-amz** [comment]
We are preparing a hotfix release tonight. Will resolve the issue once the hotfix is out.

**Comment by tianyux-amz** [comment]
The fix was released. Please try out the latest SDK v0.13.1 and let us know if you run into any other issues. Thanks!
