### ISSUE TITLE
In iphone call goes on mute when phone goes on sleep mode so the call is not working 

### ISSUE THREAD

**Issue by NehaSalve1393** [aws/amazon-chime-sdk-ios#209]

**Comment by zhinang-amazon** [comment]
Hi @NehaSalve1393,

I'm not able to reproduce this issue with our demo app in sleep mode. Can you provide details on:
- what devices/iOS version you are using
- what AmazonChimeSDK and AmazonChimeSDKMedia version you are using
- repro steps

**Comment by hokyungh** [comment]
@NehaSalve1393 Could you provide us with more information?

**Comment by arehman86** [comment]
@zhinang-amazon The problem is when the phone goest to sleep mode, the audio session stoped with the reason **Unknown** after few seconds. I created an issue with proper logs and reproducible steps
https://github.com/aws/amazon-chime-sdk-ios/issues/262

**Comment by dylonChime** [comment]
I will close this for now. Feel free to reopen if you still have the issue.
