### ISSUE TITLE
0.5.1 release is missing .swiftinterface files, won't build with Xcode 11.4.1

### ISSUE THREAD

**Issue by sjmadsen** [aws/amazon-chime-sdk-ios#21]
**Describe the bug**
Replacing the older 0.5.0 `.framework` binaries with the 0.5.1 version produces a new build error: `Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2.2 compiler: .../AmazonChimeSDK.framework/Modules/AmazonChimeSDK.swiftmodule/arm64-apple-ios.swiftmodule`

**To Reproduce**
1. Drop the 0.5.1 release `.framework` into an existing, buildable app.
2. Build with Xcode 11.4.1.
3. See error

**Expected behavior**
Apps still build.

**Test environment Info (please complete the following information):**
 - Version AmazonChimeSDK: 0.5.1
 - Version AmazonChimeSDKMedia: 0.4.1

**Additional context**
The AmazonChimeSDKMedia framework does not have the same problem. Looking at the differences in my Git repo, the `.swiftinterface` files are missing from the 0.5.1 release binary.

**Comment by hokyungh** [comment]
Thank you for reporting issue. For now, would you be able to download [0.5.2](https://github.com/aws/amazon-chime-sdk-ios/pull/26) and see if issue is fixed?

**Comment by sjmadsen** [comment]
The build issue is fixed. Thank you.

There is a new documentation warning: `Parameter 'status' not found in the function declaration of audioSessionDidStopWithStatusWithSessionStatus`.

**Comment by hokyungh** [comment]
Nice. Could you confirm that [audioSessionDidStopWithStatus](https://aws.github.io/amazon-chime-sdk-ios/Protocols/AudioVideoObserver.html#/c:@M@AmazonChimeSDK@objc(pl)AudioVideoObserver(im)audioSessionDidStopWithStatusWithSessionStatus:) parameter is `sessionStatus`?

**Comment by sjmadsen** [comment]
It is, but the warning is about the doc comment for that function in the protocol (presumably in the SDK?). There's documentation for a parameter `status` that doesn't exist.

**Comment by hokyungh** [comment]
Thank you for reporting. We do see [status](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/AudioVideoObserver.swift#L43) in the `videoSessionDidStartWithStatus`. We'll update the comment in the next release, but it seems weird that warning is on [audioSessionDidStopWithStatus](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/AudioVideoObserver.swift#L26). Does it happen on previous build or only specific to 0.5.2?

**Comment by sjmadsen** [comment]
I think the warning is generated when the build system parses the framework's headers, not on the implementing function. I could be wrong.

I don't recall it being an issue on earlier releases, but it may have been there and I missed it.

**Comment by hokyungh** [comment]
Thank you for reporting. We'll investigate on it.
