### ISSUE TITLE
Binding video tileId to multiple DefaultVideoRender view

### ISSUE THREAD

**Issue by arehman86** [aws/amazon-chime-sdk-ios#211]
When I try to bind a tileId to more than one render views, the sdk bind it with the latest view and unbind it from the previous one.

The use case is we have a speaker view in which all the render views are shown in horizontal collection view and a single view in which the active speaker video will be shown on the basis of active speaker callback. But unfortunately I am not able to achieve this using your sdk.

Similar issue
https://github.com/aws/amazon-chime-sdk-ios/issues/95 (Inactive)

**Comment by hensmi-amazon** [comment]
Hi Adeel, see a similar issue in the android SDK for a workaround: https://github.com/aws/amazon-chime-sdk-android/issues/204 (it also includes an iOS code snippet).  

Thanks for mentioning the use case and let us know if that works for you.

**Comment by arehman86** [comment]
@hensmi-amazon The code snippet you shared is similar to **VideoSourceAdapter** AmazonChimeSDK project. Is there any working example of how to bind one tile to two different render views?

**Comment by hensmi-amazon** [comment]
`VideoRenderView` is just a `VideoSink` alias.  In  this workaround you just bind the broadcaster, and then call `addVideoSink` on the broadcaster with both of your render views.

**Comment by arehman86** [comment]
@hensmi-amazon you are giving a very high level picture which I am not getting it frankly. Right now I am using **DefaultViewRenderView** from the SDK and using **bindVideoView** and **unbindVideoView** methods to start/stop the video. In **bindVideoView** method we check for the existing tile against the tileId and unbind it from the previous one and bind it with the new one. So you suggest that we don't need to use **bind/unbindVideoView** methods now?

**Comment by arehman86** [comment]
A working example would be really appreciated as we really need to show the video on more than one views.

**Comment by hensmi-amazon** [comment]
Something like:
```
let renderViewOne = ...
let renderViewTwo = ...
let videoFrameBroadcaster = VideoFrameBroadcaster()

videoFrameBroadcaster.addSink(renderViewOne)
videoFrameBroadcaster.addSink(renderViewTwo)
audioVideoFacade.bindVideoView(videoFrameBroadcaster, tileId)
```
should work.  I understand the alias of `VideoRenderView` and `VideoSink` is confusing, and we may try to improve the vocabulary through deprecation in the future.

**Comment by arehman86** [comment]
What is **renderViewOne/Two**? DefaultVideoRenderView or something else?

**Comment by hensmi-amazon** [comment]
In your case they would be `DefaultVideoRenderView`s

**Comment by hokyungh** [comment]
I'll close this issue. Feel free to reopen it if you have more questions.

Thanks!

**Comment by g-malinov** [comment]
audioVideoFacade.bindVideoView(videoFrameBroadcaster, tileId)

I can't do this because 
`Could not cast value of type 'webmeeting.VideoFrameBroadcaster' (0x10247c5a0) to 'AmazonChimeSDK.VideoRenderView' (0x103d25dd8).`

**Comment by g-malinov** [comment]
@hokyungh 
Do you have any idea?

**Comment by hensmi-amazon** [comment]
What version of the SDK are you using?  `VideoSink` was added (and `VideoRenderView` [refactored](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/VideoRenderView.swift) in 12.0.  Could you post your code for `VideoFrameBroadcaster`?
