### ISSUE TITLE
Rendering Video in SWIFTUI is the greatest limitation of this SDK.

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#213]
Going forward after months of trying this SDK I have come to find the greatest limitation of this SDK. Although the Android SDk is superb but the iOS SDK seems not very compatible with the cutting edge SwiftUI technology going forward.

There seems to be no way to display VideoRenderView in SwiftUI.
This is painful considering am a stack SWIFTUI developer and my entire project is built using SWIFTUI. I don't know much of the StoryBoard manipulation. Very sad!!!

**Comment by hokyungh** [comment]
Thank you for opening the issue and sorry for lack of support for the SwiftUI. We'll continue to add new features and if we have any update on SwiftUI, we'll update on https://github.com/aws/amazon-chime-sdk-ios/issues/120 thread. 

I'll close this and have reference to https://github.com/aws/amazon-chime-sdk-ios/issues/120. 

Thank you and let us know if you have any further question.
