### ISSUE TITLE
When using Chime SDK for iOS in AppCenter - opening the build configuration does not work anymore

### ISSUE THREAD

**Issue by hacktick** [aws/amazon-chime-sdk-ios#214]
**Describe the bug**
We have included the current Chime SDK for iOS (v0.13.1) and AmazonChimeSDKMedia-0.9.0.tar.gz in an app, that is build via AppCenter.
At first we thought everything worked fine.
But when we try to open the build configuration AppCenter hangs and is unable to retrieve any further informations.
Furthermore through excess IO usage our DevOps Access is throttled.

We have filed a support ticket as well to the AppCenter guys - because we don't know where the exact error is.
Perhaps someone can falsify or truthify (? :-D) our current informations.

**To Reproduce**
1. Create iOS Swift Project in DevOps
2. Reference Chime SDK for iOS
3. Open Build Configuration do your settings
4. Build
5. Open Build Configuration and check whether data could be loaded or not

**Expected behavior**
To open the build configuration

**Test environment Info (please complete the following information):**
 - Version AmazonChimeSDK: v0.13.1
 - AmazonChimeSDKMedia-0.9.0.tar.gz
- AppCenter (unlimited builds activated)

**Comment by hokyungh** [comment]
Thank you for opening the issue. However, it seems hard for us to debug or give suggestion based on information provided. Would you be able to provide the followings?

1. Was this happening before with other version of our SDK?
2. If you use other application, do you have similar problem or is it only issue with our SDK?

Thank you and let us know if you have any further information.

**Comment by hacktick** [comment]
> 1. Was this happening before with other version of our SDK?

We don't know for sure. We have only just opened the build configuration.

> 2. If you use other application, do you have similar problem or is it only issue with our SDK?

We can pretty much narrow it down to referencing "AmazonChimeSDKMedia". The size of the whole package seems to be the problem.

Why is the AmazonChimeSDKMedia file > 150 MB for iOS and only 15 MB for Android?

**Comment by hokyungh** [comment]
@hacktick iOS has more architectures to support. Additionally, bitcode support increase size on iOS framework. Just curious if you strip out simulator by using command described https://github.com/aws/amazon-chime-sdk-ios/issues/29, are you able to open build configuration?

**Comment by HMinning** [comment]
@hokyungh this won't help, since it only reduces the size of the generated build. The problem here is the large binary file in AmazonChimeSDKMedia and I think the size increased in recent versions. If you can't reduce the size, could you provide a cocoapod for the Chime SDK? See https://github.com/aws/amazon-chime-sdk-ios/issues/59
Right now it's only possible to include the frameworks manually and store them in the repo which is breaking the AppCenter build server.

**Comment by zhinang-amazon** [comment]
Closing this issue and our team will use #59 to track CocoaPods support.
