### ISSUE TITLE
String in DataMessage from iOS devices send with garbage

### ISSUE THREAD

**Issue by HMinning** [aws/amazon-chime-sdk-ios#217]
**Describe the bug**
Text from data message is not received correctly when send from iOS chime sdk.

**To Reproduce**
iOS Chime SDK 0.13.0, in Swift call
realtimeSendDataMessage(topic: "chat",
                                          data: message,
                                          lifetimeMs: 300000)
with the (String object) message = "12345678901234567890123456789012345678901234567890".

String received on the other side (server or Android device): "12345678901234567890123456789012345678901234567890������������"

I once had this stange string appended to my message: "������������SimulcastEncoderAdapter (VideoToolbox, VideoToolbox)"

It does not happen every time, but quite often.

**Expected behavior**
receive the string without garbage

**Test environment Info (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 14.3.
 - Version AmazonChimeSDK: 0.13.0
 - Version AmazonChimeSDKMedia: 0.9.0

Receiving side: AmazonChimeSDK: 0.9.0 on Android devices.

**Comment by hokyungh** [comment]
Thank you for reporting. We'll investigate and update the ticket.

**Comment by zhinang-amazon** [comment]
Hi @HMinning,

This is fixed in the latest 0.15.0 release. Let us know if this is still an issue for you.
Closing for now.
