### ISSUE TITLE
Attendee join/leave notifications not reliably delivered

### ISSUE THREAD

**Issue by sjmadsen** [aws/amazon-chime-sdk-ios#22]
**Describe the bug**
I've set up a `RealtimeObserver` in my app and added it to the current meeting session. `attendeesDidLeave(attendeeInfo:)` is never called, and `attendeesDidJoin(attendeeInfo:)` only sporadically.

**To Reproduce**
Well... we tried to bring up the demo serverless backend to check with the demo app, but it failed and we couldn't figure out why.

**Expected behavior**
Join and leave callbacks as attendees join and leave the meeting.

**Logs**
From the first device to join:
```Audio started connecting. Reconnecting: false
Audio successfully started. Reconnecting: false
Attendees joined: ["eebc0e27-a33e-4ff0-b16f-a9847f511940"]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e6ace0>]
Video connecting
Video started ok
Adding Video Tile tileId: 0 attendeeId: nil
Adding Video Tile tileId: 2 attendeeId: Optional("e20d29b4-6a5c-49e4-b22c-71e8a7082e6f")
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1cd80>]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1f3e0>]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1ac00>]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1aea0>]
```

You can see that I receive volume updates, which are also part of the `RealtimeObserver` protocol. So the observer is being registered properly.

From the second device to join:
```Audio started connecting. Reconnecting: false
Audio successfully started. Reconnecting: false
Video connecting
Video started ok
Adding Video Tile tileId: 0 attendeeId: nil
Adding Video Tile tileId: 1 attendeeId: Optional("eebc0e27-a33e-4ff0-b16f-a9847f511940")
```

Weirdly, no volume updates here, even though it's the same app, which a nearly identical code path to join an existing meeting (versus creating a new one). Additionally, we can see that the remote attendee is known to the SDK, since it has the ID when adding the video tile.

**Test environment Info (please complete the following information):**
 - Devices: iPhone XR, iPad 7th gen
 - OS: iOS 13.4.1
 - Version AmazonChimeSDK: 0.5.0
 - Version AmazonChimeSDKMedia: 0.4.0

**Comment by hokyungh** [comment]
Thank you for reporting issue.
We might need some clarification.
1. What is used for second device? 
2. If you swap first and second device does it always happen on second device that joins or is it happening on same device?
3. Do you have any logs printed. Does it give any error?

**Comment by sjmadsen** [comment]
1. I've been using an iPhone XR and an iPad 7th gen as the second device.
2. It doesn't matter which device joins the meeting first. The first device gets a single "join" event (itself), while the second device doesn't get any.
3. I don't see any obvious errors in the log. I noticed one weird thing: if the phone's mute switch is on, I'll see `Audio stopped for a reason: ok`, which appears to be from a failure, although it's reported to the app through `audioSessionDidStopWIthStatus(sessionStatus:)` and the code on that status is `.ok`.

**Comment by sjmadsen** [comment]
Update: this seems related to my app's integration with CallKit.

If the audio session isn't configured in the right place, and my `CXProviderDelegate` function doesn't call the `CXAction fulfill()` method promptly, I can't hear audio in the meeting from either side, and attendee join/leave notifications aren't reliably delivered.

Making some small changes to when I call `fulfill()` restores audio in the meeting (on both sides) and _also_ results in the expected join/leave notifications.

**Comment by hokyungh** [comment]
@sjmadsen thank you for reporting. I'll close the issue, but feel free to re-open it if you have issue.

**Comment by senthilece01** [comment]
@sjmadsen I am facing the same error. RealtimeObserver delegate methods are not calling when I open the app from the terminated state using push notification. Everything is working fine in the foreground state. Can you please share your suggestions or code?
