### ISSUE TITLE
Reconnection: Mobile Video Send Bug

### ISSUE THREAD

**Issue by tylerlot** [aws/amazon-chime-sdk-ios#221]
**Describe the bug**
Wanted to report a bug for the mobile client’s video reconnection logic between the mobile and web sdk. When we force the mobile client to reconnect to a meeting (toggling mobile device WiFi/LTE off/on, no web changes), we notice that after the mobile client reconnects, the mobile-video-send is not received by the web client (web client sees audioVideoTileWasRemoved fires after reconnection). The mobile local video preview remains intact. We are able to resolve this state by manually restarting the mobile client’s video feed.After reconnection there is no problem with the audio feed, this always resolves successful. The issue does not occur if the party who is “reconnecting” to the meeting is the web client.

**To Reproduce**
1. Join a demo meeting, one iOS Client one Web Client
2. Trigger reconnection on the mobile device by toggling WiFi/LTE settings
3. After mobile client reconnects, see that _sometimes_ the web client stops receiving video from the mobile client.
- we have been able to consistently reproduce this error, but it does not have a 100% repro rate

**Expected behavior**
We expect the video connection to restore as the audio does.

**Logs**
Please reach out for logs.

**Test environment Info (please complete the following information):**
 - Device: iPhone 8
 - OS: 14.2
 - Version AmazonChimeSDK: 0.12.2
 - Version AmazonChimeSDKMedia: 0.8.2

**Additional context**
We have been able to reproduce this issue on both iOS and Android platforms, and on separate devices. 
- Android issue: https://github.com/aws/amazon-chime-sdk-android/issues/222

We noticed the mobile app SDP contains 2 video tracks (the initial track, and a new one being offer). This is followed by logs indicating the web client receives a track event, but does not add the track as this attendee already has a tileId (logs attached). When the user attempts to workaround the bug by restarting their video, we see a log in the web client again that the stream does not belong to a known attendee. We believe the duplicate tracks to be the source of the issue here.

[TwoTrackSDPFromMobile.txt](https://github.com/aws/amazon-chime-sdk-ios/files/5874987/TwoTrackSDPFromMobile.txt)

**Comment by zhinang-amazon** [comment]
Thanks @tylerlot for reporting this. 
Our team is currently investigating this issue

**Comment by hensmi-amazon** [comment]
This should be fixed by https://github.com/aws/amazon-chime-sdk-js/pull/1073 .  Please let me know if there are still issues.
