### ISSUE TITLE
Reconnection: Mobile Send/Receive Video Failure

### ISSUE THREAD

**Issue by tylerlot** [aws/amazon-chime-sdk-ios#222]
This issue may be related to #221 , but filed separately for more clarity.

**Describe the bug**
Wanted to report a bug for the mobile client’s video reconnection logic between the mobile and web sdk. When we force the mobile client to reconnect to a meeting (toggling mobile device WiFi/LTE off/on, no web changes), we notice that after the mobile client reconnects, the mobile-video-receive stream is not received from the web client (also paired with linked issue 221 above - neither peer receives each others video). Toggling the video feed does not fix the web’s video receive. The mobile local video preview remains intact. After reconnection there is no problem with the audio feed, this always resolves successful. The issue does not occur if the party who is “reconnecting” to the meeting is the web client.

**To Reproduce**
2. Join a demo meeting, one iOS Client one Web Client
3. Trigger reconnection on the mobile device by toggling WiFi/LTE settings
4. After mobile client reconnects, see that sometimes the both peers stop receiving remote video

App reconnects audio and shows local video but remote video is missing.
Web reconnects audio and shows local video but remote video is missing.

**Expected behavior**
Both peers video streams reconnect successfully 

**Logs**
Please reach out for application logs.

Looking at the App hooks here. We noticed that in this situation, the `videoSessionDidStartConnecting` hook is not being fired. All subsequent disconnects/reconnects never attempt to start connecting video. Also, Turning local video on/off does nothing to change this. We get stuck in a state where we cannot restart video.

**Test environment Info (please complete the following information):**
- Device: iPhone 8
- OS: 14.2
- Version AmazonChimeSDK: 0.12.2
- Version AmazonChimeSDKMedia: 0.8.2

**Additional context**

We have only be able to reproduce this issue on iOS platforms, not Android - I think it may still be worth investigating in case the issue lies with the core webrtc media.

**Comment by zhinang-amazon** [comment]
Thanks @tylerlot for reporting this. 
Our team is currently investigating this issue

**Comment by hensmi-amazon** [comment]
This should be fixed by https://github.com/aws/amazon-chime-sdk-js/pull/1073 .  Please let me know if there are still issues.
