### ISSUE TITLE
EXC_BAD_ACCESS_mh_execute_header

### ISSUE THREAD

**Issue by Vhora01** [aws/amazon-chime-sdk-ios#228]
when I start video chat ,some time suddenly app is being crash.
show issue in Xcode terminal [INFO] MeetingViewController - videoClientCameraSendIsAvailable.
in Bugsnag ,report issue as
EXC_BAD_ACCESS_mh_execute_header
Attempted to dereference garbage pointer 0x3e097ffffe8.

**Comment by dylonChime** [comment]
Hi,
Can you please provide the following information?
Device used?
Operating System?
SDK version?
Media SDK version?
Repro steps?
Crash logs?

Thank you

**Comment by Vhora01** [comment]
On Mon, Feb 1, 2021 at 10:29 PM Dylon Dickinson <notifications@github.com>
wrote:

> Hi,
> Can you please provide the following information?
> Device used ==== iPhone XR
> Operating System ======= iOS 14.4
> SDK version ====== 0.6.1
> Media SDK version?
> Repro steps? when ever screen share from other device ,some time
> crashed.Randomly
> Crash logs
>

*[101:531] [57611] (video_renderer_adapter.cc:194): 10 metrics frames sent
with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps*

*2021-02-03 18:00:04.421189+0530 Roomzz[19832:5638651] [ERROR]
MeetingViewController - [101:531] [57611] (video_renderer_adapter.cc:194):
10 metrics frames sent with 0 FPS;
notify:video_remote_stream_unpaused_with_zero_fps*

*2021-02-03 18:00:04.458747+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - videoClientCameraSendIsAvailable*

*2021-02-03 18:00:04.617189+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - videoClientCameraSendIsAvailable*

*2021-02-03 18:00:04.708043+0530 Roomzz[19832:5638653] [ERROR]
MeetingViewController - [101:818] [74499] (webrtc_video_engine.cc:3264):
Absent receive stream; ignoring clearing encoded frame sink for ssrc 0*

*2021-02-03 18:00:04.804236+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - videoClientCameraSendIsAvailable*

*2021-02-03 18:00:04.945524+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - Adding Video Tile tileId: 3 attendeeId:
Optional("22c213bf-aff4-7ad9-243e-9f653051bbcc")*

*2021-02-03 18:00:04.945955+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - Binding VideoView to Tile with tileId = 3*

*2021-02-03 18:00:04.945975+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - Unbinding the view from tile: tileId:  3,
attendeeId: 22c213bf-aff4-7ad9-243e-9f653051bbcc*

*2021-02-03 18:00:04.945986+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - Binding the view to tile: tileId: 3, attendeeId:
22c213bf-aff4-7ad9-243e-9f653051bbcc*

*2021-02-03 18:00:05.127716+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - Media metrics have been received: [videoSendFps:
15.92117426620801, videoAvailableReceiveBandwidth: 30000000,
videoReceivePacketLossPercent: 0, audioReceivePacketLossPercent: 0,
videoSendRttMs: 205, videoReceiveBitrate: 229503.7270473884,
audioSendPacketLossPercent: 0, videoSendPacketLossPercent: 0,
videoAvailableSendBandwidth: 2274752, videoSendBitrate: 1284138.231615273]*

*2021-02-03 18:00:05.365843+0530 Roomzz[19832:5637922] [INFO]
MeetingViewController - videoClientCameraSendIsAvailable*




> Thank you
>
>
>

**Comment by hokyungh** [comment]
Hi it could be some random concurrency issue that is fixed in [0.7.0](https://github.com/aws/amazon-chime-sdk-ios/blob/master/CHANGELOG.md#070---2020-06-05). Do you mind upgrading the SDK/Demo to the latest and test it out again?

**Comment by dylonChime** [comment]
I'll close this issue for now. Feel free to reopen if the issue persists.
