### ISSUE TITLE
Error when calling stop() on DeafaultCameraCaptureSession during AVCaptureSession configuration lock

### ISSUE THREAD

**Issue by keverly** [aws/amazon-chime-sdk-ios#231]
When using `DefaultCaptureSession`, and rapidly alternating between calling `start()`/`stop()`, a `NSGenericException` occurs. Based on the logs it looks like a concurrency issue due to session.stop() being called while the configuration lock is active in the `start()`.

**Repro**

1. Create an instance of `DefaultCaptureSession`. 
2. Rapidly call `start()` and `stop()` on the instance (I have this hooked up to a video on/off toggle UI element). 

**Version**
Chime SDK: 0.14.0
ChimeMedia SDK: 0.10.0

**Logs**
[INFO] ChimeVideoCareCallLogger - Unbinding VideoView to Tile with tileId = 0
[INFO] ChimeVideoCareCallLogger - Unbinding the view from tile: tileId: 0, attendeeId:<attendee_id>
[INFO] ChimeVideoCareCallLogger - Starting local video with custom source
[INFO] ChimeVideoCareCallLogger - Binding VideoView to Tile with tileId = 0
[INFO] ChimeVideoCareCallLogger - Binding the view to tile: tileId: 0, attendeeId: <attendee_id>
[INFO] ChimeVideoCareCallLogger - Stopping local video
[INFO] ChimeVideoCareCallLogger - Unbinding VideoView to Tile with tileId = 0
[INFO] ChimeVideoCareCallLogger - Unbinding the view from tile: tileId: 0, attendeeId: <attendee_id>
[INFO] ChimeVideoCareCallLogger - Starting local video with custom source
[INFO] ChimeVideoCareCallLogger - Binding VideoView to Tile with tileId = 0
[INFO] ChimeVideoCareCallLogger - Binding the view to tile: tileId: 0, attendeeId: <attendee_id>

Exception:
`Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureSession stopRunning] stopRunning may not be called between calls to beginConfiguration and commitConfiguration'
terminating with uncaught exception of type NSException`

**Comment by zhinang-amazon** [comment]
Hi @keverly 
Thanks for reporting this issue. It looks like we need to lock on the start and stop call so that these invocations are atomic.
Our team will investigate this issue.

**Comment by dylonChime** [comment]
This issue was fixed in the most recent release. Feel free to reopen if the bug re-emerges.
