### ISSUE TITLE
iPhone video camera stops sending frames after creating too many DefaultRenderViews.

### ISSUE THREAD

**Issue by nealmanaktola** [aws/amazon-chime-sdk-ios#233]
**Describe the bug**

iPhone video camera stops sending frames after creating too many DefaultRenderViews.

I am using the react-native version of this app, however, the issue lies somewhere inside the ios-sdk.
After creating multiple default render views, (say 10-30?), the iOS camera stops sending frames and the user appears frozen.

I am unsure how created render views and the video camera is related, but this is very reproducible

**To Reproduce**
1. Keep creating new renderviews (either, leave and join the meeting repeatedly)
2. Eventually your video camera will stop sending frames, and other users will see you as frozen

**Expected behavior**
Should continue to work

**Logs**

**Screenshots**

**Test environment Info (please complete the following information):**
 - iPhone 11
 - iOS 14.3
 - 0.13.1
 - 0.13.1

**Additional context**

**Comment by zhinang-amazon** [comment]
Hi @nealmanaktola,
Did you reproduce this with our [react native](https://github.com/aws-samples/amazon-chime-react-native-demo) sample app?
When the issue happens, do you still see your camera video stream locally? Or is it also frozen for the sender's local video view?
Can you send us any relevant log?

**Comment by nealmanaktola** [comment]
I am using a fork of your react native sample app.
I do not see the camera video stream locally. Also, I don't see the frames being received for the tile. It's frozen on both ends

I'll reproduce and give you logs.....not sure if the logs will be *super* relevant though, since I don't see anything pointing to the issue.

**Comment by alnlau** [comment]
Feel free to re-open if this is still an issue for you.
