### ISSUE TITLE
DefaultVideoRenderView : keep track of the fact that first frame has been received (or not, yet)

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-ios#236]
When I bind a `videoTileId` to a view (using `DefaultVideoRenderView`), during a small amount of time, the remote video is received, therefore not received yet.

I guess it's due to the fact that no frame has been received yet.

Is there a way to keep track of the fact that the view has received (and displayed) a frame or not ?

This would be super useful in order to show something else while waiting for the first frame to show up and avoid user to see a blank view during this time.

Thanks a lot for your great work !

**Test environment Info (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.4
 - Version AmazonChimeSDK: 0.15.0
 - Version AmazonChimeSDKMedia: 0.11.0

**Comment by zhinang-amazon** [comment]
Hi @rlebosse 
Our `DefaultVideoRenderView` does not have any placeholder view while waiting for first frame.
If you want this capability, you can implement a customized `VideoRenderView` that renders a placeholder view at first, and once receive the [onVideoFrameReceived(frame:)](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/VideoSink.swift#L20), update to render actual frames.

**Comment by zhinang-amazon** [comment]
Closing this issue. Feel free to reopen if you still have question around this.
