### ISSUE TITLE
Supporting/future proofing against more then 16 video tiles being streamed

### ISSUE THREAD

**Issue by jatindervrify** [aws/amazon-chime-sdk-ios#243]
**Describe the bug**
We know that the current limit on video tiles is 16 but had a few questions surrounding the behaviour near the 16 person limit. 

1.  When additional attendees turn on remote video after 16 video tiles are already filled what is the expected behaviour within the SDK? Currently it appears as though video will automatically be stopped for another user in order to allow the new user to send frames. If that's the case how does Chime determine which users video tile will be paused? Is it FIFO? Last audible user? Any insight would be great. 

2. Piggybacking off of [this amazon-chime-sdk-js issue](https://github.com/aws/amazon-chime-sdk-js/issues/885) we were similarly wondering what the guidance is for working around the 16 video tile limit? Should we pursue using a mechanism similar to [this AWS sample](https://github.com/aws-samples/amazon-chime-sdk-smart-video-sending-demo) provided for the js sdk? It essentially recommends web sockets be used to start/stop remote video streams dynamically. This seems problematic to me from a few different perspectives tbh.  

3. Does a users local video tile count against the 16 video tile limit? 

4. Are you aware of any future plans for the limit or supporting a mechanism like the workaround in (2) to allow for selective streams of video tiles within the sdk itself?

To be clear - we aren't trying to display 16+ tiles on screen. We hope to support 16+ users being able to "stream" video on the fly and 🤞 the sdk will help support that in the future vs. having to roll our own solution. 

**To Reproduce**
N/A

**Expected behavior**
Ideally we'd prefer a means within the SDK to manage the currently streaming video tile limit vs. having to roll our own workaround using websocket messaging/having to cap users within our app when the 16 person limit is hit. 

**Logs**
N/A

**Screenshots**
N/A

**Test environment Info (please complete the following information):**
 - Device: [iPhone 12 Pro/4th Gen iPad Pro]
 - OS: [iOS 13.4/14.3]
 - Version AmazonChimeSDK: [e.g. 0.15.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.15.0]

**Additional context**
N/A

**Comment by hokyungh** [comment]
Thank you for detailed description. Here are answers to your questions. I'll update more if I have more information.

1. The behavior of SDK should be that you will receive callback [videoSessionDidStartWithStatus](https://aws.github.io/amazon-chime-sdk-ios/Protocols/AudioVideoObserver.html#/c:@M@AmazonChimeSDK@objc(pl)AudioVideoObserver(im)videoSessionDidStartWithStatusWithSessionStatus:) with status of [videoAtCapacityViewOnly](https://aws.github.io/amazon-chime-sdk-ios/Enums/MeetingSessionStatusCode.html#/c:@M@AmazonChimeSDK@E@MeetingSessionStatusCode@MeetingSessionStatusCodeVideoAtCapacityViewOnly). You can also see it in the demo app [videoSessionDidStartWithStatus](https://github.com/aws/amazon-chime-sdk-ios/blob/481ffec49f8dec67164f99e8966d3b71f5d0df75/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModel.swift#L406). 
2. Unfortunately, [smart-video-sending](https://aws.amazon.com/blogs/business-productivity/amazon-chime-sdk-smart-video-sending-demo/) is current workaround to bypass 16 video tiles limit
3. Yes. 
4. This seems like a few feature request. Do you mind filling out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "“Tell us about your project:”. You can put the link of this GitHub issue there.

Thank you. Let us know if you have any questions.

**Comment by jatindervrify** [comment]
Thanks for the speedy response @hokyungh, this helps a lot. Cheers.

**Comment by piv199** [comment]
@hokyungh Are there any readme of the way observers react to exceeding this quota?

When we joined session with more than 16 videos, we will receive `videoAtCapacityViewOnly` in `videoSessionDidStartWithStatus`, but what if we joined session normally and then lots of people with video connected during the meeting. What will be the bahavior of `VideoTileObserver` after exceeding the limit?

**Comment by zhinang-amazon** [comment]
Hi @piv199, our client side will not allow enabling the 17th video currently. This limit is also gated on our server side, so you would not run into this issue.

I will resolve this issue since @hokyungh answered all the original questions.
Feel free to reopen if you have more questions on this
