### ISSUE TITLE
Add an observer to get notified when a session has ended.

### ISSUE THREAD

**Issue by piv199** [aws/amazon-chime-sdk-ios#244]
**Is your feature request related to a problem? Please describe.**
Can't understand that the meeting finished successfully when Web team can.
When meeting ends, BE deletes it from chime.
In iOS SDK we receive videoSessionDidStop(ok) +audioSessionDidStop(audioServerHungup)
But web team receives MeetingEnded (code 6)
Refer: https://aws.github.io/amazon-chime-sdk-js/index.html#stopping-a-session  use case 28

**Describe the solution you'd like**
```
/*
        - You (or someone else) have called the DeleteMeeting API action in your server application.
        - You attempted to join a deleted meeting.
        - No audio connections are present in the meeting for more than five minutes.
        - Fewer than two audio connections are present in the meeting for more than 30 minutes.
        - Screen share viewer connections are inactive for more than 30 minutes.
        - The meeting time exceeds 24 hours.
        See https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html for details.
*/
```
sessionStatusCode == MeetingSessionStatusCode.meetingEnded

**Describe alternatives you've considered**
Websocket communications on our side.

**Additional context**

**Comment by zhinang-amazon** [comment]
Hi @piv199,
Chime SDK for iOS and Android have a different implementation comparing to JS, and have an extra AmazonChimeSDKMedia layer so JS SDK APIs do not translate directly to iOS and Android SDK. 
In this case, `audioSessionDidStop(audioServerHungup)` is called to reflect meeting ended from other parties.
Is this not working as expected for you?

**Comment by hokyungh** [comment]
We have similar issue open. Let me refer this here and close this ticket https://github.com/aws/amazon-chime-sdk-ios/issues/82.
