### ISSUE TITLE
Sometimes meetingSession becomes stale (may be observers) on first call when app starts but subsequent calls connect. iOS/Android

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#245]
Sometimes meetingSession becomes stale (may be observers) on the first call when app starts but subsequent calls connect. iOS/Android. 

It will observe itself in DidJoin as the only attendee and won't activate voice or show others on the same session. And others won't see it as well.

spent the whole day to no avail, but I have made the following changes but will try to observe again if it re-occurs

private func startAudioVideoConnection(isCallKitEnabled: Bool) {
        do {
      //setupAudioVideoFacadeObservers() //<- I Commented this to let the call start b4 observing changes may be it will work this way am not sure.
            try currentMeetingSession.audioVideo.start(callKitEnabled: isCallKitEnabled) 
           **setupAudioVideoFacadeObservers()** //<-------- 
            try currentMeetingSession.audioVideo.start(callKitEnabled: isCallKitEnabled) 
        } catch {
            logger.error(msg: "Error starting the Meeting: \(error.localizedDescription)")
            endMeeting()
        }
    }

**Comment by hokyungh** [comment]
@adesun2k Hi I am trying to better understand the problem. Do you mind providing answers to the followings:

1. Are you reusing `DefaultMeetingSession` to join meeting or is `DefaultMeetingSession` recreated every time?
2. Is subsequent call happening after ending each meeting? 
3. Is subsequent call same meeting or different meeting?
4. Is behavior not getting any callback for observers or unable to join the meeting the others are in?
5. Were you able to reproduce similar with our demo application?

Do you also mind providing

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logs**
If applicable, add logs from console to help explain your problem.

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]

**Comment by adesun2k** [comment]
Q: Are you reusing DefaultMeetingSession to join meeting or is DefaultMeetingSession recreated every time?
A: Am recreating DefaultMeetingSession everytime. This issue happens only when app is first started. Like removing app  from recent.

Q: Is subsequent call happening after ending each meeting?
A: Subsequent call happens after each meeting!

Q: Is subsequent call same meeting or different meeting?
A: Susequent is different meeting. Works fine for subsequent calls but for the very first call when app is newly open it happens sometimes though not always.
 
Q: Is behavior not getting any callback for observers or unable to join the meeting the others are in?
A: it only gets itself as the only attendee and nothing else. It will observe itself in DidJoin as the only attendee and won't activate voice or show others on the same session. And others won't see it as well.

Q: Were you able to reproduce similar with our demo application? 
A: Yes copied everything from the demo to my app just that I wont need to fill any form as in the case of the demo app. My app is a glorified demo app. Users call each other and I generate different meeting for  each call.

Q: Device
A: iPhone 7
Q: OS
A: iOS 14.4
Version AmazonChimeSDK: I extracted the bundle deleted the rest its the one before this last update.
Version AmazonChimeSDKMedia: I extracted the bundle deleted the rest its the one before this last update.

**Comment by adesun2k** [comment]
and most times i see this from the log

**_2021-02-24 23:20:33.860465+0100 Kwayet[6156:2121373] [ERROR] RosterModel - Cannot find attendee with attendee id 2501d08c-d506-b87f-8294-552980b9adc2_**

**Comment by hokyungh** [comment]
@adesun2k Thank you for clarification. Do you use callkit by any chance? Trying to see if you are using callkit and maybe in the first time it is not initialized properly.

**Comment by adesun2k** [comment]
Haa Okay. Thanks

**Comment by adesun2k** [comment]
**_self.startAudioVideoConnection(isCallKitEnabled: false) This is what works perfectly after 48 hours._**

self.startAudioVideoConnection(isCallKitEnabled: true) This is very very unstable and unpredictable. It stales observers.

And now am experience the same issue on Android even with the new SDKs you released yesterday...

**Comment by adesun2k** [comment]
Thanks Nick

Final solution since this happens randomly on android and iOS was to remove observers, stop signals and Re-connect to the meeting after a seemingly staled connection. And Now my App works perfectly just like WhatsApp. Thanks 

`self.amRejoiningDoNotEnd = true
        self.globalSettings.meetingModel?.currentMeetingSession.audioVideo.stopLocalVideo()
        self.globalSettings.meetingModel?.currentMeetingSession.audioVideo.stopRemoteVideo()
        self.globalSettings.meetingModel?.currentMeetingSession.audioVideo.stop()
        self.globalSettings.meetingModel?.videoModel.customSource.stop()
        self.globalSettings.meetingModel?.videoModel.customSource.torchEnabled = false
            _ = self.globalSettings.meetingModel?.removeAudioVideoFacadeObservers
        if MeetingModule.shared().activeMeeting != nil {
            MeetingModule.shared().prepareMeeting(meetingId: AppController.globalSettings.callId, selfName: AppController.globalSettings.kallerName, option: .neutral) { success in
           // DispatchQueue.main.async {
             if !success {
                let stringi = NSLocalizedString("norecooe", comment: "")
                self.globalSettings.kallStatus = stringi
                 Toast.toastMessage(stringi,35)
                print("TWAtchr6")
                //self.amRejoiningDoNotEnd = false
                AppController.stopTimer()
                 }else{
                   /// self.amRejoiningDoNotEnd = false
                 }
                self.amRejoiningDoNotEnd = false
                
            }
        }else{
            print("TWAtchr")
            self.amRejoiningDoNotEnd = false
            AppController.stopTimer()
            
        }`

**Comment by dylonChime** [comment]
I'm glad you got it working. I'll close this for now, but feel free to reopen if run into this issue again.
