### ISSUE TITLE
Errors when running demo

### ISSUE THREAD

**Issue by adambyer** [aws/amazon-chime-sdk-ios#253]
I am trying to run the demo following the steps here... 
https://github.com/aws/amazon-chime-sdk-ios#running-the-demo-app

I have the serverless demo running.

When I try to run in the iPhone 12 simulator I get the following error...
```
Details

The request to open "com.amazonaws.services.chime.SDKDemo" failed.
Domain: FBSOpenApplicationServiceErrorDomain
Code: 5
Failure Reason: Unexpected error type.
User Info: {
    BSErrorCodeDescription = InvalidResponse;
}
--
The operation couldn’t be completed. (BSServiceConnectionErrorDomain error 3.)
Domain: BSServiceConnectionErrorDomain
Code: 3
User Info: {
    BSErrorCodeDescription = OperationFailed;
}
--


System Information

macOS Version 10.15.7 (Build 19H524)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-02-26T21:32:53-05:00
```

When I try to to run in the iPhone 11 simulator I get this error...

```
Details

The operation couldn’t be completed. (Mach error -308 - (ipc/mig) server died)
Domain: NSMachErrorDomain
Code: -308
--


System Information

macOS Version 10.15.7 (Build 19H524)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-02-26T22:02:17-05:00
```

- AmazonChimeSDK-0.16.0
- AmazonChimeSDKMedia-0.11.1

Any idea what I'm doing wrong?

Thanks.

**Comment by hokyungh** [comment]
When you run serverless demo, you should've got the url. When you open the url from browser, are you able to open it and run it?

**Comment by hokyungh** [comment]
Closing as no response. Feel free to reopen if you still have issue.
