### ISSUE TITLE
iOS SDK not compatible with ObjC anymore?

### ISSUE THREAD

**Issue by revox-gh** [aws/amazon-chime-sdk-ios#254]
**Describe the bug**
Since updating to the latest verion (v0.16.0), we receive errors when compiling our app:
```
@interface MeetingObservers : NSObject <RealtimeObserver, VideoTileObserver, AudioVideoObserver>

MeetingObservers.h:49:55: error: expected a type
- (id)initWithBridge:(MyBridge *) bridge logger:(ConsoleLogger * )logger;
```

**To Reproduce**
1. Include the .xcframework in an ObjC project
2. Import the Chime SDK
3. Declare the above class
4. Build the app

**Expected behavior**
The build succeeds.

**Test environment Info (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.5
 - Version AmazonChimeSDK: 0.16.0
 - Version AmazonChimeSDKMedia: 0.11.1

**Comment by revox-gh** [comment]
Update: It seems like this is only an issue with the .xcframework binaries. The classic .framework binaries work fine!

**Comment by hokyungh** [comment]
@revox-gh I wasn't able to reproduce the same issue. Will you be able to clean project and [update project file](https://github.com/aws/amazon-chime-sdk-ios#2-update-project-file) and rebuild to see if you can build it?

**Comment by hokyungh** [comment]
Closing as we have not get response. Feel free to reopen it if you still have issue.
