### ISSUE TITLE
[ERROR] MeetingModel - Error starting the Meeting: The operation couldn’t be completed. (AmazonChimeSDK.MediaError error 1.)

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#257]
2021-03-02 05:19:49.089287+0100 myApp[2411:805411] [ERROR] MeetingModel - Error starting the Meeting: The operation couldn’t be completed. (AmazonChimeSDK.MediaError error 1.)

2021-03-02 05:19:39.915116+0100 myApp[2411:805411] [ERROR] MeetingModule - Error configuring AVAudioSession: The operation couldn’t be completed. (OSStatus error 1701737535.)

Whenever Phone is locked and App is started from the background and a call comes in (Incoming CallKit Call) for the first time I always get this error, but subsequent incoming call won't give this error. Again if i killed the app and locked the screen and I call again, I will get this error but subsequent call will go through.

` private func startAudioVideoConnection(isCallKitEnabled: Bool) {
        do {
            setupAudioVideoFacadeObservers()
            try currentMeetingSession.audioVideo.start(callKitEnabled: isCallKitEnabled) //<---- Giving error on 1st try when app is waken up from suspended state.
        } catch {
            logger.error(msg: "Error starting the Meeting: \(error.localizedDescription)")
            endMeeting()
        }
    }`

**Comment by adesun2k** [comment]
or please what am I to do to ensure the MediaSDK is properly setup before starting the call? Just thinking
**or how can I ensure the MediaSDK is properly setup before starting the call i.e before calling audioVideo.start()**

My app has to be inherently stable. Thanks

**Comment by adesun2k** [comment]
Fixed:: Need to setup Audio Before reporting call. Thanks

**Comment by hokyungh** [comment]
@adesun2k Do you mind sharing the solution or the problem? We would like to know if we need to update documentation or code to handle some cases better.

**Comment by adesun2k** [comment]
Sure!!!
In the `**MeetingModule.swift**` in the demo example just configure audio session before starting CallKit i.e
```
 **self.configureAudioSession() //<--- Add this to configure Audio before starting callKit
 CallKitManager.shared().reportNewIncomingCall(with: call)**
```
