### ISSUE TITLE
EXC_BAD_ACCESS in AmazonChimeMediaSDK

### ISSUE THREAD

**Issue by jpmunoz9** [aws/amazon-chime-sdk-ios#258]
We are seeing this event in our error monitoring tool. At the moment we are not able to reproduce it manually. We realize this is hard to debug and fix, but we wanted to open it to see if you are aware of this. I can provide you with more information if you need it.

[Crash report.rtf.zip](https://github.com/aws/amazon-chime-sdk-ios/files/6070773/Crash.report.rtf.zip)

**Comment by dylonChime** [comment]
Can you please provide the following information?

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Version AmazonChimeSDK: [e.g. 0.4.0]
Version AmazonChimeSDKMedia: [e.g. 0.4.0]

**Comment by jpmunoz9** [comment]
Absolutely,

Device: iPhone XR
OS: 14.3
AmazonChimeSDK: 0.11.0
AmazonChimeSDKMedia: 0.7.0

**Comment by jpmunoz9** [comment]
We now have a similar crash that occurs with a more recent SDK version, should I provide the stack for this newer one to focus on this new one instead, since this one is from an old SDK release?

**Comment by zhinang-amazon** [comment]
Yes please send us the stack trace on newer SDK version along with which AmazonChimeSDK and AmazonChimeSDKMedia version

**Comment by zhinang-amazon** [comment]
@jpmunoz9 And please send us the complete stack trace, the one with a “Binary Images” section in the end so that we can symbolicate on our end.

**Comment by hokyungh** [comment]
Hi @jpmunoz9 . Do you know when it usually happens or is it still not reproducible? This seems to be summary of crash report. Is there way you can get us either crash report that is in `.ips` or `.crash`?

**Comment by jpmunoz9** [comment]
No, so far we cannot reproduce this. And the info I provided is what we get from bugsnag. Let me see if I can get the .crash file but I dont believe we can get it.

**Comment by alnlau** [comment]
Feel free to re-open if this is still an issue for you.
