### ISSUE TITLE
API exposed differs between Amazon Chime JS SDK and Amazon Chime React Components, making the later incompatible as it is with Amazon Chime iOS SDK.

### ISSUE THREAD

**Issue by ElielCohen** [aws/amazon-chime-sdk-ios#264]
Hi,

The API exposed by Chime SDK Javascript Sample app, and the one exposed by the Chime SDK React Component Sample App differs. This cause an issue with the native SDK implementation, that is built to support only the pure JavaScript API implementation.

Here is an example of the two different API response we get, when trying to create a session :

JavaScript API :

"{\n  \"JoinInfo\": {\n    \"Meeting\": {\n      \"Meeting\": {\n        \"MeetingId\": \"c70f45c2-b6e0-4fbb-bd7b-e93c1c87bca4\",\n        \"ExternalMeetingId\": \"tout\",\n        \"MediaPlacement\": {\n          \"AudioHostUrl\": \"28cb8b008aa2069574f5e3e413b9f33a.k.m3.ue1.app.chime.aws:3478\",\n          \"AudioFallbackUrl\": \"wss://haxrp.m3.ue1.app.chime.aws:443/calls/c70f45c2-b6e0-4fbb-bd7b-e93c1c87bca4\",\n          \"ScreenDataUrl\": \"wss://bitpw.m3.ue1.app.chime.aws:443/v2/screen/c70f45c2-b6e0-4fbb-bd7b-e93c1c87bca4\",\n          \"ScreenSharingUrl\": \"wss://bitpw.m3.ue1.app.chime.aws:443/v2/screen/c70f45c2-b6e0-4fbb-bd7b-e93c1c87bca4\",\n          \"ScreenViewingUrl\": \"wss://bitpw.m3.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=c70f45c2-b6e0-4fbb-bd7b-e93c1c87bca4\",\n          \"SignalingUrl\": \"wss://signal.m3.ue1.app.chime.aws/control/c70f45c2-b6e0-4fbb-bd7b-e93c1c87bca4\",\n          \"TurnControlUrl\": \"https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions\ "\n        },\n        \"MediaRegion\": \"us-east-1\"\n      }\n    },\n    \"Attendee\": {\n      \"Attendee\": {\n        \"ExternalUserId\": \"0aa9cba2#eliel\",\n        \"AttendeeId\": \"5f6616c1-0e14-2622-ee40-cbde4637daca\",\n        \"JoinToken\": \"NWY2NjE2YzEtMGUxNC0yNjIyLWVlNDAtY2JkZTQ2MzdkYWNhOjEyNGY4NjE3LTk3ZGYtNGExYi1hODdkLTUyNTUzN2Q1NTQzOQ\"\n      }\n    }\n  }\n}"

React JS API :

"{\n  \"JoinInfo\": {\n    \"Title\": \"tout\",\n    \"Meeting\": {
\n      \"MeetingId\": \"71eedca6-b686-4a25-b73c-06677cf5ac68\",\n      \"ExternalMeetingId\": null,\n      \"MediaPlacement\": {
\n        \"AudioHostUrl\": \"469fd3c53b044551899746909e413187.k.m3.ue1.app.chime.aws:3478\",\n        \"AudioFallbackUrl\": \"wss://haxrp.m3.ue1.app.chime.aws:443/calls/71eedca6-b686-4a25-b73c-06677cf5ac68\",\n        \"ScreenDataUrl\": \"wss://bitpw.m3.ue1.app.chime.aws:443/v2/screen/71eedca6-b686-4a25-b73c-06677cf5ac68\",\n        \"ScreenSharingUrl\": \"wss://bitpw.m3.ue1.app.chime.aws:443/v2/screen/71eedca6-b686-4a25-b73c-06677cf5ac68\",\n        \"ScreenViewingUrl\": \"wss://bitpw.m3.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=71eedca6-b686-4a25-b73c-06677cf5ac68\",\n        \"SignalingUrl\": \"wss://signal.m3.ue1.app.chime.aws/control/71eedca6-b686-4a25-b73c-06677cf5ac68\",\n        \"TurnControlUrl\": \"https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions\ "\n      
},\n      \"MediaRegion\": \"us-east-1\"\n    },\n    \"Attendee\": {\n      \"ExternalUserId\": \"6a9e438b-61b3-429d-9346-be17276b9e31\",\n      \"AttendeeId\": \"a00315d5-f685-3145-c80a-bb66520a2dd0\",\n      \"JoinToken\": \"YTAwMzE1ZDUtZjY4NS0zMTQ1LWM4MGEtYmI2NjUyMGEyZGQwOmRjZjE0ZDM4LTMwMGYtNDMwZS1iYTQ1LTkyMmQ4NWNhMjVjMw\"\n    }\n  }\n}"

In order to support the later, I had to change the file JoinMeetingResponse.swift, so that the structure we use is compatible with the different API response. Without that change, an iOS native application using the Chime SDK won't be able to connect to the API endpoint served by the React Component JS application.

Of course this is not a long term solution, and I believe we should align both API to be the same.

Thanks,

Eliel Cohen
WebRTC Technological Lead
TytoCare

**Comment by zhinang-amazon** [comment]
Hi @ElielCohen,

I believe your question is answered in the https://github.com/aws/amazon-chime-sdk-js/issues/1146
I will close this one to keep the conversation in one place.
