### ISSUE TITLE
How to decrease interruptions

### ISSUE THREAD

**Issue by jonah-katz** [aws/amazon-chime-sdk-ios#266]
Video tiles frequently freeze (audio is usually smooth). Is it possible to decrease the video quality or something of the sort in an effort to decrease interruptions?

**Comment by zhinang-amazon** [comment]
Hi @jonah-katz,

There are several factors that can impact video quality, such as device network bandwidth, processing capability, video resolution and fps, number of concurrent video streams. 

To reduce video quality at the sending side, you can follow [this guide](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/custom_video.md) and our demo app to choose a lower `VideoCaptureFormat`.

Our SDK pauses video tiles when there is network bandwidth constraints. If you prefer to selectively display video tiles and pause others, take a look at [this guide](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/video_pagination.md)

If you are looking for a uplink/downlink policy similar to our JS SDK, feel free to +1 on this feature request #137 

Let us know if you need more information.

**Comment by jonah-katz** [comment]
@zhinang-amazon Perfect! I want my app to never freeze tiles, would prefer extremely low quality video over freezing. Thinking if the app detects a freeze or low quality, we can reinstantiate a custom VideoCaptureFormat with a lower framerate.

**Comment by jonah-katz** [comment]
> Our SDK pauses video tiles when there is network bandwidth constraints.

Does the sdk try lowering the framerate before pausing the tiles?

**Comment by jonah-katz** [comment]
@zhinang-amazon Oh and one more, is there a way for the receiver to specify lower quality when being received? That way only the bad-internet users need to have worser quality.
