### ISSUE TITLE
Demo iOS app crashing on tapping end meeting button

### ISSUE THREAD

**Issue by Swapnil-Gunla** [aws/amazon-chime-sdk-ios#27]
**Describe the bug**
I have downloaded the Demo iOS chime App. Run it on the iPad Pro real device. Got connected to recipient. When I click on End meeting icon which is located on top right side. App get crashed on line 
**self.currentMeetingSession?.audioVideo.stop()**

**To Reproduce**
1. Launch Demo iOS app
2. Enter meeting ID and Name 
3. Click on Join button. Wait till the Meeting get joined
4. Click on Videos tab. 
5. Turn on Local Video by clicking on Video icon located in top segment bar.
6. Once both local and remote video get loaded, click on End meeting icon located in Top Segment Bar.

**Expected behavior**
It is expected the meeting get ended properly and user get redirected to previous screen.

**Logs**
` *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
(
	0   CoreFoundation                      0x00000001b3776178 9624AAFD-5437-3772-A507-0F357875808D + 1253752
	1   libobjc.A.dylib                     0x00000001b348ac1c objc_exception_throw + 60
	2   CoreFoundation                      0x00000001b3670228 9624AAFD-5437-3772-A507-0F357875808D + 180776
	3   AmazonChimeSDKMedia                 0x00000001010b2478 AmazonChimeSDKMedia + 107640
	4   AmazonChimeSDKMedia                 0x00000001010b2674 AmazonChimeSDKMedia + 108148
	5   libdispatch.dylib                   0x000000010100718c _dispatch_client_callout + 20
	6   libdispatch.dylib                   0x0000000101009ff0 _dispatch_continuation_pop + 576
	7   libdispatch.dylib                   0x000000010101e0e4 _dispatch_source_invoke + 1332
	8   libdispatch.dylib                   0x000000010100e798 _dispatch_lane_serial_drain + 260
	9   libdispatch.dylib                   0x000000010100f580 _dispatch_lane_invoke + 440
	10  libdispatch.dylib                   0x000000010101b0f0 _dispatch_workloop_worker_thread + 1344
	11  libsystem_pthread.dylib             0x00000001b347d714 _pthread_wqthread + 276
	12  libsystem_pthread.dylib             0x00000001b34839c8 start_wqthread + 8
)` 

**Test environment Info (please complete the following information):**
 - Device: iPad Pro
 - OS: 13.4.1
 - Version AmazonChimeSDK: 0.5.0
 - Version AmazonChimeSDKMedia: 0.4.0

**Comment by hokyungh** [comment]
Thank you for reporting issue. We'll try to run on iPad Pro and see if we can reproduce this issue.

**Comment by tianyux-amz** [comment]
Discussed with @Swapnil-Gunla offline. This particular issue is related to the network setup. When user was on VPN the app got crashed when end meeting.

**Comment by tianyux-amz** [comment]
This was related to #43 and was fixed in AmazonChimeSDKMedia v0.4.3.
