### ISSUE TITLE
I'd like better documentation about the size I can expect when using the Bitcode enabled library.

### ISSUE THREAD

**Issue by aarontrank** [aws/amazon-chime-sdk-ios#279]
**Is your feature request related to a problem? Please describe.**
I'd like to understand how inclusion of the bitcode enabled sdk library will impact the size of my app without having to submit it to apple to see.

**Describe the solution you'd like**
I'd like to see some documentation on the expected output size of the bitcode enabled library so that I can predict how much my app will grow by including the library. You could solve either with a generic formula or a set of published values included in release notes for each release.

**Describe alternatives you've considered**
I could submit a new build to apple and look at the ipa size, but I want to predict the size before submitting to apple.  

**Additional context**

**Comment by ziyiz-amzn** [comment]
You may be able to create app size report in xcode. 
https://developer.apple.com/documentation/xcode/reducing_your_app_s_size
