### ISSUE TITLE
Unable to unbind already binded DefaultVideoRenderView against tileId

### ISSUE THREAD

**Issue by arehman86** [aws/amazon-chime-sdk-ios#281]
**Description**
I am showing thumbnail for each attendee in my collection view. When I start a video from the other side, I get a tileId (i.e 2) for the person's video. I bind my render view against the tileId (i.e. 2). Then I start screen sharing from the other side, now I get the tileId (i.e. 3) for screen sharing against that same attendee. When I try to unbind the tileId (i.e. 2)(the person's video tile), I get a callback from the SDK `- (void)videoTileDidAddWithTileState:(VideoTileState *)tileState` which result in binding the same tileId (i.e 2) again

**To Reproduce**
1. Start a meeting
2. Join two attendees, one from the device and second one from the web
3. Start video from web
4. Bind the person video tile to a DefaultVideoRenderView
5. Start screen sharing from web
6. Unbind the person video tileId and bind screen sharing tileId with same DefaultVideoRenderView

**Expected behavior**
It should unbind the person video and bind the screen sharing video tile

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS14.4.2]
 - Version AmazonChimeSDK: [e.g. 0.16.1]
 - Version AmazonChimeSDKMedia: [e.g. 0.11.2]
 - Can you reproduce this in the demo app? Yes

**Comment by alnlau** [comment]
Thanks for reporting this issue. We'll take a look and get back to you.

**Comment by arehman86** [comment]
@alnlau any update on this issue?

**Comment by ziyiz-amzn** [comment]
Hi @arehman86 

I would like to confirm from you what is the current behavior? 

Did you reproduce this behavior in Swift/Obj demo app? or in your own application? If the former, could you specify steps to reproduce?

Also, I would always suggest that you call `pauseRemoteVideoTile(tileId:)` before unbind a video tile. Please let me know if this helps. 

Thanks

**Comment by arehman86** [comment]
@ziyiz-amzn I'll check it out and get back to you

**Comment by arehman86** [comment]
@ziyiz-amzn If we pause the video tile and then unbind it then it works fine. I'll close this issue. Thanks

**Comment by arehman86** [comment]
@ziyiz-amzn There is one more issue. We have a speaker view in which we display thumbnail against each attendee in a horizontal collection view at the bottom and a DefaultVideoRender view as a full screen view which will display the video on the basis of active speaker. If any attendee turn on his video, the video is shown in the thumbnail as well as in a full screen render view. When the user starts screen sharing, I unbind (but not pause because the video is shown in the thumbnail will also get pause) the user video tile from the full screen render view and bind the screen sharing tile. If multiple user from web starts screen sharing, we show the screen sharing on the basis of active speaker. Now the issue is, if I pause and unbind  one screen sharing tile and then bind the other screen sharing tile. I get a callback from the chime SDK 
`- (void)videoTileDidAddWithTileState:(VideoTileState *)tileState`
which result in adding the screen sharing tile again.

**Comment by ziyiz-amzn** [comment]
Hi @arehman86, 

Please refer to the [detailed `bindVideoView` implementation](https://github.com/aws/amazon-chime-sdk-ios/blob/71dd4a92cabe73b2e98ffa0556d0320c0763eef9/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/DefaultVideoTileController.swift#L87-L106), it contains the logic of `rebind`(I would name it). 
So you can try to call `bindVideoView` with a new view without unbinding the old one.
