### ISSUE TITLE
At what point does AWS timing for charges starts( i.e When will the minutes start reading)

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#285]
I understand this SDK consist of two steps
1. Creating Meeting Resources on the server
2. Then Joining the meeting with the created resources

Now at what point does AWS timing for charges starts (i.e When will the minutes start reading) is it immediately at step 1 or at step 2?

Because I can Create the meeting resources on the server and the first attendee joins after 2-Min and ends the meeting after 5-Min. Will I be charged for 3 Min or 5 Min knowing that the first attendee joins the meeting for only 3-Min?

**Comment by ziyiz-amzn** [comment]
``
Each “attendee” (i.e. an instance of your application that has implemented the SDK) is billed for each minute it is connected to a meeting session regardless of which media modalities (screen share, screen view, two-way audio, one-way audio, two-way video, or one-way video) are used. 
`` - from https://aws.amazon.com/chime/chime-sdk/pricing/

For example, if a meeting lasts for 10 mins, attendee A joins for 5 mins, attendee B joins for 8 mins, total charge will be 13 mins.

Closing the issue, feel free to reopen if more question.

**Comment by adesun2k** [comment]
> `Each “attendee” (i.e. an instance of your application that has implemented the SDK) is billed for each minute it is connected to a meeting session regardless of which media modalities (screen share, screen view, two-way audio, one-way audio, two-way video, or one-way video) are used. ` - from https://aws.amazon.com/chime/chime-sdk/pricing/
> 
> For example, if a meeting lasts for 10 mins, attendee A joins for 5 mins, attendee B joins for 8 mins, total charge will be 13 mins.
> 
> Closing the issue, feel free to reopen if more question.

You have not answered me.

**Comment by ziyiz-amzn** [comment]
Because I can Create the meeting resources on the server and the first attendee joins after 2-Min and ends the meeting after 5-Min. Will I be charged for 3 Min or 5 Min knowing that the first attendee joins the meeting for only 3-Min?

@adesun2k  Charged 3 mins in this case.

**Comment by adesun2k** [comment]
Excellent. Thanks
