### ISSUE TITLE
The Demo App Is Not Working

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#286]
<img width="1278" alt="Screenshot 2021-04-22 at 23 57 01" src="https://user-images.githubusercontent.com/57893099/115794758-782d0300-a3c6-11eb-9369-d94cb5847957.png">
<img width="1280" alt="Screenshot 2021-04-22 at 23 56 15" src="https://user-images.githubusercontent.com/57893099/115794768-7cf1b700-a3c6-11eb-8d10-a73c8e87c5c4.png">

**Comment by adesun2k** [comment]
Is just very frustrating that this demo is so complex one can't even get it to build. Very bad after spending about 2 days.
<img width="1270" alt="Screenshot 2021-04-22 at 23 59 30" src="https://user-images.githubusercontent.com/57893099/115794918-d22dc880-a3c6-11eb-817e-25185ee1f5c3.png">

**Comment by ziyiz-amzn** [comment]
Hi @adesun2k 

The demo app should be built and run with minor friction. But we are glad to help. 

Regards to the build system settings, could you refer to the below? 
![Screen Shot 2021-04-22 at 6 38 20 PM](https://user-images.githubusercontent.com/60948810/115805483-ec04e680-a399-11eb-96a4-f42b3345c782.png)

Regards to `Missing package product toast`, have you tried to reset package caches? 

Could you please provide more detailed information about 
1. what steps you have performed
2. what error you encountered
3. where you were blocked?
