### ISSUE TITLE
xcode11 archive IPA processing failed

### ISSUE THREAD

**Issue by anasna83** [aws/amazon-chime-sdk-ios#29]
I'm trying to export the archive ipa so I can distribute through ad-hoc or testFlight , however I always get this error message  "IPA processing failed". 

I'm using the latest framework file with bitcode enabled. I'm able to run the app normally, it is just the export of ipa.

I have searched for a way to fix this and I found a script that can be added to the "build phases" which fix the issue. here is the script https://stackoverflow.com/a/60494271

I'm not sure what this script do (remove x86_64 archs?). However, after adding this script , I was able to implement and export the ipa file.

My question, is using this script safe or I should do something in this case?
 
 
**Test environment Info (please complete the following information):**
 - Xcode 11.4
- AmazonChimeSDK-0.5.2
 - AmazonChimeSDKMedia-0.4.1-2

**Comment by weichenhamzn** [comment]
Hi, the binary we provided contains both x86_64 and ARM support, so that you will be able to run it on real device and simulator.

To release the app to AppStore, you will need to remove the x86_64 part from the framework

**Comment by anasna83** [comment]
Thank you !

**Comment by Doko-Demo-Doa** [comment]
Just a head up, to remove x86 from framework in build process. Use following script:

Choose target > Build Phases > + > New Run Script Phase

<img width="832" alt="image" src="https://user-images.githubusercontent.com/7723097/86577475-7a8faf00-bfa4-11ea-992a-2a2bbbb98919.png">


Shell: `/bin/sh`

Script:

```sh
if [ "$CONFIGURATION" == "Debug" ]; then
    echo "Skip frameworks cleaning in debug version"
    exit 0
fi

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and
# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```
