### ISSUE TITLE
Crash when starting video

### ISSUE THREAD

**Issue by alexmglover** [aws/amazon-chime-sdk-ios#290]
**Describe the bug**
The app crashes when starting video. 

**Test environment Info (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14.4.2
 - Version AmazonChimeSDK: 0.6.12
 - Version AmazonChimeSDKMedia: 0.11.3
 - Can you reproduce this in the demo app? I haven't tried
If you are reporting a crash:
 - Are you using bitcode supported binaries? No
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.
 https://www.dropbox.com/s/u3itrji4cx1s5l2/03ff63804f5540e9850ccf0bdff23d6f.crash.zip?dl=0

**Comment by zhinang-amazon** [comment]
Hi @alexmglover 
I'm not able to symbolicate the crash with the .crash file you shared because it's missing a few sections before thread back traces.

Example:
```
Incident Identifier: 14FFD847-61CB-435B-9E98-C06B3B661429
CrashReporter Key:   7c5fd78cf04b38cfd2aa153f61eb1655ed671274
Hardware Model:      iPhone4,1
Process:         My iPhone App [2599]
Path:            /var/mobile/Applications/ABAB96ED-A203-48A5-8B50-B34BA3A8E4A4/My iPhone App.app/My iPhone App
Identifier:      My iPhone App
Version:         ??? (???)
Code Type:       ARM (Native)
Parent Process:  launchd [1]

Date/Time:       2012-07-01 22:17:43.458 -0600
OS Version:      iPhone OS 5.1 (9B179)
Report Version:  104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xb4f05bbe
Crashed Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libobjc.A.dylib                 0x35a65f7e objc_msgSend + 22
1   UIKit                           0x33c31042 -[UIImageView isAnimating] + 130
2   UIKit                           
```


Can you provide a .crash file with those information?
Also, I think your AmazonChimeSDK version is 0.16.2, correct?

**Comment by alnlau** [comment]
Feel free to re-open if this is still an issue for you.
