### ISSUE TITLE
URL IS NAKED AND ANYBODY CAN MESS UP WITH IT

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#292]
Hi guys since url is naked anybody can mess up with it.  I want to be sure the request is from me so I added a post parameter 'key' to my request but it is not working please where on the backend am supposed to do this

<img width="1279" alt="Screenshot 2021-05-01 at 12 15 05" src="https://user-images.githubusercontent.com/57893099/116780837-e5036580-aa76-11eb-8e00-5796ec373d91.png">

**handlers.js**
```
let body = JSON.parse(event.body)
 if (body.key !== "3fG#$5o") {
  return response(400, 'application/json', JSON.stringify({error: 'Need parameters: title, name, region'}));
}
```

**Comment by zhinang-amazon** [comment]
Hi @adesun2k,

I'm not sure if this is related to our Amazon Chime SDK for iOS. Is this regarding the serverless demo that you deployed from [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)?

If that is the case, can you open an issue in that repo instead?
