### ISSUE TITLE
Please How Do I Programmatically End A Broadcast?

### ISSUE THREAD

**Issue by adesun2k** [aws/amazon-chime-sdk-ios#293]
Please How Do I Programmatically End A Broadcast?
After the meeting has ended the broadcast still continues. I want to end a broadcast when meeting ends just like your Android SDK.

**Comment by zhinang-amazon** [comment]
Hi @adesun2k 
You can take a look at our [guide](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/content_share.md#stop-screen-share-1), which talks about stopping broadcast programmatically.

**Comment by zhinang-amazon** [comment]
I will resolve this issue for now. Feel free to reopen if you have further questions
