### ISSUE TITLE
Is this possible to choose the video input bandwidth ?

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-ios#302]
**Is your feature request related to a problem? Please describe.**

With `amazon-chime-sdk-js`, it is possible to choose the video input quality with the method `chooseVideoInputQuality(width, height, frameRate, maxBandwidthKbps)`.

With `amazon-chime-sdk-ios`, I noticed it was possible to choose `width`, `height` and `maxFrameRate` in the [DefaultCameraCaptureSource](https://aws.github.io/amazon-chime-sdk-ios/Classes/DefaultCameraCaptureSource.html) object (thanks to the `format` attribute).

Is there any way to customize `maxBandwidthKbps` somewhere too ?

Thanks you for this amazing library !

**Comment by linsang21** [comment]
Thanks for submitting the feature request! This has been tracked with https://github.com/aws/amazon-chime-sdk-ios/issues/137, we'll update there once have more info. :)
