### ISSUE TITLE
AWS Chime want to schedule a meeting in future

### ISSUE THREAD

**Issue by richa2jan** [aws/amazon-chime-sdk-ios#303]
Why AWS Chime does not provide option to schedule meeting in future? Its only valid 24 hours from meeting creation time. 

There are so many hiccups and issues associated with AWS Chime that no one would be able to use it in a standard application.

1. There are issues with sharing screen in iOS device if you have made a browser based application
2. Even with AWS SDK integrated in iOS app audio of screen being shared is not sent across.
3. Meeting cannot be scheduled for a future date and time.
4. There are hardly any settings available to create meeting and set custom options for availability or expiry. 

With these many issues its getting very difficult to use it in applications.

@zhinang
https://github.com/zhinang-amazon

**Comment by richa2jan** [comment]
The scenario is like this,

Person A (Mr Brian) talks about a product to potential clients. He everyday talks to new customers so plans for the week and schedules meetings with them.  When he schedules a meeting he also sends invitations to them in email (days in advance) with Meeting URL. Like below,
-----------------------------------------------------------------------------------------------------------------------------------------------------
Hello Mr Smith,
Your meeting is scheduled for Wednesday from 10:30 AM - 11:30 AM. Following is the meeting URL,

Join Meeting Here ->  https://meeting.abc.com/meet/cc4f6540-636d-4937-8206-d454346849d1/0/Prof.%20JAMES%20MARTHA%20HILL 

Thanks,
Mr Brian.
-----------------------------------------------------------------------------------------------------------------------------------------------------

The Url given here may be the web application we have developed using AWS Chime for Meetings. The person can click here and join the meeting at the time of the meeting. 

We are right now using Create Meeting API and generating the MeetingID and which we are passing in the URL. This works well for sometime and we end user can check email click on URL and able to join meetings. But it doesn't work after 24 hours. 

Please let us know what we can do to create MeetingId which is for a future meeting.

**Comment by richa2jan** [comment]
@linsang21
@zhinang-amazon

Could you please help me out with this? 

I want to send meeting URL to attendees days in advance. When they click on it they should be able to join the meeting. How can I do that?

**Comment by ziyiz-amzn** [comment]
@richa2jan Thanks for your input. 

The use case is not in the scope of mobile client library. I would suggest either
1. File an [AWS support ticket](https://aws.amazon.com/premiumsupport/knowledge-center/information-support-case/) to get more help from Chime or request new feature to support your use case. 
2. Check with [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js/) js client library for update.
