### ISSUE TITLE
Add support for messaging

### ISSUE THREAD

**Issue by ValYouW** [aws/amazon-chime-sdk-ios#304]
Hi,

Would be nice to have support for [Amazon Chime Messaging](https://docs.aws.amazon.com/chime/latest/dg/using-the-messaging-sdk.html), something like the [JS SDK](https://github.com/aws/amazon-chime-sdk-js#messaging-session) has (or is it already supported and I missed it??)

Thx!

**Comment by alnlau** [comment]
Hello,

We currently do not support this on Android and iOS. I'll leave this issue open as a feature request.

**Comment by ziyiz-amzn** [comment]
Hi @ValYouW The Amazon Chime team has published a blog post[Build chat applications in iOS and Android with Amazon Chime SDK messaging](https://aws.amazon.com/blogs/business-productivity/build-chat-applications-in-ios-and-android-with-amazon-chime-sdk-messaging/) to introduce Amazon Chime SDK messaging in iOS and Android.

**Comment by ziyiz-amzn** [comment]
@ValYouW Please check the blog post which demo the Amazon Chime Messaging SDK in iOS and Android. Closing this for now.
