### ISSUE TITLE
Detect active speakers readme example memory leak.

### ISSUE THREAD

**Issue by JozefLipovsky** [aws/amazon-chime-sdk-ios#305]
**Describe the bug**
Using config provided in the detect [active speakers readme example](https://github.com/aws/amazon-chime-sdk-ios#use-case-10-detect-active-speakers-and-active-scores-of-speakers). Specifically returning `UUID().uuidString`  directly for `ActiveSpeakerObserver` protocol `observerId` computed property can cause a memory leak/strong reference cycle.

```
var observerId: String {
    return UUID().uuidString
}
```

**To Reproduce**

When you use a reference type as addActiveSpeakerObserver i.e. AudioVideoViewModel class:
```
extension AudioVideoViewModel {
    func addSessionObservers() {
        ...
        currentSession?.audioVideo.addActiveSpeakerObserver(policy: DefaultActiveSpeakerPolicy(), observer: self)
    }

    func removeSessionObservers() {
        ...
        currentSession?.audioVideo.removeActiveSpeakerObserver(observer: self)
    }
}
```

And then the same AudioVideoViewModel class conforms to the `ActiveSpeakerObserver` protocol with following config:
```
extension AudioVideoViewModel: ActiveSpeakerObserver {
    var observerId: String {
        UUID().uuidString
    }

    var scoresCallbackIntervalMs: Int {
        1000
    }

    func activeSpeakerDidDetect(attendeeInfo: [AttendeeInfo]) { }

    func activeSpeakerScoreDidChange(scores: [AttendeeInfo: Double]) {
        ...
    }
}
```

`AudioVideoViewModel` is never deallocated even after a chime session is ended and  active speaker observer is removed. I am not 100% sure about this, but assuming that `observerId` is called multiple times and every time a new `UUID().uuidString` is returned maybe a new reference to the same  `AudioVideoViewModel` is stored by SDK?

This could be simply fixed by declaring `let activeSpeakerObserverId = UUID().uuidString` on `AudioVideoViewModel` and then always using this single value in the `ActiveSpeakerObserver` implementation:
```
extension AudioVideoViewModel: ActiveSpeakerObserver {
    var observerId: String {
        activeSpeakerObserverId
    }

    var scoresCallbackIntervalMs: Int {
        1000
    }

    func activeSpeakerDidDetect(attendeeInfo: [AttendeeInfo]) { }

    func activeSpeakerScoreDidChange(scores: [AttendeeInfo: Double]) {
        ...
    }
}
```

**Comment by dylonChime** [comment]
Thank you @JozefLipovsky for your attention to detail. You are absolutely correct. I have opened a PR to update the README example.

**Comment by zhinang-amazon** [comment]
PR has been merged, will resolve this issue.
