### ISSUE TITLE
Call is getting disconnect automatically in background after 30 seconds

### ISSUE THREAD

**Issue by AnandPGautam** [aws/amazon-chime-sdk-ios#308]
Anyone is facing this issue. Please share your suggestions!

**Comment by dylonChime** [comment]
Hi @AnandPGautam, try starting your `DefaultAudioVideoController` with [callkit enabled](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/DefaultAudioVideoController.swift#L44). This will allow the call to continue even while it's in the background.

**Comment by AnandPGautam** [comment]
Thanks for your response @dylonChime !

You mean I have to pass `true` before starting `DefaultAudioVideoController` everywhere in the App like below ?

`try self.start(callKitEnabled: true)`

Please reply!

**Comment by dylonChime** [comment]
Hi @AnandPGautam, sorry for misunderstanding. The entire process of integrating callkit is more involved. You can reference our demo app and [this blog post](https://aws.amazon.com/blogs/business-productivity/how-to-integrate-apples-callkit-into-ios-applications-using-the-amazon-chime-sdk/) to get started. The reason for the disconnect is our media library cannot access the AVAudioSession and microphone while in the background without callkit.

**Comment by AnandPGautam** [comment]
Thank you so much for the writeup!

This works for me :)

**Comment by ziyiz-amzn** [comment]
@AnandPGautam Great to see it works for you. 

To answer **incoming** VoIP calls through VoIP Push Notification, the Customer Application also needs to have [VoIP Push Notification](https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit) integrated, where a certificate may be needed. Outgoing callkit call does not require it.
