### ISSUE TITLE
Building for iOS Simulator, but the linked and embedded framework was build for iOS + iOS Simulator

### ISSUE THREAD

**Issue by zeeshanz** [aws/amazon-chime-sdk-ios#309]
I have started receiving this error after updating my Xcode from 12.2 to 12.5 and MacOS from Catalina to BigSur (11.4).

Please see the attached screenshot.

If I check Validate Workspace back and forth between Yes and No, then the error message turns to warning. But then the app often crashes before the viewcontroller is displayed.

<img width="1440" alt="Screen Shot 2021-06-11 at 6 00 19 AM" src="https://user-images.githubusercontent.com/4508321/121670191-27a75d00-ca7b-11eb-9727-66e2f5eaabc5.png">

@schuettc

**Comment by hokyungh** [comment]
@zeeshanz Do you have same issue with xcframework?

**Comment by zeeshanz** [comment]
@hokyungh No, I don't.

**Comment by ziyiz-amzn** [comment]
You can utilize the .xcframework distributed after v0.15.0

Duplicate: https://github.com/aws/amazon-chime-sdk-ios/issues/129
