### ISSUE TITLE
White screen instead of video on some wifi connections

### ISSUE THREAD

**Issue by TomasPecuch** [aws/amazon-chime-sdk-ios#310]
**Describe the bug**
When we connect to the call on iOS device (connected to wifi) the video of other participants constantly freezes, sometime we see only white screen instead of the video. This happens mostly on group calls (3+ participants where we switch video tiles according to current active speaker).

**Expected behavior**
The video might be laggy, but we expect no white screen instead of user's video.

**Test environment Info (please complete the following information):**
 - Device: iPhone Xs
 - OS: iOS 14.4.2
 - Version AmazonChimeSDK: 0.16.2
 - Version AmazonChimeSDKMedia: 0.11.3
 - Can you reproduce this in the demo app? No, but the video is laggy there as well.

**Additional context**
We've also tried other call providers, the video works fine and it's not even laggy. When we try to make a group call on mobile data, it's working fine. Wifi stats: 20 ping, download 28 Mbps, upload 8 Mbps.

**Comment by zhinang-amazon** [comment]
Hi @TomasPecuch,

Apologies for your experience. Can you send us some debug logs when you see this issue? You can reference our demo app that leverages the `ConsoleLogger`. To enable debug level logging, you can initialize the logger by `ConsoleLogger(name: "logger", level: LogLevel.DEBUG)`

**Comment by alnlau** [comment]
Feel free to re-open if this is still an issue for you.
