### ISSUE TITLE
Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by zeeshanz** [aws/amazon-chime-sdk-ios#315]
<img width="326" alt="Screen Shot 2021-06-22 at 4 54 39 PM" src="https://user-images.githubusercontent.com/4508321/122998108-a30de600-d37a-11eb-8923-5adf4f43c88d.png">

<img width="908" alt="Screen Shot 2021-06-23 at 8 02 57 AM" src="https://user-images.githubusercontent.com/4508321/123093781-13a81780-d3fa-11eb-8182-fa81980c7cc7.png">

After spending days to try to make the demo app work, which finally worked, now integrating the SDK in my actual app is totally failing.

Using AmazonChimeSDKMedia-0.11.3 and AmazonChimeSDK-0.16.2 and the issue is with AmazonChimeSDKMedia.

Using Xcode 12.5 and bigSur 11.4.

/Users/zeeshan/Library/Developer/Xcode/DerivedData/my_app_name-azwjzitglwbkcyhayibclslxjxhr/Build/Products/Debug-iphoneos/mobile-border-ios-cleanup.app/Frameworks/AmazonChimeSDKMedia.framework: bundle format unrecognized, invalid, or unsuitable

On using the ...SDK.xcframework files, I get a different error:

"Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's." Now how do I do it? We have a developer profile provided for our team and we cannot change it.

I have tried everything I could find on Stackoverflow.

**Comment by hokyungh** [comment]
Sorry for your experience. Do you mind sharing
![Screen Shot 2021-06-22 at 8 58 16 PM](https://user-images.githubusercontent.com/57926812/123033437-9dc19300-d39c-11eb-8869-a0916cdbaefa.png)

and check if you still have reference to AmazonChimeSDK?
![Screen Shot 2021-06-22 at 8 40 31 PM](https://user-images.githubusercontent.com/57926812/123032029-2428a580-d39a-11eb-9c30-e7328619955f.png)

If you are using our demo app to remove reference to SDK project, then, you might want to do

1. Remove AmazonChimeSDK.xcodeproj by right click -> Delete -> Move to Trash. Make sure you have no reference to AmazonChimeSDK.xcodeproj in Xcode
2. If you see the first screen shot, it will need reference to AmazonChimeSDK. Click + on `Frameworks, Libraries, and Embedded Content` and click `Add Other`. You should reference the Downloaded SDK file (xcframework).
3.  If you moved location of MediaSDK, then you should remove that framework from screenshot 1 and add same following same procedure as 2.
4. Sometimes, it might be that location is in absurd places and Xcode might not be able to find frameworks. Make sure framework search path is updated to where your framework is located. It is in Build Settings -> Framework Search Paths
![Screen Shot 2021-06-22 at 9 06 28 PM](https://user-images.githubusercontent.com/57926812/123034195-ec236180-d39d-11eb-8a8b-3a3ab3767c10.png)
5. Try Product -> Clean Build Folder to make sure previous built artifact doesn't affect our build.
6. Build the app again and see if it has issue.

Let me know if you encounter any issue during the step.

**Comment by zeeshanz** [comment]
I have everything like you showed above. Demo app works fine, though demo app had its own issues which I mentioned in a separate Issue thread.

The issue here is with signing certificates. Please see the attached screenshot.

If I use **AmazonChimeSDKMedia.framework** and **AmazonChimeSDK.framework**, then Xcode wants me to enable **Automatically manage sign** for all the targets. If I have my own provisioning profile, and that provisioning profile doesn't include all the targets, then I get the above mentioned codeSign error.

If I use **AmazonChimeSDKMedia.xcframework** and **AmazonChimeSDK.xcframework** instead, then it seems to not care about provisioning profile and I don't get codeSign error and the app compiles and runs fine.

This should be mentioned somewhere in the Readme file. The instructions provided with the demo are not adequate, and the demo code also needs some cleaning up. Setting up Chime is pretty confusing.

<img width="1080" alt="Screen Shot 2021-06-23 at 5 55 43 AM" src="https://user-images.githubusercontent.com/4508321/123078499-09c9e880-d3e9-11eb-9941-bf40cc20e4f7.png">

<img width="554" alt="Screen Shot 2021-06-23 at 5 53 51 AM" src="https://user-images.githubusercontent.com/4508321/123078874-675e3500-d3e9-11eb-9b10-ce6100b03901.png">

**Comment by hokyungh** [comment]
@zeeshanz sorry for all the trouble. We will update documentation to use xcframework.

**Comment by alnlau** [comment]
Hello,

We've updated our README to include information about xcframework.
