### ISSUE TITLE
Function turn on/off speaker

### ISSUE THREAD

**Issue by DuyIoT** [aws/amazon-chime-sdk-ios#317]
I'm using the AWS Chime SDK to do audio calling(not using video call).
I found the function to turn the microphone turn on/off(currentMeetingSession.audioVideo.realtimeLocalMute(), ..unMute()), does the SDK provide any function to mute the speaker?
Example: js has a bindAudioElement and unBind function.

**Comment by hokyungh** [comment]
Thank you for reporting. This is currently not supported. We'll track update in https://github.com/aws/amazon-chime-sdk-ios/issues/250

**Comment by DuyIoT** [comment]
@hokyungh Thank you so much.

**Comment by DuyIoT** [comment]
@hokyungh Thank you so much.
