### ISSUE TITLE
Audio not defaulting to Speaker

### ISSUE THREAD

**Issue by jonah-katz** [aws/amazon-chime-sdk-ios#318]
I expect audio to default to speaker, but sometimes, it doesn't (default to the quiet audio output used for phone calls). If user brings up output selection modal and chooses speaker, then it works.

Additional info: Ive realized its only on a fresh install. If I quit and reopen, it works (ie. speaker) consistently. Have confirmed I only initiate video chat after permission for mic/video have been granted.

Relevant code, which I call various times (audioSessionDidStart, audioDeviceDidChange, etc)

```  
 private func autoselectDevices() {
        let session = self.activeMeetingSession!
        let devices = session.audioVideo.listAudioDevices()

 if let speakerDevice = devices.first(where: { $0.type == MediaDeviceType.audioBuiltInSpeaker || $0.label.lowercased().contains("speaker")}) {
        session.audioVideo.chooseAudioDevice(mediaDevice: speakerDevice)

        setSpeaker()
      } else {
        setSpeaker()
      }
    }
    
    func setSpeaker() {
        do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playAndRecord, options: .defaultToSpeaker)
            try AVAudioSession.sharedInstance().overrideOutputAudioPort(AVAudioSession.PortOverride.speaker)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            print("error.")
        }
    }
```
 Device: Various iPhones / OS's

**Comment by jonah-katz** [comment]
Any tips? Kind of exhausted all options here

**Comment by hokyungh** [comment]
Could you swap the order? `setSpeaker()` first and then `chooseAudioDevice`.

**Comment by jonah-katz** [comment]
@hokyungh Thank you for the response. Same result. Additional info: Ive realized its only on a fresh install. If I quit and reopen, it works (ie. speaker) consistently.

**Comment by jonah-katz** [comment]
@hokyungh It seems like for a second audio does come out of speaker, but then its back to earpiece. Is there code in the chime sdk that sets the preferred output?

**Comment by hokyungh** [comment]
I think we do it [here](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/device/DefaultDeviceController.swift#L57), but I don't think we have extra code to set it else where. However, we do set mode to voice chat. Could you see if [code](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModule.swift#L188), actually solves your issue?

**Comment by jonah-katz** [comment]
@hokyungh OK I got it to work (not with that code), but not sure why. This did it. Seems after I set .defaultToSpeaker, some other code elsewhere was undoing it. So I simply set it again. Closing ticket!
<img width="770" alt="image" src="https://user-images.githubusercontent.com/3124024/124822645-295f2600-df3e-11eb-9a4a-d8eff6b4b979.png">

**Comment by jonah-katz** [comment]
Though this could be a problem if the user intentionally routes it. Maybe I'll only do this once.
