### ISSUE TITLE
Unable to join same meeting again and again - Received status code 502

### ISSUE THREAD

**Issue by pankaj-rana01** [aws/amazon-chime-sdk-ios#323]
The first time it is working fine and when I am trying to rejoin the same meeting again then, 
JoiningRequestService - Received status code 502. 
So that I am unable to join again the same meeting with the same meeting id and name.

Calling this function when hitting the join button... 
MeetingModule.shared().prepareMeeting(meetingId:"123",
                                              selfName:"pankaj rana",
                                              option: .disabled,
                                              overriddenEndpoint: debugSettingsModel.endpointUrl) { success in                                         
                                              
While Fetching response, it is showing  me a toast message... 
if !success {
                    self.hostViewController.view.hideToast()
                    self.hostViewController.view.makeToast("Unable to join Appointment please try different Appointment ID",
                                        duration: self.toastDisplayDuration, position: CSToastPositionTop)
}

}

So Please let me know what is the issue here and how to solve this. 
Thanks in Advance.

**Comment by alnlau** [comment]
Hello,

Could you provide the following information?
* Device: 
* OS: 
* Version AmazonChimeSDK: 
* Version AmazonChimeSDKMedia: 
* Can you reproduce this in the demo app?

I'd also like clarification for the following:
* What happens to the meeting when you leave it for the first time? Did the host end the meeting for all? 
* When you leave the meeting, is there anyone left in the meeting?
* When you try to rejoin the meeting, is it immediately after leaving the meeting? If not, how long before rejoining?

**Comment by pankaj-rana01** [comment]
Hi, 

Please find the following information:

**Device**: iPhone7, 7+ and iPhone 11

**OS**: 14.5

**Version AmazonChimeSDK**:  AmazonChimeSDK-0.16.3

**Version AmazonChimeSDKMedia**: AmazonChimeSDKMedia-0.11.4

**Can you reproduce this in the demo app?** 
Comment: No, I am able to run your demo app, It shows many errors while run.

**I'd also like clarification for the following:**  
Comment: The first time it is working fine and when I am trying to rejoin the same meeting again then,
JoiningRequestService - Received status code 502.
So that I am unable to join again the same meeting with the same meeting id and name.

**Calling this function when hitting the join button...**
MeetingModule.shared().prepareMeeting(meetingId:"123",
selfName:"pankaj rana",
option: .disabled,
overriddenEndpoint: debugSettingsModel.endpointUrl) { success in

**While Fetching response, it is showing me a toast message...**
if !success {
self.hostViewController.view.hideToast()
self.hostViewController.view.makeToast("Unable to join Appointment please try different Appointment ID",
duration: self.toastDisplayDuration, position: CSToastPositionTop)
}

}

What happens to the meeting when you leave it for the first time? Did the host end the meeting for all?
Comment: meetingModel?.endMeeting()
 meetingModel.isEndedHandler = { [weak meetingModel] in {
                MeetingModule.shared().dismissMeeting(meetingModel)
}

When you leave the meeting, is there anyone left in the meeting?
Comment: How I can check this is the current meeting is at the end or not? Is this compulsory to end meetings on both ends. How to do force end the meeting if the opponent does not leave the same meeting on killing the app or vice versa.

When you try to rejoin the meeting, is it immediately after leaving the meeting? If not, how long before rejoining?
Comment: Yes I trying to rejoin after leaving the meeting.

**Comment by hokyungh** [comment]
@pankaj-rana01  I think this is due to [serverless demo](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js). 
So what happened was meeting has ended due to following reason [reference](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html).
1. No audio connections are present in the meeting for more than five minutes.
2. Less than two audio connections are present in the meeting for more than 30 minutes.
3. Screen share viewer connections are inactive for more than 30 minutes.
4. Run the DeleteMeeting API 
5. The meeting time exceeds 24 hours.

And you are trying to create meeting on already ended meeting which gives that error. Could you check if any one of them applies to your case?
