### ISSUE TITLE
Documentation incorrectly states getActiveAudioDevice() belongs to ActiveSpeakerDetector

### ISSUE THREAD

**Issue by aldao3057** [aws/amazon-chime-sdk-ios#329]
**Describe the bug**
`getActiveAudioDevice` appears under the `ActiveSpeakerDetector` section rather than the `DeviceController` section. This is confusing and misleads developers about what the method call does.

**To Reproduce**
1. Go to https://aws.github.io/amazon-chime-sdk-ios/Classes/DefaultAudioVideoFacade.html#/c:@M@AmazonChimeSDK@objc(pl)DeviceController(im)getActiveAudioDevice

**Expected behavior**
`getActiveAudioDevice` appears under the 'DeviceController' section.

**Comment by hokyungh** [comment]
Thank you for reporting. There must have been mistakes generating doc. Will look into why this happens.

**Comment by alnlau** [comment]
The documentation has been updated.
