### ISSUE TITLE
Unplugging headphones leads to an error

### ISSUE THREAD

**Issue by arturdev** [aws/amazon-chime-sdk-ios#333]
**Describe the bug**
When you select a Build-in Speaker and then switch to the connected Headphones, and unplug the headphones, the meeting freezes and leads to `audioSessionDidStopWithStatus(sessionStatus: MeetingSessionStatus)` method call with `unknown` statusCode.

**To Reproduce**
1. Choose Build-in-Speaker as an output device
2. Switch back to Headset Microphone
3. Unplug headphones

**Expected behavior**
It should automatically select another audio device

**Logs**
-

**Screenshots**
-

**Test environment Info (please complete the following information):**
 - Device: Any iOS Device
 - OS: 14.6
 - Version AmazonChimeSDK: 0.16.2
 - Version AmazonChimeSDKMedia: -

**Comment by hokyungh** [comment]
Thank you for opening issue. Will close it as duplicate https://github.com/aws/amazon-chime-sdk-ios/issues/322 and continue to update on other issue.
