### ISSUE TITLE
M1 Mac - Can't compile Chime for simulator

### ISSUE THREAD

**Issue by zeeshanz** [aws/amazon-chime-sdk-ios#334]
On our new M1 laptops, we are not able to compile our app which uses AWS Chime, when compiling it for simulator.

Has anybody encountered similar issues? It compiles fine otherwise on Intel laptops.

I don't see support for M1 in the SDK files. Is there any way to run Chime on M1 Simulator?

We get the following errors:

<img width="528" alt="Screen Shot 2021-08-17 at 9 27 11 AM" src="https://user-images.githubusercontent.com/4508321/129737873-a8fc8e4f-37a6-406f-9a0f-4175534c2593.png">
<img width="527" alt="Screen Shot 2021-08-17 at 9 27 58 AM" src="https://user-images.githubusercontent.com/4508321/129737875-30fd96a4-3f7d-4c5e-ab65-91962d19913a.png">

**Comment by zhinang-amazon** [comment]
Hi @zeeshanz,
Our team has not been able to pick up the work to support M1 Mac. The work is being tracked #295.
Closing this as duplicate and please follow that issue for update,
