### ISSUE TITLE
Can we customize video call UI Design to the full and small window view?

### ISSUE THREAD

**Issue by pankaj-rana01** [aws/amazon-chime-sdk-ios#335]
I want to customize the video call UI design to the full and small window view in the screen. It is possible to do that. 

If yes then please let me know how I can change that.

Big thanks!!!
![MicrosoftTeams-image](https://user-images.githubusercontent.com/71134511/130551657-bf4173c0-057d-4d88-a6f3-c96fd8af4c3e.png)

**Comment by hokyungh** [comment]
Hello @pankaj-rana01 sorry for late reply. In the iOS, you could try [bringsubviewtofront](https://developer.apple.com/documentation/uikit/uiview/1622541-bringsubviewtofront). Or you could try [zPosition](https://developer.apple.com/documentation/quartzcore/calayer/1410884-zposition). However, you might need to try it out which works best for you.

**Comment by pankaj-rana01** [comment]
@hokyungh, Hi thanks for the reply.  I have already implemented this in iOS. 

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-01 at 10 58 54](https://user-images.githubusercontent.com/71134511/131617208-89e715f2-ca01-41f8-aa8e-2924b125ecd6.png)

Thank you for your support!!.

**Comment by hokyungh** [comment]
Cool glad you make it work! Will close the issue. Feel free to reopen if you have any issue.
