### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by gtakahashi** [aws/amazon-chime-sdk-ios#338]
https://swift.org/package-manager/#conceptual-overview

**Comment by ziyiz-amzn** [comment]
Thank you @gtakahashi  for reporting. We will update this issue once we onboard with package manager.

**Comment by peacekimjapan** [comment]
Here is suggestion amazon chime team can do

1. zip `AmazonChimeSDK.xcframework` to `AmazonChimeSDK.xcframework.zip` and `AmazonChimeSDKMedia.xcframework` to` AmazonChimeSDKMedia.xcframework.zip`
2. upload to your s3 and figure out its sha-256 checksum
3. create `Package.swift` on project root and fill out `{s3buketsurl}` and `{sha256 checksum}`

```swift
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "AmazonChimeSDK",
    products: [
        .library(name: "AmazonChimeSDK", targets: ["AmazonChimeSDK", "AmazonChimeSDKMedia"])
    ],
    dependencies: [    
        .package(url: "https://github.com/birdrides/mockingbird.git", from: "0.15.0")
    ],
    targets: [
        .binaryTarget(
            name: "AmazonChimeSDK",
            url: "https://{s3buketsurl}/AmazonChimeSDK.xcframework.zip",
            checksum: "{sha256 checksum}"
        ),
        .binaryTarget(
            name: "AmazonChimeSDKMedia",
            url: "https://{s3buketsurl}/AmazonChimeSDKMedia.xcframework.zip",
            checksum: "{sha256 checksum}"
        )
    ]
)
```

and then developer can use in swift package manager

1. add package
(Added Package files)
<img width="432" alt="added package" src="https://user-images.githubusercontent.com/33534175/135723575-fb159983-217c-449b-a8e6-900eb30dba89.png">

2. add at frameworks, Libraries, and embedded content on project general setting
<img width="432" alt="스크린샷 2021-10-03 오전 12 48 04" src="https://user-images.githubusercontent.com/33534175/135723599-95334e53-92de-4765-af02-96a5631aaf9b.png">

- issue
if you have a local permission problem such as below
```
Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “Package.swift” in the folder “amazon-chime-sdk-ios”." UserInfo={NSFilePath=/Users/{username}/Library/Developer/Xcode/DerivedData/{your name}-goueebkrvcgclyedurmddizimvio/SourcePackages/checkouts/amazon-chime-sdk-ios/Package.swift, NSUnderlyingError=0x7fa18925baa0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
```
unlock the file lock at `/Users/{username}/Library/Developer/Xcode/DerivedData/{your name}-goueebkrvcgclyedurmddizimvio/SourcePackages/checkouts/amazon-chime-sdk-ios/Package.swift`


<hr>

This is what I can suggest at this time.

But you can also provide AmazonChimeSDKMedia as different project and import on AmazonChimeSDK
then, it seems you don't need AmazonChimeSDK as binary target.

and also hope to resolve above issue.

**Comment by Saurabh-vegans** [comment]
> Here is suggestion amazon chime team can do
> 
> 1. zip `AmazonChimeSDK.xcframework` to `AmazonChimeSDK.xcframework.zip` and `AmazonChimeSDKMedia.xcframework` to` AmazonChimeSDKMedia.xcframework.zip`
> 2. upload to your s3 and figure out its sha-256 checksum
> 3. create `Package.swift` on project root and fill out `{s3buketsurl}` and `{sha256 checksum}`
> 
> ```swift
> // swift-tools-version:5.3
> import PackageDescription
> 
> let package = Package(
>     name: "AmazonChimeSDK",
>     products: [
>         .library(name: "AmazonChimeSDK", targets: ["AmazonChimeSDK", "AmazonChimeSDKMedia"])
>     ],
>     dependencies: [    
>         .package(url: "https://github.com/birdrides/mockingbird.git", from: "0.15.0")
>     ],
>     targets: [
>         .binaryTarget(
>             name: "AmazonChimeSDK",
>             url: "https://{s3buketsurl}/AmazonChimeSDK.xcframework.zip",
>             checksum: "{sha256 checksum}"
>         ),
>         .binaryTarget(
>             name: "AmazonChimeSDKMedia",
>             url: "https://{s3buketsurl}/AmazonChimeSDKMedia.xcframework.zip",
>             checksum: "{sha256 checksum}"
>         )
>     ]
> )
> ```
> 
> and then developer can use in swift package manager
> 
> 1. add package
>    (Added Package files)
> 
> <img alt="added package" width="432" src="https://user-images.githubusercontent.com/33534175/135723575-fb159983-217c-449b-a8e6-900eb30dba89.png">
> 
> 2. add at frameworks, Libraries, and embedded content on project general setting
> 
> <img alt="스크린샷 2021-10-03 오전 12 48 04" width="432" src="https://user-images.githubusercontent.com/33534175/135723599-95334e53-92de-4765-af02-96a5631aaf9b.png">
> 
> * issue
>   if you have a local permission problem such as below
> 
> ```
> Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “Package.swift” in the folder “amazon-chime-sdk-ios”." UserInfo={NSFilePath=/Users/{username}/Library/Developer/Xcode/DerivedData/{your name}-goueebkrvcgclyedurmddizimvio/SourcePackages/checkouts/amazon-chime-sdk-ios/Package.swift, NSUnderlyingError=0x7fa18925baa0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
> ```
> 
> unlock the file lock at `/Users/{username}/Library/Developer/Xcode/DerivedData/{your name}-goueebkrvcgclyedurmddizimvio/SourcePackages/checkouts/amazon-chime-sdk-ios/Package.swift`
> 
> This is what I can suggest at this time.
> 
> But you can also provide AmazonChimeSDKMedia as different project and import on AmazonChimeSDK then, it seems you don't need AmazonChimeSDK as binary target.
> 
> and also hope to resolve above issue.

I tried like this but now it shows me error "No such module 'AmazonChimeSDK'". Any Idea?

**Comment by zhinang-amazon** [comment]
Hi,

I'm glad that you are able to find a workaround. Our team is currently working on [CocoaPods support](https://github.com/aws/amazon-chime-sdk-ios/issues/59), which will be an alternative to Swift Package Manager. We will keep this issue updated if we start working on this one.

**Comment by Saurabh-vegans** [comment]
Hi @zhinang-amazon, I saw that new version supports cocoa pods now. eagerly waiting for SPM support as I wanted to add it as a dependency in another swift package.

**Comment by zhinang-amazon** [comment]
HI @Saurabh-vegans,

We did just release CocoaPods support. Is that something you can use to integrate our Amazon Chime iOS SDK with before we add SPM support?

**Comment by Saurabh-vegans** [comment]
I tried but is not compatible with my custom SwiftPackageManager which I created as wrapper over main Amazon chime iOS sdk. I can not add Chime iOS SDK as a dependency in my swift package manager.

**Comment by matteocrippa** [comment]
It would be great to have SPM support in place too, Pods are a de facto standard for years, but SPM is starting to introduce a native alternative, considering the suggestion of @peacekimjapan that basically provide a step by step guide on how to do that

**Comment by notapplicableio** [comment]
We're transitioning of Cocoapods, and SPM would be great to get. Do you have a timeline?

**Comment by zhinang-amazon** [comment]
Hi all,

The team is currently working on other features and does not have a timeline to share at the moment. Apologies for the inconvenience.

**Comment by Saurabh-vegans** [comment]
@zhinang-amazon It will be better if you upload SDK with ".zip" extension, this way we can include it in custom SPM. Currently its .tar.gz so Swift Package Manager is not allowing to add remote resource with this extension.

**Comment by bukira** [comment]
yes please, SPM over outdated CocoaPods technology, Amazon get with the current times please

**Comment by paulocoutinhox** [comment]
I have the same problem:
https://forums.swift.org/t/support-tar-gz-in-spm/59849

**Comment by shgew** [comment]
@zhinang-amazon Hi! Could you please let us know, if there is an ETA for this issue?

**Comment by zhinang-amazon** [comment]
Hi, the team is working on other projects and has not started the work to add SPM support. Unfortunately we do not have an ETA at this point.

**Comment by notapplicableio** [comment]
@zhinang-amazon  my concern here is that SPM support is something fundamental to delivery and it’s not being prioritised. The implication here is that it forces manual or cocoapods dependency management.

- We know why manual isn’t a good option. 
- And given pods and SPM don’t really share this forces that pods must be used.

It’s been a reasonable amount of time since SPM became usable, so I think two things need to happen. 
- the team needs to raise the priority of SPM support. 
- the team needs to commit to an eta. 

I’m not sure what is being worked on but the basics of delivery mechanisms shouldn’t be forgotten over other/newer features. 

Additionally, I don’t believe the effort to support SPM is significant. There are no logical changes to code so no regression from that perspective.

**Comment by notapplicableio** [comment]
Thoughts on ^^ @zhinang-amazon?

**Comment by zhinang-amazon** [comment]
Apologies for the delay of this request. To help us drive prioritization, you can also file an AWS support case and refer to this Github issue and describe the impact due to the lack of SPM support.

**Comment by matteocrippa** [comment]
@zhinang-amazon if you switch the release file from `.tar.gz` to `.zip` is mostly already done

**Comment by notapplicableio** [comment]
Case # 11724006181

**Comment by shgew** [comment]
I think the criticality of this issue is being underestimated. Using Cocoapods is not a viable workaround for this issue, simply because most of the projects nowadays use SPM for feature separation, creating packages inside a single repo and linking them to the main target.

So, let’s say one of these feature modules is managed by SPM and I need to link Amazon Chime SDK as a dependency to it. **You can't link dependencies via Cocoapods to SPM-managed libraries**. So the only option left for me is to manually download the `.xcframework` files and link them locally, storing the files inside of my repo. And then the problems don’t stop, since the files are very large, and most of commerical git servers (i.e. GitHub) don’t support file sizes above 100MB, so I have to resort to tools like [git lfs](https://git-lfs.com/) to then track the files in `git` and be able to upload them, increasing the size of the repo by gigabytes, which reduces the usability of the repo.

I want to highlight that the only blocker for community to resolve this issue by ourselves is the fact that SPM doesn’t support `.tar.gz` extension on remote binary targets. So, re-uploading the `.xcframework`s in `.zip` format, instead of `.tar.gz` is the only change absolutely necessary. This wouldn’t change anything for the existing Cocoapods support, since it supports both extensions.

**Comment by bukira** [comment]
I agree with you and I want SPM, but for I simply made my own repo Chime and then load that via SPM, only thing is I have to update my repo every time there is a new build I require, so would be better for AWS to do, plus it took only a few minutes to create so there is very very little excuse why AWS cannot do it, there is no time excuse

**Comment by notapplicableio** [comment]
@zhinang-amazon Any chance of an update on this?

**Comment by a428tm** [comment]
> I agree with you and I want SPM, but for I simply made my own repo Chime and then load that via SPM, only thing is I have to update my repo every time there is a new build I require, so would be better for AWS to do, plus it took only a few minutes to create so there is very very little excuse why AWS cannot do it, there is no time excuse

@bukira
Could you share the steps with us on how we can do it

**Comment by a428tm** [comment]
> I agree with you and I want SPM, but for I simply made my own repo Chime and then load that via SPM, only thing is I have to update my repo every time there is a new build I require, so would be better for AWS to do, plus it took only a few minutes to create so there is very very little excuse why AWS cannot do it, there is no time excuse

@bukira
Could you share the steps with us on how we can do it?

**Comment by georgezy-amzn** [comment]
Hi @oliverfoggin,

We are not able to give a specific date, but it's coming very soon.

**Comment by georgezy-amzn** [comment]
Hi all,

SPM support is available now! https://github.com/aws/amazon-chime-sdk-ios-spm

**Comment by oliverfoggin** [comment]
@georgezy-amzn amazing!

We were just about to merge in a 250k line PR to bring Chime into the project. 🤣

**Comment by notapplicableio** [comment]
Thanks for doing this. You should add something to the main read me so people know it's there.
