### ISSUE TITLE
Use Callkit with Firebase FCM notifications

### ISSUE THREAD

**Issue by youssefhaitham-callvita** [aws/amazon-chime-sdk-ios#343]
I want to integrate Callkit with my react-native application. Unfortunately, I couldn't find any good documentation to integrate Callkit with IOS in a react-native application, would you recommend good documentation for this integration? 

What I need is to activate the UI of the Callkit when a Firebase FCM push notification is sent to the IOS device, how can this be done?

**Comment by hokyungh** [comment]
Hi thanks for posting. Sadly you would have to look up [Callkit](https://developer.apple.com/documentation/callkit?language=objc) to integrate into objective c and then put those logic into objective c [layer](https://github.com/aws-samples/amazon-chime-react-native-demo/tree/master/ios/RNDemo). 

You can also check out [blog](https://aws.amazon.com/blogs/business-productivity/how-to-integrate-apples-callkit-into-ios-applications-using-the-amazon-chime-sdk/) or check out our [codebase](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/CallKitManager.swift) to see if any of the code helps. 

Thanks!

**Comment by alnlau** [comment]
Let us know if the suggestion works for you.
