### ISSUE TITLE
Bluetooth devices not shown in the list when the app moves to background and then back to foreground.

### ISSUE THREAD

**Issue by caffieneToCode** [aws/amazon-chime-sdk-ios#346]
**Describe the bug**
MeetingSession.audioVideo.listAudioDevices() does not return duplicates in the list of audio devices for the bluetooth device connected to iOS device running on iOS 15 beta, first with MediaDevice type bluetoothAudio and again as MediaDevice type other.

**To Reproduce**
1. Start a meeting using chime with a Bluetooth device connected to iPhone/iPad
2. Get the list of Audio Devices with MeetingSession.audioVideo.listAudioDevices()
3. This list returns bluetooth devices connected to the iOS device.
4. Move the app to background and then move the app to the foreground
5. Get the list of Audio Devices with MeetingSession.audioVideo.listAudioDevices()
6. This list does not return bluetooth devices connected to the iOS device.

**Expected behavior**
MeetingSession.audioVideo.listAudioDevices() should always return a correct list of the audio devices connected to the iPhone/iPad

**Logs**
NA

**Screenshots**
Screenshot of the first time when we get the list.
<img width="879" alt="AmazonChimeSDK-Audio-Source-Issue-iOS15" src="https://user-images.githubusercontent.com/11851138/133209650-e9c4c4fb-c333-4286-9fc1-2989334b39bd.png">

Will soon Update the screenshot for the second time when we get the list.

**Test environment Info (please complete the following information):**
Device: iPhone XR
OS: iOS 15 beta 8 19A5340A
Version AmazonChimeSDK: v0.16.1
Version AmazonChimeSDKMedia: v0.11.2
Can you reproduce this in the demo app? Not tried

**Comment by dingyishen-amazon** [comment]
Hi, thank you for your feedback. 

I have tested the demo app with all the steps you provided, and did not see this issue. After the app moves back to foreground, the bluetooth device is still there.

Could you please try to reproduce this in the demo app(master brunch)?

**Comment by caffieneToCode** [comment]
@dingyishen-amazon: Did you notice the duplicate entries in the Bluetooth device list when you checked the list for the first time? If yes, did you notice that the duplicate entries for the Bluetooth device disappearing when you bring back the app to the foreground from the background? If Yes, then this might be a case that the second time the Bluetooth device that you see in the list are actually the Bluetooth devices with MediaType .other. This information will help us understand what could be wrong.

**Comment by hokyungh** [comment]
Hi @caffieneToCode, we have merged https://github.com/aws/amazon-chime-sdk-ios/pull/345 for duplicate entries.

**Comment by alnlau** [comment]
Hello,

A fix for this was released in the latest release. Let us know if you're still having issues.
