### ISSUE TITLE
Can't change the current audio device to a Built-in speaker.

### ISSUE THREAD

**Issue by pankaj-rana01** [aws/amazon-chime-sdk-ios#348]
Hi, 
I Can't change the current audio device to a Built-in speaker. I want to set the default audio device to a Built-in speaker when I am open this meeting controller. So please suggest to me how I can change this. 

MeetingViewController -> viewDidLoad -> I am using this but can't change the audio to the speaker. 
**meetingModel.currentMeetingSession.audioVideo.chooseAudioDevice(mediaDevice:(meetingModel.audioDevices[1]))**

Please help me out with this. Many thanks in advance..

AnyOne help....

**Comment by dylonChime** [comment]
Hi @pankaj-rana01,
The session has to start before calling chooseAudioDevice or it will be a noop. [See here](https://github.com/aws/amazon-chime-sdk-ios#use-case-3-list-audio-devices). Setting an audio device before the call is not supported currently. Were you calling chooseAudioDevice before staring the meeting?

**Comment by linsang21** [comment]
Hi @pankaj-rana01, @jonah-katz, the SDK device management is expected to use after joining the meeting. 

Also, `chooseAudioDevice` expected a SDK defined `MediaDevice` that returned from `listAudioDevices `. Sample is [here](https://github.com/aws/amazon-chime-sdk-ios#use-case-4-choose-audio-device-by-passing-mediadevice-object).

You can choose not to use SDK device management, but go with the system audio API, like what @jonah-katz uses.

Let us know if you have further question.
