### ISSUE TITLE
How to share the rear camera while broadcasting the front camera in iOS (dual camera or multi cam)

### ISSUE THREAD

**Issue by prodev-alt** [aws/amazon-chime-sdk-ios#375]
**Describe the bug**
We're going to share the rear camera to all participants while broadcasting the front camera in iOS app.
I've created the custom video source using DefaultCameraCaptureSource, but it didn't work.
Please check the following screenshot and code snippet.

**Screenshots**
![Monosnap 2021-11-10 22-23-32](https://user-images.githubusercontent.com/22884168/141231895-756c3322-370e-407c-9586-54678ad10ff2.png)

**Test environment Info (please complete the following information):**
 - Device: [e.g. iPhone12 pro]
 - OS: [e.g. iOS15]
 - Version AmazonChimeSDK: [e.g. 0.16.6]
 - Version AmazonChimeSDKMedia: [e.g. 0.12.1]
 - Can you reproduce this in the demo app? Yes sure.
If you are reporting a crash:
 - Are you using bitcode supported binaries? It's enabled.

```
func videoSessionDidStartWithStatus(sessionStatus: MeetingSessionStatus) {
        notifyHandler?("videoSessionDidStartWithStatus: \(sessionStatus.statusCode)")
        switch sessionStatus.statusCode {
        case .videoAtCapacityViewOnly:
            notifyHandler?("Maximum concurrent video limit reached! Failed to start local video")
            logWithFunctionName(message: "\(sessionStatus.statusCode)")
        default:
            logWithFunctionName(message: "\(sessionStatus.statusCode)")
        }
        videoModel.isLocalVideoActive = true
        screenShareModel.cameraCaptureModel.isSharing = true
        screenShareModel.startCameraCaptureHandler?()
    }
```

**Comment by prodev-alt** [comment]
------------- CameraCaptureModel.swift

```
class CameraCaptureModel: NSObject {
    let logger = ConsoleLogger(name: "CameraCaptureModel")
    let contentShareController: ContentShareController
    var isSharingHandler: ((Bool) -> Void)?
    
    lazy var cameraCaptureSource: DefaultCameraCaptureSource? = {
        if #available(iOS 11.0, *) {
            let source = DefaultCameraCaptureSource(logger: logger)
            source.addCaptureSourceObserver(observer: self)
            if let backCamera = MediaDevice.listVideoDevices().first(where: { item in
                item.type == .videoBackCamera
            }) {
                source.device = backCamera
            }            
            return source
        }
        return nil
    }()
    
    var isSharing = false {
        willSet(newValue) {
            if newValue == isSharing {
                return
            }
            if newValue {
                cameraCaptureSource?.start()
                isSharingHandler?(true)
            }
            else {
                cameraCaptureSource?.stop()
                isSharingHandler?(false)
            }
        }
    }
    
    init(contentShareController: ContentShareController) {
        self.contentShareController = contentShareController
    }
}

extension CameraCaptureModel: CaptureSourceObserver {
    func captureDidStart() {
        logger.info(msg: "CameraCaptureModel did start")
        let contentShareSource = ContentShareSource()
        contentShareSource.videoSource = cameraCaptureSource
        contentShareController.startContentShare(source: contentShareSource)
    }

    func captureDidStop() {
        logger.info(msg: "CameraCaptureModel did stop")
        contentShareController.stopContentShare()
        cameraCaptureSource?.removeCaptureSourceObserver(observer: self)
    }

    func captureDidFail(error: CaptureSourceError) {
        logger.error(msg: "CameraCaptureModel did fail: \(error.description)")
        isSharing = false
        contentShareController.stopContentShare()
    }
}
```

**Comment by alnlau** [comment]
Hello,

You can use a separate source for each camera and pass one source to `startLocalVideo` and one source to `startContentShare`. You may have to create your own source for this. You can reference the existing [DefaultCameraCaptureSource](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/audiovideo/video/capture/DefaultCameraCaptureSource.swift) in this case.

**Comment by prodev-alt** [comment]
@alnlau Thanks for reaching out to me.
As you can see the above code snippet, I created the separate source for each camera and passed them to startLocalVideo and startContentShare.
Can you show me the examples?

**Comment by prodev-alt** [comment]
@alnlau Please let me know. Looking forward to hearing from you as quickly as possible.

**Comment by alnlau** [comment]
Hello,

In the above code snippet, `cameraCaptureSource` is also being reused for the content share source. There should be two separate sources, one for each camera. 

Unfortunately, we don't have an example for using both front and rear cameras at once. You can follow this [guide](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/custom_video.md) for creating a custom source and https://developer.apple.com/videos/play/wwdc2019/249/ for the multi camera capture. Note that you'd still want two sources (one for `startLocalVideo` and one for `startContentShare`) and have one source sending the buffers from the front camera and the other source sending the buffers from the rear camera.

**Comment by alnlau** [comment]
As we don't have an example for both front and rear camera at once, I'll mark this issue as a feature request for creating an example.

**Comment by prodev-alt** [comment]
@alnlau `cameraCaptureSource ` was used for only the content share source, but not for the front camera.
Please check my code carefully.

**Comment by prodev-alt** [comment]
@alnlau Any update? Looking forward to hearing from you as quickly as possible. Thanks so much!

**Comment by prodev-alt** [comment]
@alnlau The front camera capturing is not capturing at all.
Sorry, but I can not understand your suggestion. Check your comment again.
Or send me the code snippet.

**Comment by prodev-alt** [comment]
@alnlau Sorry, but do you know how the AWS iOS Chime SDK works?

**Comment by prodev-alt** [comment]
@alnlau Any update? Looking forward to hearing from you as quickly as possible.
Actually, we need the example code snippet.
Content Share - Rear camera
Local video - Front camera

**Comment by prodev-alt** [comment]
@alnlau How's it coming along? Looking forward to hearing from you as quickly as possible.

**Comment by dingyishen-amazon** [comment]
Hi,

I have updated the sample code in my repo, it may not be in production quality, but the dual camera works well with it.
https://github.com/dingyishen-amazon/amazon-chime-sdk-ios-1/tree/dual-camera

Feel free to contact me if you have further questions.

Thank you.

**Comment by prodev-alt** [comment]
Hi @dingyishen-amazon Thanks for the update. Let me check it quickly. Thanks so much!

**Comment by dingyishen-amazon** [comment]
Hi @prodev-alt, here is the sample code in the ios public repo (https://github.com/aws/amazon-chime-sdk-ios/tree/dual-camera), please check this repo. Thank you.

**Comment by prodev-alt** [comment]
Hi @dingyishen-amazon Thank you!
