### ISSUE TITLE
Make the background blur for the video stream. 

### ISSUE THREAD

**Issue by trungnvnl** [aws/amazon-chime-sdk-ios#378]
# Tell us about your request
I'm trying to make the blur background with the deeplabV3 model, but the time to process for each frame is too long. So the video frame will be dropped and not smooth. 
Have any suggestions to make the blur background function? 
Thank you!

**Comment by hokyungh** [comment]
Thanks for opening an issue. We'll update the ticket once we have background blur feature out.

**Comment by georgezy-amzn** [comment]
We have background blur available now, please check the latest release.
