### ISSUE TITLE
PSTN calling support

### ISSUE THREAD

**Issue by durga0303** [aws/amazon-chime-sdk-ios#39]
Does Chime mobile SDK's support PSTN calls? I have gone through the iOS SDK and did not see any feature related to this feature

My requirement is to add a third user to the meeting session using the PSTN option. 
Users in the call should be able to directly call the other user using a phone number.

**Comment by mitankit** [comment]
Currently integration with PSTN is not supported but it is definitely on the roadmap. I am putting a Feature enhancement label as its a new feature.
We would love to hear more about your use case which would help us in prioritizing this feature. Could you please fill out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "“Tell us about your project:”. You can put the link of this GitHub issue there.

**Comment by hokyungh** [comment]
@durga0303 this could be possible using voice connector. More details can be found https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-cvc.html.
