### ISSUE TITLE
Meeting screen active speaker  need to show full screen and other participants should show on bottom of the page horizantal  how to achieve it?

### ISSUE THREAD

**Issue by MohanNB** [aws/amazon-chime-sdk-ios#394]
Hello Team,

in mobile app Meeting screen active speak  need to show full screen and other participants should show on button of the page horizontal .

How can I achieve this . I have tried to customise UI Part but I can't able change as per requirement .

**Comment by hokyungh** [comment]
Hello sorry. UI is not part of SDK, so we don't give suggestions on UI. However, were you able to open [Main.storyboard](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/Base.lproj/Main.storyboard) in Xcode and 


![Screen Shot 2022-01-20 at 3 56 20 PM](https://user-images.githubusercontent.com/57926812/150440941-5bc32922-4377-4104-a429-79ac48c27e85.png))

instead of VideoCollection used just the view?

**Comment by MohanNB** [comment]
Hello hokyungh,

Thanks for you updates, How can to identify video enabled Active Speaker &  self attender video .

can you please give the suggestion for achieve this .

**Comment by hokyungh** [comment]
Hi we already have example of identifying based on Active speaker. Could you checkout https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/video_pagination.md and see if this helps?

**Comment by MohanNB** [comment]
Hi hokyungh,

Thank you for support .

I have analysed shared document [https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/video_pagination.md ](url) and Latest Git Code .It's have Many changes . Old Git sample code automatically worked active speaker on Top of list . but now new git code not working .

Below code showing first self videotile then other remotevideotile 
`func collectionView(_ collectionView: UICollectionView,
                        cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let meetingModel = meetingModel, indexPath.item < meetingModel.videoModel.videoTileCount else {
            return UICollectionViewCell()
        }
        let isSelf = indexPath.item == 0
        let videoTileState = meetingModel.videoModel.getVideoTileState(for: indexPath)
        let displayName = meetingModel.getVideoTileDisplayName(for: indexPath)

        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: videoTileCellReuseIdentifier,for: indexPath) as? VideoTileCell else {
            return VideoTileCell()
        }

        cell.updateCell(name: displayName,
                        isSelf: isSelf,
                        videoTileState: videoTileState,
                        tag: indexPath.row)
        cell.delegate = meetingModel.videoModel

        if let tileState = videoTileState {
            if tileState.isLocalTile, !tileState.isContent, meetingModel.videoModel.isFrontCameraActive {
                cell.videoRenderView.mirror = true
            }
            meetingModel.bind(videoRenderView: cell.videoRenderView, tileId: tileState.tileId)
        }
        return cell
    }`


and assigning video tile on here: meetingModel.bind(videoRenderView: cell.videoRenderView, tileId: tileState.tileId)

can you please tell me how can I get current active speaker remote video title . and which func I need to call?

**Comment by dylonChime** [comment]
Hi @MohanNB,

If you want to know which attendee ID is associated with the local video tile, you can try something like this when active speakers update in `activeSpeakerDidDetect ` or `updateRemoteVideoStatesBasedOnActiveSpeakers`.

```
let videoTileState = meetingModel.videoModel.getVideoTileState(for: indexPath)

if tileState.isLocalTile {
...
}
```

**Comment by MohanNB** [comment]
Hi dylonChime,

Thank you so much 
it working
