### ISSUE TITLE
Mic stops working when phone call interrupts, even after phone call ends

### ISSUE THREAD

**Issue by jonah-katz** [aws/amazon-chime-sdk-ios#395]
**Describe the bug**
If you get a phone call during the meeting, the mic (expectedly mutes). However, its impossible to unmute when the phone call ends. 

**To Reproduce**
1. Start meeting
2. Receive a phone call, or make an outgoing call
3. End call
4. See that your mic doesnt work in the chime meeting.

**Comment by dylonChime** [comment]
Hi @jonah-katz 

I am unable to reproduce the issue on our demo app. Can you provide more information about your setup and logs?

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Version AmazonChimeSDK: [e.g. 0.4.0]
Version AmazonChimeSDKMedia: [e.g. 0.4.0]
Can you explain how your code differs from the demo app?

**Comment by ziyiz-amzn** [comment]
@jonah-katz In the use case of having Chime meeting and phone call concurrently, we would suggest you to start the meeting using CallKit, you find this feature in the demo app.

**Comment by dingyishen-amazon** [comment]
No response from requester.
