### ISSUE TITLE
FEATURE REQUEST - Flutter Support

### ISSUE THREAD

**Issue by mmmaxi** [aws/amazon-chime-sdk-ios#4]
It would be awesome to use the amazon-chime-sdk ios and android to build a flutter pub package to integrate it in an existing flutter project.

Are there any plans for doing so?

**Comment by dchen-aws** [comment]
@mmmaxi 
Thanks for reaching out. We are currently evaluating different options for cross platform support. I have added an enhancement label to your request and will update the thread once we have a plan to support Flutter.

**Comment by JannikSt** [comment]
+1

**Comment by umsbuyaka** [comment]
+1

**Comment by ciroanunciacao** [comment]
+1

**Comment by danielthomasdev** [comment]
+1 - Tag if in the works and I'll help where I can.

**Comment by matave** [comment]
+1!

**Comment by bernardbaker** [comment]
So there is currently no support for Flutter?

**Comment by mbenedek** [comment]
+1

**Comment by tawfeeqamro91** [comment]
+1

**Comment by eggnstone** [comment]
I started a plugin and it works for Android (base functionality only).
I'm not an iOS developer so if anyone wants to add the iOS part or improve the Android part or even add the Web part please take a look:
https://pub.dev/packages/eggnstone_amazon_chime

**Comment by wesleytoshio** [comment]
+1

**Comment by eggnstone** [comment]
I started a plugin (and got help on the iOS part) and it works for Android and iOS (base functionality only).
https://pub.dev/packages/eggnstone_amazon_chime
https://github.com/eggnstone/eggnstone_amazon_chime

**Comment by bugrasa** [comment]
+1

**Comment by eggnstone** [comment]
It seems my plugin is still the only available one and no official one in sight :(

But we dearly need an iOS programmer to fix the iOS part.
@henlamk started it and made it work but we are facing issues with the file size of the iOS libraries.

If you know Flutter and iOS please take a look if you can help:
https://pub.dev/packages/eggnstone_amazon_chime

**Comment by naz-eze** [comment]
+1

**Comment by tnishada** [comment]
+1

**Comment by AlexandraDamaschin** [comment]
+1

**Comment by AdamNSmith** [comment]
+1, this would be super useful.

**Comment by wildvat** [comment]
+1

**Comment by wcomicho** [comment]
+1

**Comment by wcomicho** [comment]
I need this in my next project. Hoping for the official plugin that will support both Android and iOS.

**Comment by DhavalRKansara** [comment]
+1

**Comment by dhelsper** [comment]
+1

**Comment by kNoAPP** [comment]
+1

**Comment by zhinang-amazon** [comment]
Our team published a [Flutter demo](https://github.com/aws-samples/amazon-chime-sdk-flutter-demo) application that bridges to our native iOS and Android SDK to demonstrate 1-1 audio video calling functionalities and how customers would build the Flutter-iOS/Android bridging. Closing this issue for now.

**Comment by nam-tran-t6** [comment]
is there any way to implement the Audio/Video call in Flutter (Android/iOS) app? 
How to receive a new call from another user?

**Comment by zhinang-amazon** [comment]
@nam-tran-t6 You would have to add push notification capability and handling in your application layer. That is not a functionality that we provide as part of the Amazon Chime Mobile SDK today
