### ISSUE TITLE
Live video conference with Chat feature available

### ISSUE THREAD

**Issue by nileshordex** [aws/amazon-chime-sdk-ios#40]
Does Chime mobile SDK's support live video conference with a chat feature? I have gone through the iOS SDK and did not see any chat related module

My requirement is group chat with the live conference because of due to some technical issue and drop the participant or be late join in the meeting and some other requirement purpose.

**Comment by hokyungh** [comment]
Right now amazon chime SDK only supports meetings with audio and video. Chat is not supported currently.
I am putting a Feature enhancement label as its a new feature.
We would love to hear more about your use case which would help us in prioritizing this feature. Could you please fill out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "“Tell us about your project:”. You can put the link of this GitHub issue there.

**Comment by maheshordex** [comment]
@hokyungh 

 if we want to add Group chat features with chime SDK than how can we achieve that outside of Chime SDK?

 And, What is the diff features support like @tagging for people when the sent message, Content sharing etc. for it?

**Comment by hokyungh** [comment]
@maheshordex @nileshordex . Sorry for late reply. Chat feature is currently under development. We'll be providing similar API like [JS](https://aws.github.io/amazon-chime-sdk-js/classes/sendandreceivedatamessagestask.html#senddatamessagehandler).

**Comment by maheshordex** [comment]
@hokyungh Thanks for your update :)

**Comment by AshrafJaddo** [comment]
@hokyungh  just to confirm so in any meeting Chat is only available between the JS clients. if someone joined via iOS can they see the chat message but cannot reply or they wont even see the chat messages. Thanks.

**Comment by hokyungh** [comment]
@AshrafJaddo there is no current API to receive or send those messages currently. We are adding those features both send & receive.

**Comment by AshrafJaddo** [comment]
Thanks you @hokyungh  for the quick update. do we you have an ETA?

**Comment by hokyungh** [comment]
@AshrafJaddo the code is currently under review, but we don't have exact ETA for this feature. However, this is our next big feature we are trying to push, so you'll hear from us soon. Thanks.

**Comment by zhinang-amazon** [comment]
@AshrafJaddo  Data Message is available with AmazonChimeSDK v0.8.1 release.
Make sure to also use the latest AmazonChimeSDKMedia framework v0.6.0
Closing this issue since the feature is released
