### ISSUE TITLE
Subscribe to Meeting Audio Buffers

### ISSUE THREAD

**Issue by esatp** [aws/amazon-chime-sdk-ios#405]
Hello,

I'm developing an App that requires custom view recording inside the app. Is it possible to get Meeting Audio Buffer in real time so I can merge it with my custom recording?

Best

**Comment by zhinang-amazon** [comment]
Hi @esatp,

Does this recording have to be locally on the device? Have you considered using our [Media Capture Pipeline](https://docs.aws.amazon.com/chime/latest/dg/media-capture.html) to record on the server side?

**Comment by esatp** [comment]
Hi @zhinang-amazon ,

Yes we need it locally since we have custom views for camera participants we are recoding locally a Custom Video and need to attach meeting Audio at the same time.

**Comment by hokyungh** [comment]
Hi I don't think we currently expose audio frame. Would you mind opening a feature request exposing it?

**Comment by ziyiz-amzn** [comment]
Feel free to reopen or open a feature request.
