### ISSUE TITLE
Video Recording with Mobile client only not working

### ISSUE THREAD

**Issue by maheshordex** [aws/amazon-chime-sdk-ios#41]
Does Chime mobile SDK support live video conference with recording those meeting video conferences running on Mobile only not in any browser?

If yes then can you have some useful links.

Because When we try to record mobile conference video with recording action API nothing is 
recorded and when we try the combination of mobile client + browser client recording is working.

**Comment by mitankit** [comment]
@maheshordex We do have a way to record the meetings running on mobile. 
The way it works is a bot user ((i.e. a headless meeting attendee) join an Amazon Chime SDK meeting session via a URL and record the meeting's audio, video and screen share in high definition (1080p at 30fps by default, but configurable) and stream output to a specified Amazon S3 bucket.
We already have a demo working for meeting on browser 
Here is the [link](https://aws.amazon.com/blogs/business-productivity/how-to-enable-client-side-recording-using-the-amazon-chime-sdk/) for how to do it
Here is the [link](https://github.com/aws-samples/amazon-chime-sdk-recording-demo) for source

**Note**: The above link shows the meeting on browser but you can change it for meetings on mobile. The only change is you would have to call the recording start and stop REST end point from mobile.

Let me know if you have any questions about the demo.

**Comment by maheshordex** [comment]
@mitankit 
It is capture recording if you started in the browser.
if both side only mobile app running than it is not capturing videos.
We tested it

**Comment by mitankit** [comment]
I will test it with mobile and let you know.

**Comment by maheshordex** [comment]
Ok

**Comment by mitankit** [comment]
@maheshordex I tried the recording demo with just the participants from mobile and it worked for me. The recording captured both audio and video from the mobile device
Could you please confirm the following?
1) Did you see the "<<Meeting Recorder>>" attendee in your mobile app

**Comment by mitankit** [comment]
@maheshordex We have not heard from you for sometime. Could you please update about this issue? Do you need more help from our side?

**Comment by maheshordex** [comment]
@mitankit 
How many client you have ?
1. Only Mobile devices
2. Mobile device + JS client browser.

Can you please confirm ?

**Comment by mitankit** [comment]
I have only 1 user who is on mobile device in the meeting.

**Comment by mitankit** [comment]
@maheshordex Any updates on this issue?

**Comment by mitankit** [comment]
Closing the issue since there is no response from the user. Feel free to reopen it if you still see the issue.
