### ISSUE TITLE
Share in app content getting failed and not sharing 

### ISSUE THREAD

**Issue by MohanNB** [aws/amazon-chime-sdk-ios#415]
When I share in app content not sharing screen and some time enabled app share status but screen not presenting to another .

Getting below error logs:
[RPScreenRecorder startCaptureWithHandler:completionHandler:]_block_invoke_2:482 failed to start due to error: Error Domain=com.apple.ReplayKit.RPRecordingErrorDomain Code=-5803 "Recording failed to start" UserInfo={NSLocalizedDescription=Recording failed to start}

[10080:1764088] [ERROR] InAppScreenCaptureModel - RPScreenRecorder start failed: Recording failed to start
[10080:1764088] [ERROR] InAppScreenCaptureModel - InAppScreenCaptureSource did fail: systemFailure
[10080:1764088] [INFO] InAppScreenCaptureModel - RPScreenRecorder not recording, so skipping stop

**Comment by hokyungh** [comment]
Hi do you mind providing more details like 
**Versions**
Amazon Chime SDK: 
Amazon Chime SDK Media: 

**Device**
OS Version:
Device Model:

**Step**
How to reproduce the issue.

**Comment by MohanNB** [comment]
Hey hokyungh,

Versions: 
if you need bitcode support:
[AmazonChimeSDK-0.18.0.tar.gz](https://amazon-chime-sdk-ios.s3.amazonaws.com/sdk/0.18.0/AmazonChimeSDK-0.18.0.tar.gz)
[AmazonChimeSDKMedia-0.14.0.tar.gz](https://amazon-chime-sdk-ios.s3.amazonaws.com/media/0.14.0/AmazonChimeSDKMedia-0.14.0.tar.gz)

Device
OS Version:15.3.1
Device Model:iPad 5th gen & iPhone 6Plus

Step
"How to reproduce the issue". when I click on share in app content getting above shared error logs.some enabled share in app content but screen showing empty gray color.

**Comment by dylonChime** [comment]
Hi @MohanNB,

I'm not able to reproduce this issue. Are you able to provide a diff between our demo and your app?

**Comment by linsang21** [comment]
Feel free to reopen and provide extended information if the problem still persists.
