### ISSUE TITLE
video title getting struck when I use app SDK some time  but same time web browser working ?

### ISSUE THREAD

**Issue by MohanNB** [aws/amazon-chime-sdk-ios#416]
we are using web and mobile app SDK for chime . while join meeting on Chime SDK some time video tile getting struck also  slow . but while joining web browser  I'm not getting that issue . how can I override the issue .

some can help me to fix the issues.

I have used version : [v0.18.0](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.18.0)

Thanks

**Comment by MohanNB** [comment]
Hey hokyungh,

we are connected five attendees two web and other three iPad and iPhone and android device .
iPad using wifi connection ,iPhone & android using LTE
Getting issue on  iPhone & android using LTE. mobile network brand Jio .
when we connect mobile web browser same devices working fine.
How long did the video tile get stuck? - video buffering 10 to 40 seconds struck.

**Comment by dylonChime** [comment]
Hi @MohanNB,

I assume your remote video tiles are getting stuck on the iOS, not your local video tile. I am able to reproduce this in a simulated degraded network, but video improves a bit when video resolution is reduced.

Are you getting audio issues as well?

As a workaround, you can use [data message](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/api_overview.md#10-sending-and-receiving-data-messages-optional) to send a message to remote attendees, telling them to send lower resolutions.
