### ISSUE TITLE
App Crashes Caused by EXC_BAD_ACCESS Exception in Media.framework

### ISSUE THREAD

**Issue by tianyux-amz** [aws/amazon-chime-sdk-ios#42]
**Describe the bug**
Master issue to track app crashes caused by EXC_BAD_ACCESS Exception in Media.framework

**To Reproduce**
- Reproduce step reported in #28 App crashing when exiting a meeting: [Repro](https://github.com/aws/amazon-chime-sdk-ios/issues/28#issue-613455525)

**Expected behavior**
The app should not crash

**Logs**
- Logs reported in #28 App crashing when exiting a meeting: [Log 1](https://github.com/aws/amazon-chime-sdk-ios/issues/28#issue-613455525)

**Comment by jadhavd183** [comment]
I used runtime sanitisation , got the App Crashes Caused by EXC_BAD_ACCESS and in the log it did show as: Use of Deallocated Memory
Detects when memory is used after being deallocated.

**Comment by tianyux-amz** [comment]
Hi @jadhavd183, are you still seeing this crash with AmazonChimeSDK v0.6.1 and AmazonChimeSDKMedia v0.4.3? If you do, please send us a full crash report (`.crash` file) so we can symbolicate the issue and troubleshooting the root cause.

**Comment by tianyux-amz** [comment]
This was fixed in the latest release (iOS v0.7.0 and Media v0.5.0). Please try it out and let us know if you have more questions or concerns. Thanks!

**Comment by jadhavd183** [comment]
@tianyux-amz  - The issue is fixed now, Thanks!
