### ISSUE TITLE
Device level Screen sharing not work in iOS

### ISSUE THREAD

**Issue by Vhora01** [aws/amazon-chime-sdk-ios#436]
I have follow all steps for screen sharing documentation .InAppScreenSharing is working.But when I have try to share device level screen share ,it is not worked.PLease suggest me .

**Comment by dingyishen-amazon** [comment]
Would you mind providing details on
-  Device: [e.g. iPhone6]
-  OS: [e.g. iOS8.1]
-  Version AmazonChimeSDK: [e.g. 0.4.0]
-  Version AmazonChimeSDKMedia: [e.g. 0.4.0]
-  Can you reproduce this in the demo app?

**Comment by hokyungh** [comment]
Hi we might need little more details on what you have tried.

So the last question is if you set 
[code](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoBroadcast/SampleHandler.swift#L12) matches with your [application group id](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemoBroadcast/AmazonChimeSDKDemoBroadcastDebug.entitlements#L7)

and additionally set [bundle id and appGroupId] (https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/AppConfiguration.swift#L14) from our demo app, are you able to send it or having same issue?

It might be also easier to tell us what steps have been completed, what structures you have, and issue you are having. Is it like you have a button to record, but it doesn't show the application or it has application, but clicking it doesn't really share the screen?

**Comment by Vhora01** [comment]
hello
I have used defined Amazonechime sdk and media sdk also.I have try with
xcframework also but when i am going to share screen SampleHandler is not
being call.But screen is being record in my device but dont share.
I have follow all steps in documentation.
Please suggest me or if possible then i can show you my code through screen
sharing

thanks
