### ISSUE TITLE
ITMS-90562: Invalid Bundle - Unable to submit builds to the App Store/Distribution with Bitcode is broken

### ISSUE THREAD

**Issue by tomsinqg** [aws/amazon-chime-sdk-ios#443]
**Describe the bug**
When submitting to Apple you get the error **ITMS-90562**. Doing a local distribution with "Rebuild from Bitcode" enabled gives a more detailed error:
```
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode-13.3.0.app/Contents/Developer/usr/bin/python3 /Applications/Xcode-13.3.0.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode-13.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode-13.3.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -o /var/folders/9v/9p9j5jpj6pdglv1vlc79d53w0000gn/T/ipatool20220414-11012-hfkcq7/thinned-out/arm64/Payload/MyApp.app/Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia --generate-dsym /var/folders/9v/9p9j5jpj6pdglv1vlc79d53w0000gn/T/ipatool20220414-11012-hfkcq7/thinned-out/arm64/Payload/MyApp.app/Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia.dSYM --strip-swift-symbols /var/folders/9v/9p9j5jpj6pdglv1vlc79d53w0000gn/T/ipatool20220414-11012-hfkcq7/thinned-in/arm64/Payload/MyApp.app/Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia
Status: pid 13468 exit 1
Stdout:
	SDK path: /Applications/Xcode-13.3.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/
```

**To Reproduce**
1. Create a blank project
2. Add Amazon Chime pod or framework (bitcode version)
3. Product -> Archive
4. Once archived open the Organizer (should open automatically).
5. Click Distribute App -> Development -> Make sure "Rebuild from Bitcode" is enabled -> either signing method -> You should see the error

**Expected behavior**
There should be no error and it should be distributable

**Test environment Info (please complete the following information):**
 - Xcode: 13.3
 - Version AmazonChimeSDK: 19.3
 - Version AmazonChimeSDKMedia: 15.3
 - Can you reproduce this in the demo app?
If you are reporting a crash:
 - Are you using bitcode supported binaries? Yes

**Comment by hokyungh** [comment]
Thank you for reporting. We'll try to reproduce and update the ticket.

**Comment by goelay** [comment]
It's always reproducible.  Please fix the same. When you try to upload the build it gets uploaded, but we get an error on email.

**Comment by goelay** [comment]
I am also facing the same issue. Please fix asap.

**Comment by hokyungh** [comment]
Hi sorry for the trouble, we were able to reproduce the issue and actively working on the fix. We'll update the ticket once we have solution for this issue. Meanwhile for workaround could you uncheck `Rebuild from Bitcode` or disable bitcode or downgrade the version while uploading to App Store.

Sorry for the trouble and thank you for the patience.

**Comment by goelay** [comment]
Hi,
Any update?. Above steps not helping us as we are using app clip so without bitcode its not working.

**Comment by hokyungh** [comment]
We are actively working on this, and targeting next release to address this.

**Comment by alexmglover** [comment]
I am also having the same issue. What is the ETA on next release?

**Comment by ashirkhan94** [comment]
hi, same issue for me

**Comment by linsang21** [comment]
The latest [0.20.0](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.20.0) is released with the fix, give it a try and let us know if there's further issue.

**Comment by goelay** [comment]
[!] CocoaPods could not find compatible versions for pod "AmazonChimeSDK-Bitcode":
  In Podfile:
 AmazonChimeSDK-Bitcode (= 0.2.0)

**Comment by linsang21** [comment]
@goelay Should be 0.20.0
