### ISSUE TITLE
Can not get chime audio from avcapture when use peripheral

### ISSUE THREAD

**Issue by SanuChou** [aws/amazon-chime-sdk-ios#448]
Describe the question :
I’m trying to get chime audio via AVCaptureSession.
If Im using the microphone on a phone, I got the audio from chime in CMSampleBuffer, if Im using AirPods / EarPods, I can not get the audio from chime. 
To reproduce this behavior:
1. Use AirPods or EarPods 
2. Setup AVAudioSession category to .playAndRecord, options to [.allowBluetooth, .defaultToSpeaker, .mixWithOthers]
3. Create a capture custom audio input and output
4. Start chime meeting
5. Got the CMSampleBuffer from captureOutput(_ output: AVCaptureOutput delegate
6. Use this buffer to do something

Test environment Info :
* Version AmazonChimeSDK: 0.19.1
* Version AmazonChimeSDKMedia: 0.15.1

Additional context:
I am wondering 
1. For audio, is any protocol to get CMSampleBuffer, like function onVideoFrameReceived in class VideoRenderView
2. Is it because the audiosession setting is wrong that I can't capture the sound from chime after connecting the peripheral
3. Is there any suggested solution that allows me to record audio from chime locally

**Comment by dylonChime** [comment]
Hi @SanuChou,

Are you sure the Airpods are selected? Have you tried calling `chooseAudioDevice` to explicitly choose the Airpods? You can get the list of available audio devices by calling `listAudioDevices` or listening to `audioDeviceDidChange`. The OS seems to enforce a certain priority for devices selected unless you manually select the device. Issue #89 provides a workaround for that.

Currently we don't support a custom audio processing. I'll mark this as a feature request.

**Comment by dylonChime** [comment]
I'll dedupe and close this issue. Duplicate issue: #294
