### ISSUE TITLE
What scenarios causes MediaError.audioFailedToStart to be thrown?

### ISSUE THREAD

**Issue by keverly** [aws/amazon-chime-sdk-ios#450]
We are seeing some instances of customers receiving `MediaError.audioFailedToStart` when trying to call `DefaultAudioVideoController.start(callKitEnabled: true)`. We have been unable to reproduce this locally and are looking for some insight into what could cause these errors. The only instance I'm aware of is not setting up the audio session, but we can see from our logs all instances have `provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession)` called before we attempt to join the meeting. Do you all have any ideas about what else would cause this? It seems like it could be a system setting or maybe something else is trying to use the audio session.

**Comment by dylonChime** [comment]
There are many reasons it might fail. Some reasons include failure to allocate memory, pthread mutex API failures, Apache Portable Runtime API failures, and Core Audio API failures. It can also fail if it's called from the wrong state, like trying to start while it's already started. Do you know if it only occurs on a particular device or OS?
