### ISSUE TITLE
Why native function written in objective C is is not returning anything?

### ISSUE THREAD

**Issue by Saifak34** [aws/amazon-chime-sdk-ios#462]
**Describe the bug**
I am trying to get output from native function to use in frontend, here is the function,

`RCT_EXPORT_METHOD(getActiveAudioDevice:
                 resolver:(RCTPromiseResolveBlock)resolve
                 rejecter:(RCTPromiseRejectBlock)reject)
{
  MediaDevice * _Nullable  devices = [meetingSession.audioVideo getActiveAudioDevice];
  NSLog(@"Hello Devices: %@", devices);
  
  if (!devices) {
    reject(@"event_failure", @"failed to list audio devices", nil);
  } else {
    resolve(devices);
  }

}`

When I trigger this from frontend I can see in logs that Native function (Hello Devices ) is returning a device but in JS all I get is undefined, any idea what I am doing wrong here ?

**Comment by ziyiz-amzn** [comment]
Hi @Saifak34 Thanks for reporting this. Has the new function `getActiveAudioDevice` been declared in Bridge.js? Seems this native function is not bridged to js. Also, have you tried with a pure function instead of a promise and see if it works?

**Comment by Saifak34** [comment]
I have not tried using pure function because I thought this will work like listing audio devices, let me give it a try and also check bridge.js. Thank you for the input

**Comment by ziyiz-amzn** [comment]
return value is [optional MediaDevice](https://github.com/aws/amazon-chime-sdk-ios/blob/71dd4a92cabe73b2e98ffa0556d0320c0763eef9/AmazonChimeSDK/AmazonChimeSDK/device/DeviceController.swift#L44)
