### ISSUE TITLE
Crash on M1 when called AudioVideoFacade's listAudioDevices function

### ISSUE THREAD

**Issue by omerturhan** [aws/amazon-chime-sdk-ios#468]
**Describe the bug**
Application crahes on M1 build when **AudioVideoFacade** class' **listAudioDevices** function is called.

**To Reproduce**
1-) Call the start function of AudioVideoFacade
2-) Afterwards call the listAudioDevices function of AudioVideoFacade

**Expected behavior**
Expected to not getting a crash when calling start function

**Logs**
> 2022-05-13 13:02:35.378790+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: others_joined.wav err: 7
> 2022-05-13 13:02:35.378898+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: others_left.wav err: 7
> 2022-05-13 13:02:35.378960+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: reconnecting.wav err: 7
> 2022-05-13 13:02:35.379014+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: reconnected.wav err: 7
> 2022-05-13 13:02:35.379058+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: reconnect_failed.wav err: 7
> 2022-05-13 13:02:35.379099+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: rumble_strips.wav err: 7
> 2022-05-13 13:02:35.379136+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: first_caller.wav err: 7
> 2022-05-13 13:02:35.379174+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: remote_muted.wav err: 7
> 2022-05-13 13:02:35.379212+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: call_waiting.wav err: 7
> 2022-05-13 13:02:35.381716+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: ring_back.wav err: 7
> 2022-05-13 13:02:35.381762+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: first_caller_beep.wav err: 7
> 2022-05-13 13:02:35.381808+0300 0[15802:95111] [ERROR] VideoChatManager - audio cues: welcome.wav err: 7
> 2022-05-13 13:02:35.417754+0300 0[15802:95111] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000399ce40> 30010C1C-93BF-11D8-8B5B-000A95AF9C6A
> 2022-05-13 13:02:36.623532+0300 0[15802:95111] device model is iPad8,6
> 2022-05-13 13:02:36.623582+0300 0[15802:95111] hardware model is MacBookPro18,2
> 2022-05-13 13:02:36.692781+0300 0[15802:95111] [as] ATAudioSessionClientImpl.mm:232   Error: AudioSession not initialized
> 2022-05-13 13:02:36.692827+0300 0[15802:95111] [ERROR] VideoChatManager - xal_core_audio: IOS Could not get the current HW sample rate
> 2022-05-13 13:02:36.692848+0300 0[15802:95111] [ERROR] VideoChatManager - xal_core_audio: configure input AU buffer size failed
> 2022-05-13 13:02:36.711258+0300 0[15802:95111] [ERROR] VideoChatManager - failed to start xal spk; err=25
> 2022-05-13 13:02:36.711315+0300 0[15802:95111] [ERROR] VideoChatManager - media stream: failed to start speaker audio; err=0
> 2022-05-13 13:02:37.415327+0300 0[15802:98543] [ERROR] VideoChatManager - in service, peer read err=3
> 2022-05-13 13:02:37.415636+0300 0[15802:98543] [ERROR] VideoChatManager - audio_client/connector/duplex/dtls/4dab07b0592fae7cebd8ca77555a386a.k.m3.ue1.app.chime.aws:3478: Failed to service xtl while reading response; error=1
> 2022-05-13 13:02:37.416955+0300 0[15802:95111] [ERROR] VideoChatManager - failed to start media stream; err=6

**Test environment Info (please complete the following information):**
 - Device: Macbook M1 Max (16' 2021)
 - OS: MacOS Monterey **12.3.1**
 - Version AmazonChimeSDK: **0.20.0**
 - Version AmazonChimeSDKMedia: **0.16.0**
 - Can you reproduce this in the demo app? **Yes**
If you are reporting a crash:
 - Are you using bitcode supported binaries? **No**
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.
**Additional context**

**Comment by linsang21** [comment]
Hi @omerturhan, you mentioned this is a crash, do we get any crash file other than the log you provided? If not, could you also reproduce with the demo app (since you said it can), and paste log here too?

**Comment by manghwanitin** [comment]
@linsang21 
We are also facing same crash.

Please find the SDK versions used by our team
Version AmazonChimeSDK: 0.21.0
Version AmazonChimeSDKMedia: 0.17.0

Also attaching crash logs as requested.
[2023-12-28_16-12-28.1496_-0500-d499a5c2c99de0c06a0095bdd66c56c9d53b8ef1.crash.zip](https://github.com/aws/amazon-chime-sdk-ios/files/14437812/2023-12-28_16-12-28.1496_-0500-d499a5c2c99de0c06a0095bdd66c56c9d53b8ef1.crash.zip)
