### ISSUE TITLE
Qt support

### ISSUE THREAD

**Issue by MartinDelille** [aws/amazon-chime-sdk-ios#47]
**Is your feature request related to a problem? Please describe.**

There is no Qt SDK.

**Describe the solution you'd like**
I would like to integrate Amazone Chime in my Qt client application like https://github.com/aws/amazon-chime-sdk-qt
I know that this is the iOS sdk but I post here since I only see javascript and android support.

My application is designed to be cross plateform (MacOS/Windows/iOS).

**Describe alternatives you've considered**

https://github.com/aws/amazon-chime-sdk-js but I would be sad to embed a chromium in my app only for this feature and I'm not sure to see it working for iOS.

**Additional context**

Nope.

**Comment by mitankit** [comment]
> I would like to integrate Amazone Chime in my Qt client application like https://github.com/aws/amazon-chime-sdk-qt
I know that this is the iOS sdk but I post here since I only see javascript and android support.

I am not sure if I understood you correctly? 
Are you implying you are looking for iOS SDK?

**Comment by mitankit** [comment]
Not sure if I have understood you correctly.
Are you implying that you are looking for a new SDK based on qt?

**Comment by MartinDelille** [comment]
Yes

**Comment by raul-guerrero** [comment]
I think this is simpler than expected, using the embedded C++ signaling client library plus the Qt multimedia module, is not as hard as you might think.
I'm just checking the embedded client library, I'm not sure if it's multiplatform, if it is then even simpler to implement.

**Comment by MartinDelille** [comment]
I'm not interested anymore but indeed the c++ sdk might be the right way to go!
