### ISSUE TITLE
Video frame starts lagging/Freezing if number of user is more than 12.

### ISSUE THREAD

**Issue by leadIosDev** [aws/amazon-chime-sdk-ios#477]
In iOS when number of user is more than 12 in a meeting video starts lagging/Frame drops

**To Reproduce**
Join a meeting with more than 12 users for a minimum 10-15mins. Turn on video for all the users.

**Test environment Info**
• Device: All iOS devces
• OS: iOS 15
• Version amazon-chime-sdk: (0.20.0)
• Version amazon-chime-sdk-media: (0.16.0)
• Can you reproduce this in the demo app. Yes

**Comment by alnlau** [comment]
Hello,

Could you provide the meeting ID and device logs for troubleshooting (https://github.com/aws/amazon-chime-sdk-ios#debugging)? Also, what kind of network was the device using?

**Comment by MohdIrfan12** [comment]
@alnlau This and another one that I reported for Android here (https://github.com/aws/amazon-chime-sdk-android/issues/449), are the same. I mean we are experiencing this issue on both platforms( Android/IOS)

**Comment by hokyungh** [comment]
Could you verify that suggestion in https://github.com/aws/amazon-chime-sdk-android/issues/449 fixed your issue in iOS as well?

**Comment by ziyiz-amzn** [comment]
Closing it for now. Feel free to reopen if need.
