### ISSUE TITLE
App is getting crash on AmazonChimeSDKMedia VideoRendererAdapter::ClearFrame:

### ISSUE THREAD

**Issue by kuldeeptripthee** [aws/amazon-chime-sdk-ios#48]
App is getting crash if remote participants are getting disconnected multiple time.

![Screenshot 2020-05-30 at 11 43 47 AM](https://user-images.githubusercontent.com/27189615/83321086-ecb8f980-a26a-11ea-8695-f5c837e2e055.png)

**Comment by wanghaor-amzn** [comment]
@kuldeeptripthee Could you provide more details of this issue by filling out our bug report template? Thanks

**Comment by kuldeeptripthee** [comment]
@wanghaor-amzn  Please check the following details  as requested 

**Describe the bug**
If we have multiple attendee in call sometime where attendee left from the call app is getting crashed 

**To Reproduce**
Steps to reproduce the behaviour:
1. Join call with multiple attendee with slow internet connection.
2. As internet is slow attendee will reconnect 
3. sometime on reconnect app is getting crashed 

**Expected behavior**
App should not crash it should remove attendee when the left from the call without crash 

**Logs**
![Screenshot 2020-05-30 at 11 44 00 AM](https://user-images.githubusercontent.com/27189615/83477801-c89b2980-a4b1-11ea-8846-84aaa562f888.png)


**Test environment Info (please complete the following information):**
 - Device: iPhone6
 - OS: 12.4.4
 - Version AmazonChimeSDK:0.6.1
 - Version AmazonChimeSDKMedia:0.4.3

Please let me know if any other information needed.

**Comment by tianyux-amz** [comment]
This was fixed in the latest release (iOS v0.7.0 and Media v0.5.0). Please try it out and let us know if you have more questions or concerns. Thanks!
