### ISSUE TITLE
ObservableMetric Video Packet loss is less than expected. 

### ISSUE THREAD

**Issue by keverly** [aws/amazon-chime-sdk-ios#489]
**Describe the bug**
When looking at `ObservableMetric`s provided by `MetricsObserver.metricsDidReceive()`, the values of [videoSendPacketLossPercent](https://aws.github.io/amazon-chime-sdk-ios/Enums/ObservableMetric.html#/c:@M@AmazonChimeSDK@E@ObservableMetric@ObservableMetricVideoSendPacketLossPercent) and [videoReceivePacketLossPercent](https://aws.github.io/amazon-chime-sdk-ios/Enums/ObservableMetric.html#/c:@M@AmazonChimeSDK@E@ObservableMetric@ObservableMetricVideoReceivePacketLossPercent) seem to be lower than expected. When turning on iOS's network limiter to "Very bad", We get values consistently less than 1, and occasionally see values between 1-2. If these are percentages, then we would expect a higher percent of package loss for poor connections.  When using the network limiter for another party, we only see values of ~0 for `videoRecievePacketLossPercent`. 

**To Reproduce**
1. Start a meeting and send local video
2. Add a `MetricsObserver` and implement `metricsDidReceive(metrics:)`.
3. In the iOS settings, go to Developer -> Network Link Conditioner. Enable it and select "Very Bad Network".

**Expected behavior**
We expect to see packet loss above 1-2%. For Audio, we see values between 0 and 100 which seems more in line with what we expect. 

**Logs**
Testing: videoSendPacketLossPercent: 0.1572243264097023
Testing: videoSendPacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0.05002811752077682
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0.07689138825531314
Testing: videoSendPacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0.1577166111634989
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0.1967884982422862
Testing: videoSendPacketLossPercent: 0
Testing: videoSendPacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0
Testing: videoReceivePacketLossPercent: 0

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 15.5
 - Version AmazonChimeSDK: 0.19.4 (0.21.1 for demo app)
 - Version AmazonChimeSDKMedia: 0.15.4 (0.17.1 for demo app)
 - Can you reproduce this in the demo app? Yes

**Additional Context**
My guess would be that these values are on a scale of 0-1, where we multiply it by 100 to get the percent value (although that doesn't explain the occasional 1-2 value we see). Looking to get confirmation on this assumption. If not, would like some insight into why the values are so low.

**Comment by georgezy-amzn** [comment]
Hi @keverly, thanks for reporting this. We will investigate more.

**Comment by ziyiz-amzn** [comment]
Please check out the fix in the [latest release](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.22.0). Closing this for now.
