### ISSUE TITLE
Enabling the blur makes the video laggy on receiving devices

### ISSUE THREAD

**Issue by ThomasDev321** [aws/amazon-chime-sdk-ios#494]
**Describe the bug**

The local video display is correct, but attendees receive a lagging video stream while the blur is used.
The `videoSendBitrate` value is half the size while using the blur. 500000 bit/s compared to 1000000 bit/s without.

**Test environment Info:**
 - Device: iPhone 11
 - OS: iOS 15.5
 - Version AmazonChimeSDK: 0.21.2
 - Version AmazonChimeSDKMedia: 0.17.2
 - Version AmazonChimeSDKMachineLearning: 0.1.0

**Comment by dingyishen-amazon** [comment]
Hi @ThomasDev321, I cannot reproduce the issue, after I turn on the background blur, the `videoSendBitrate` value is also around the previous value. It could be due to the CPU usage limitation.
