### ISSUE TITLE
App randomly crashes when implementing active speaker observer

### ISSUE THREAD

**Issue by antonrenzobenedict** [aws/amazon-chime-sdk-ios#50]
**Describe the bug**
App randomly crashes while observing active speaker observer

**To Reproduce**
1. Listen on active speaker
2. App will crash randomly

**Expected behavior**
App will not crash

**Logs**
[sym1.zip](https://github.com/aws/amazon-chime-sdk-ios/files/4716636/sym1.zip)
[sym2.zip](https://github.com/aws/amazon-chime-sdk-ios/files/4716638/sym2.zip)
[sym3.zip](https://github.com/aws/amazon-chime-sdk-ios/files/4715585/sym3.zip)

**Screenshots**
Please see screenshot from atttached logs
![image](https://user-images.githubusercontent.com/13776488/83494940-973e5000-a4e9-11ea-8a17-4bc56e7be208.png)

![image](https://user-images.githubusercontent.com/13776488/83512461-d0cf8500-a502-11ea-9755-97aea2ae59b7.png)

**Test environment Info (please complete the following information):**
 - Device: iPad11,3
 - OS: iOS13.3
 - Version AmazonChimeSDK: 0.6.1
 - Version AmazonChimeSDKMedia: 0.4.3

**Additional context**
This seems to happen randomly, tested on different OS and Devices

**Comment by wanghaor-amzn** [comment]
@antonrenzobenedict We've already had a fix for this issue but it is not released yet. We will include the fix in next release. Thanks.

**Comment by antonrenzobenedict** [comment]
Hi @wanghaor-amzn, may we know when this fix will be released?

Thanks!

**Comment by tianyux-amz** [comment]
@antonrenzobenedict We are planning to have a release this Friday. Will let you know once the new release is available.

**Comment by antonrenzobenedict** [comment]
@tianyux-amz Looking forward to the release, Thanks!

**Comment by tianyux-amz** [comment]
This was fixed in the latest release (iOS v0.7.0 and Media v0.5.0). Please try it out and let us know if you have more questions or concerns. Thanks!
