### ISSUE TITLE
Video laggy on remote devices with iOS 15.4+

### ISSUE THREAD

**Issue by Jim-Bar** [aws/amazon-chime-sdk-ios#505]
Hi,

We encounter a bug with all iPhone devices in version 15.4 or greater. Devices with version at most 15.3 do not share this issue. We confirmed that a particular iPhone in 15.3 would work fine, but once updated in 15.4 or later would present the bug.

The problem is that for those devices, the video is very laggy on receiving devices (be it a PC, Mac, iPhone or Android) although the local video is fine. This bug shows up in our application and is also reproduced using [Amazon Chime’s Demo App](https://github.com/aws/amazon-chime-sdk-ios#running-the-demo-app) (on iOS) with [Amazon Chime’s Browser Meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) (on desktop).

**To reproduce**:

1. Set up the [Browser Meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) (we had to replace occurrences of `127.0.0.1` by `0.0.0.0` for letting devices on the same network connect to the meeting)
2. Note the IP address of the desktop computer starting the demo
3. Build the [Demo App](https://github.com/aws/amazon-chime-sdk-ios#running-the-demo-app) with the previous IP set as server URL in `AppConfiguration`
4. Start and join a meeting on both ends

**Expected behavior**: the iPhone’s video is smooth on remote ends.

**Actual behavior**: the iPhone’s video is laggy on remote ends, but only when the emitting iPhone is in version 15.4+. 

We noticed that frames are dropped by WebRTC when this occurs (this is 1280x720):

    2022-07-27 17:29:22.851128+0200 App[1921:80114] [DEFAULT] Tag - [014:325][71939] (video_stream_encoder.cc:1690): Drop Frame: target bitrate 146112, input frame rate 30

It still happens with lower definitions such as 192x144 (but less).

I’ve made videos using the Demo App to illustrate the issue:

- [Video with iOS < 15.4 (smooth)](https://vimeo.com/734040399)
- [Video with iOS >= 15.4 (laggy)](https://vimeo.com/734042125)

**Additional context**

Reproduced at least with 0.19.3 and 0.22.0.

We tried setting different formats, but the issue is reproduced with all of them. Android phones do not have this issue.

This is a pretty bad situation to be in for us, as our customers experience the issue in their video meetings.

Thanks for your help.

**Comment by ziyiz-amzn** [comment]
Thank you for reporting. We are investigating on it.

**Comment by Jim-Bar** [comment]
Have you been able to reproduce the issue?

**Comment by ziyiz-amzn** [comment]
Yes, it can be reproduced on 15.4+. The team is working on it.

**Comment by hensmi-amazon** [comment]
The fix should be in the next release. 

The issue was that VideoToolbox encoders were significantly overshooting their target rates, and the built in adaption within the SDK was not enough to lower it further. As a last effort the media send pipeline will drop frames, hence the logs.

**Comment by Jim-Bar** [comment]
Thanks for the feedback. Do you have a time estimate for the next release?

**Comment by ziyiz-amzn** [comment]
The fix is released in https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.22.2

**Comment by Jim-Bar** [comment]
The fix is working as intended, thank you for solving this.
