### ISSUE TITLE
Can't join meeting as a "listener" receiving only audio - AudioMode, .noDevice, .noAudio

### ISSUE THREAD

**Issue by hvsw** [aws/amazon-chime-sdk-ios#507]
# Context
Joining with `audioMode` as `.noDevice` causes no audio to be received; and joining with default configuration causes camera and audio permissions to be asked even without using it aka "join a listener". We want this behavior to make users to join using the [media replication feature](https://docs.aws.amazon.com/chime-sdk/latest/dg/media-replication.html) which is receive-only without having to ask for user permissions(or only ask when needed, i.e. they're promoted to speakers for example).

At some point, we had support to enable [Audio/Video Configuration for Join Without Audio #363](https://github.com/aws/amazon-chime-sdk-ios/pull/363 ), but it seems that changed to `.noDevice` with a different behavior of not receiving any audio.

Is this the expected behavior? How can I set up the SDK to allow someone to join as a "listener/viewer" that can be promoted on the fly(including iOS permission handling)? Is this possible today? If not, is there something on the road map?

This also happens on the Android SDK. React seems to have implemented both `.noAudio` and `.noDevice` behaviors with `Audio` and `None`.

References:
https://github.com/aws/amazon-chime-sdk-js/issues/2099#issuecomment-1085132691
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f1b599441543e90c1d20fd41d0a03ec7ba995c23/src/components/quickStarts.stories.mdx

# To Reproduce
1. Start a meeting
2. Setup `DefaultAudioClientController.audio` to `.noDevice`.
3. Notice no audio is received

# Expected behavior
SDK should provide extension points so clients can control which OS permissions will end up being required based on the provided experience.

**Comment by georgezy-amzn** [comment]
Hi @hvsw, for `.noDevice`, this is expected behaviour; for default configuration, audio is required, that's why audio permission will be asked(camera permission is only asked on request).

Currently we don't support switching audio mode on the fly, I'll mark this as feature request.

**Comment by linsang21** [comment]
[v0.25.0](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.25.0) introduces [new audio capability](https://github.com/aws/amazon-chime-sdk-ios/blob/adeca0cfc35572fbef3ba773a48ed54c3b208d13/AmazonChimeSDK/AmazonChimeSDK/audiovideo/audio/AudioDeviceCapabilities.swift#L13) - see https://github.com/aws/amazon-chime-sdk-ios?tab=readme-ov-file#starting-a-session for more details.

**Comment by linsang21** [comment]
I'll close the issue as the feature has launched, if you have further questions, please feel free to open a new one.

**Comment by hvsw** [comment]
> [!IMPORTANT]
> Question: how should we promote a `.outputOnly` listener to a sending speaker without recreating the session? If "switching audio mode on the fly" is still unsupported, can we reopen this, or should I file a fresh issue scoped to just that?

---

@linsang21 I see this was closed as launched on the `AudioDeviceCapabilities` from v0.25.0 — and that half works for us: viewers join with `.outputOnly` and get no mic prompt while watching.

The original report had a second half that `AudioDeviceCapabilities` doesn't cover, though — joining as a listener "that can be promoted on the fly (including iOS permission handling)". @georgezy-amzn scoped exactly that back in 2022:

> Currently we don't support switching audio mode on the fly, I'll mark this as feature request.
https://github.com/aws/amazon-chime-sdk-ios/issues/507#issuecomment-1204677798

That's still the gap. 

`AudioDeviceCapabilities` is set once, at `start(audioVideoConfiguration:)` — there's no API to move `.outputOnly` → `.inputAndOutput` on a live session, and `promoteToPrimaryMeeting(credentials:observer:)` re-points the connection to the primary but doesn't open the microphone device or trigger the iOS `AVAudioSession.RecordPermission` prompt. A promoted listener lands in the primary meeting with no working mic and no permission request.

> [!NOTE]
> Concrete use case (media replication): a viewer joins a replica with no permissions; when they're promoted to speak in the primary, THAT's the moment we want to open the mic and request permission. The only way we've found on the current SDK is to `stop()` and recreate the session in `.inputAndOutput` — which is fragile, since we infer teardown completion from the `audioSessionDidStopWithStatus` / `videoSessionDidStopWithStatus` callbacks (the video one sometimes never fires for some reason, and we had to put a watchdog as a workaround to handle that, as an example of issue).
