### ISSUE TITLE
App crashing randomly once user leave  the meeting

### ISSUE THREAD

**Issue by manindra86** [aws/amazon-chime-sdk-ios#51]
**Describe the bug**
The app is randomly crashing once the attendee is leaving the meeting. 

**To Reproduce**
1. Start the meeting. Let join another attendee at the meeting.
2. Start video of all attendee and make them switch on/off the video
3. After 2 -3 minutes once the attendee video is on then let them leave the meeting. 
4. After step 3, the app is getting crash. If it doesn't crash then again join the meeting and repeat steps 2 and 3 for some time.

**Expected behavior**
Once user is leaving the meeting then app shouldn't crash.

**Logs**
Log is attached

[DemoApp  03-06-20, 14-35.crash.zip](https://github.com/aws/amazon-chime-sdk-ios/files/4722361/DemoApp.03-06-20.14-35.crash.zip)

**Test environment Info (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 13.3
 - Version AmazonChimeSDK: [e.g. 0.6.1]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.3]

**Comment by tianyux-amz** [comment]
Hi @manindra86, we have a potential fix for this issue and we are planning to release it this Friday.

**Comment by tianyux-amz** [comment]
This was fixed in the latest release (iOS v0.7.0 and Media v0.5.0). Please try it out and let us know if you have more questions or concerns. Thanks!
