### ISSUE TITLE
Question: Is there an equivalent to the JS library's RealtimeAttendeePositionInFrame?

### ISSUE THREAD

**Issue by notapplicableio** [aws/amazon-chime-sdk-ios#513]
I'm matching some code from an existing browser project which uses RealtimeAttendeePositionInFrame and posInFrame. But I can't find the equivalent in iOS.

**Comment by linsang21** [comment]
Hi @notapplicableio, we don't have this API for mobile so far. Can you describe the use case you want to get out of it?

**Comment by ziyiz-amzn** [comment]
Closing this for now. Feel free to reopen it if you can provide description of use cases.
