### ISSUE TITLE
Version 0.22.2 was not published on CocoaPods

### ISSUE THREAD

**Issue by Jim-Bar** [aws/amazon-chime-sdk-ios#514]
Hi,

Version `0.22.2` has been released a few days ago, but it seems the release is missing from CocoaPods. When searching for "_AmazonChimeSDK-Bitcode_" on [CocoaPods](https://cocoapods.org), the latest version shown is `0.22.1`. And [in their repository](https://github.com/CocoaPods/Specs/tree/master/Specs/6/c/3/AmazonChimeSDK-Bitcode), the latest version listed is also `0.22.1`.

Consequently trying to use the latest `0.22.2` fails:

    None of your spec sources contain a spec satisfying the dependency: `AmazonChimeSDK-Bitcode (~> 0.22.2)`.

Thanks.

**Comment by linsang21** [comment]
Hi @Jim-Bar, yes we're working on the CocoaPods release for this version, will let you know when it's available.

**Comment by linsang21** [comment]
v0.22.2 should be available on CocoaPods now.

**Comment by Jim-Bar** [comment]
Yes we were able to pull it successfully, thanks for the update.
