### ISSUE TITLE
SDK 0.22.2 is incompatible with compiler Swift 5.6.1

### ISSUE THREAD

**Issue by Amitmahato** [aws/amazon-chime-sdk-ios#517]
**Describe the bug**
We have been using Amazon Chime SDK `v0.21.3` in our app, and we have tried to update the SDK to `0.22.2`, but while building the iOS app in Xcode, we get the following error:

```
Failed to build module 'AmazonChimeSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). Please select a toolchain which matches the SDK.
```

We have tried to install Swift `v5.6` and use it by changing it from the Toolchain, but it seems this can be done only on the simulator. Since the simulator doesn't have the option to use the camera and the use of camera in our case is mandatory, it is not possible to simply run on the simulator and not on the actual device.

**Expected behavior**
After replacing the `AmazonChimeSDK.xcframework` and `AmazonChimeSDKMedia.xcframework` of `v0.21.3` with the one from `v0.22.2`, the expected behavior should be, that the app would build successfully.

**Screenshots**
<img width="784" alt="image" src="https://user-images.githubusercontent.com/29419386/187147772-93289cde-466c-465f-abf8-c07c6f4c0a68.png">

**Comment by hokyungh** [comment]
Thank you for the report. What Xcode version are you using? Based on [Release Note](https://github.com/aws/amazon-chime-sdk-ios/blob/master/CHANGELOG.md), I don't see any build changes.

Meanwhile were you able to clean and rebuild?

**Comment by Amitmahato** [comment]
Never mind, the issue seems to resolve today after trying to clean and then build again. By the way, my Xcode version is `13.4.1`.

Thank you for your support 🙇
