### ISSUE TITLE
Compile Error on upgrade to latest

### ISSUE THREAD

**Issue by antonrenzoreyes** [aws/amazon-chime-sdk-ios#521]
**Describe the bug**
Compile error when upgrading from v0.8.0 to v0.22.2

**To Reproduce**
1. We are trying to upgrade to a newer version but we're encountering multiple compile errors.

**Screenshots**
![Screen Shot 2022-09-02 at 6 41 11 PM](https://user-images.githubusercontent.com/13776488/188122951-8b778049-78cb-4614-94d1-6b01d47dd766.png)
![Screen Shot 2022-09-02 at 6 41 07 PM](https://user-images.githubusercontent.com/13776488/188122967-1351e544-13f3-46c5-8a9d-e96255e8fa66.png)

**Test environment Info (please complete the following information):**
- Xcode 13.3.1

There are more errors, but I think this should suffice. I think some of the classes/enums from AmazonChimeSDKMedia cannot be found

**Comment by dylonChime** [comment]
Hi @antonrenzoreyes,

Are you building from Cocoapods or binaries? Are you using the correct media binary version (0.17.6)?

**Comment by antonrenzoreyes** [comment]
Hi @dylonChime, I tried both via cocoapods and by downloading it here from github. 
Yes, I am using 0.17.6. 
Also our project has Obj-C, I think the error is from the generated obj-c header.

Thanks!

**Comment by antonrenzoreyes** [comment]
Hi @dylonChime,

We also tried building chime locally and the error still persists.

**Comment by ziyiz-amzn** [comment]
Is `AudioClientDelegate` accessible in this code scope?

**Comment by ethanjanadrake** [comment]
Hi @antonrenzoreyes I built our obj-c demo app without encountering this issue. Can you give details on how to reproduce the issue in the obj-c demo app?

**Comment by antonrenzoreyes** [comment]
Hi @ethanjanadrake, I don't know what exactly reproduces the issue, but since we're encountering an error when using the framework with an obj-c file, we just decided to use Swift for this specific class that uses the framework. This solved our issue on upgrading.

Thanks @ziyiz-amzn, @dylonChime, @ethanjanadrake
