### ISSUE TITLE
Crashed: pc_network_thread

### ISSUE THREAD

**Issue by manghwanitin** [aws/amazon-chime-sdk-ios#523]
Hello,
We are using Amazon chime SDK in our native iOS app. We got a crash in our production version of app.
Please find the required details as below. We have also attached .crash files.
[AmazonChimeSDKMedia.xccrashpoint.zip](https://github.com/aws/amazon-chime-sdk-ios/files/9563961/AmazonChimeSDKMedia.xccrashpoint.zip)

Device: Phone SE (2nd generation)
iOS: 14.8.1
AmazonChimeSDK-No-Bitcode version: 0.21.0
AmazonChimeSDKMedia-No-Bitcode Version: 0.17.0

**Stack trace**
Crashed: pc_network_thread
0  libsystem_pthread.dylib        0x9390 pthread_rwlock_tryrdlock + 158
1  AmazonChimeSDKMedia            0x1cec34 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
2  AmazonChimeSDKMedia            0x1b4c58 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
3  AmazonChimeSDKMedia            0x33b960 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
4  AmazonChimeSDKMedia            0x33b5e4 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
5  AmazonChimeSDKMedia            0x33b4cc (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
6  AmazonChimeSDKMedia            0x29d150 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
7  AmazonChimeSDKMedia            0x2a4f44 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
8  AmazonChimeSDKMedia            0x2a147c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
9  AmazonChimeSDKMedia            0x2a1380 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
10 AmazonChimeSDKMedia            0x2a152c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
11 AmazonChimeSDKMedia            0x2a79a4 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
12 AmazonChimeSDKMedia            0x2a7b20 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
13 AmazonChimeSDKMedia            0x29816c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
14 AmazonChimeSDKMedia            0x298d3c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
15 AmazonChimeSDKMedia            0x298cfc (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
16 AmazonChimeSDKMedia            0x28b758 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
17 AmazonChimeSDKMedia            0x28b7fc (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
18 AmazonChimeSDKMedia            0x287fe4 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
19 AmazonChimeSDKMedia            0x287fb4 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
20 AmazonChimeSDKMedia            0x28818c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
21 AmazonChimeSDKMedia            0x288168 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
22 AmazonChimeSDKMedia            0x31d458 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
23 AmazonChimeSDKMedia            0x324d58 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
24 AmazonChimeSDKMedia            0x3258cc (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
25 AmazonChimeSDKMedia            0x3258a0 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
26 AmazonChimeSDKMedia            0x320b58 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
27 AmazonChimeSDKMedia            0x32188c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
28 AmazonChimeSDKMedia            0x321918 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
29 AmazonChimeSDKMedia            0x2c52f8 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
30 AmazonChimeSDKMedia            0x3cabc0 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
31 AmazonChimeSDKMedia            0x3ca090 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
32 AmazonChimeSDKMedia            0x3c97d0 (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
33 AmazonChimeSDKMedia            0x3c875c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
34 AmazonChimeSDKMedia            0x3c9c8c (Missing UUID 47bb04fbe9b2324f96ab75b46923c864)
35 libsystem_pthread.dylib        0x1bfc _pthread_start + 320
36 libsystem_pthread.dylib        0xa758 thread_start + 8

**Comment by ziyiz-amzn** [comment]
Thank you for reporting and your interest in Amazon Chime iOS SDK. We will investigate and update.

**Comment by manghwanitin** [comment]
@ziyiz-amzn Any updates on this.

**Comment by manghwanitin** [comment]
@ziyiz-amzn It has been more than a month can we please get some updates on this?

**Comment by ethanjanadrake** [comment]
Hi @manghwanitin, we have spent some time investigating this and would like some more information if possible:
- How often is this crash occurring? Can you reproduce it intentionally with specific steps?
- What is occurring in the app when the crash occurs? Are there metrics on CPU or memory use at the time?

**Comment by ethanjanadrake** [comment]
[Symbolicated.zip](https://github.com/aws/amazon-chime-sdk-ios/files/9789173/Symbolicated.zip)

Here are the symbolicated crash files to help if you need. Our thoughts are that thread 0 is on `UIApplication _terminateWithStatus:` so the application is likely being force quit by user or by the system.

**Comment by manghwanitin** [comment]
Hello @ethanjanadrake thanks for update.
Please find the answers for questions asked in above comments
How often is this crash occurring? Crash has occurred once in last 90 days
Can you reproduce it intentionally with specific steps? No we could not reproduce in development environment
What is occurring in the app when the crash occurs? User turned off and on local video and app crashed
Are there metrics on CPU or memory use at the time? Could not figure that out.

Also after looking at sybmolicated crash logs provided in above comment I found that
In file 0826.crash. Thread 11 has crashed the app.
In file 0902.crash. Thread 16 has crashed the app.

In both the crashed threads (11 & 16) las logs mentioned are
rtc::SecureRandomGenerator::Generate(void*, unsigned long) + 3389792 (helpers.cc:42)

So not sure if crash has happened in some helpers.cc class?

However crash is not frequent and there are not any specific steps to reproduce.
In this scenario what is your recommendation?

**Comment by manghwanitin** [comment]
@ziyiz-amzn @ethanjanadrake Any further updates on this please

**Comment by georgezy-amzn** [comment]
Hi @manghwanitin, sorry for the delayed response. Looks like it's a memory management issue in media SDK. We are still looking into it, and will let you know once there are any updates.

**Comment by ethanjanadrake** [comment]
Hi @manghwanitin,
First off, thanks for bringing this issue to our attention. Although it is never ideal to have crashes, we are currently unable to reproduce this one, and it appears to be happening inconsistently and have minimal impact. This means it could take some time to address this bug, as we are currently dealing with some higher priorities. Thank you once again for filing the report.
