### ISSUE TITLE
Error in URLSessionProtocol.swift class

### ISSUE THREAD

**Issue by gmrm** [aws/amazon-chime-sdk-ios#528]
I have compiled the demo app with XCode 14.0 but getting the error in URLSessionProtocol.swift class. Please see the attached screenshot. 
<img width="1440" alt="Screenshot 2022-10-04 at 9 49 14 PM" src="https://user-images.githubusercontent.com/11029185/193880285-5ecc0132-9ed8-4b59-97a8-8cfe773b5a6f.png">

**Comment by linsang21** [comment]
Hi @gmrm, we're aware of this issue on Xcode 14.0.
Please take a look of https://github.com/aws/amazon-chime-sdk-ios/pull/527 for reference.
