### ISSUE TITLE
Additional data/characters appear in the payload

### ISSUE THREAD

**Issue by notapplicableio** [aws/amazon-chime-sdk-ios#536]
Similar to a previous issue, in some payloads send from native to browser I'm seeing additional data/characters appear in the payload.

Sent JSON string: {"currentControllerUserId":"","controlType":"Host","type":"Control","userId":""}
Received JSON String: {"currentControllerUserId":"","controlType":"Host","type":"Control","userId":""}\x01

- I'm not convinced this is happening every time.
- Browser to browser works fine, so I think this may be something in the sent payload.
- I stopped trying to send Data from JSONEncoder as this was even worse, so maybe there is more than one issue rolled up in this.
- Evident in version 0.22.4, but does work in 0.22.3

Links:
- Similar issue: https://github.com/aws/amazon-chime-sdk-ios/issues/217
- Possibly, yhe original change fix: https://github.com/aws/amazon-chime-sdk-ios/commit/c775f6264b24512e52a50948390878452c3c6a40
- Possibly, the change that reverted this: https://github.com/aws/amazon-chime-sdk-ios/commit/4349e9754fa3bd4f7b4a5a6d79c09e9505987192

**To Reproduce**
1. Send JSON as String message using `meetingSession.audioVideo.realtimeSendDataMessage(topic: message.topic.rawValue, data: message.string, lifetimeMs: message.lifetimeMs)`
2. Receive message in Chrome browser client.
4. Chrome browser shows `SyntaxError: Unexpected non-whitespace character after JSON at position 80`

**Expected behavior**
The exact message sent is the one received.

**Logs**
N/A Sufficient detail in description

**Screenshots**
N/A

**Test environment Info (please complete the following information):**
 - Device: iPad
 - OS: iOS 16.1
 - Version AmazonChimeSDK: 0.22.3
 - Version AmazonChimeSDKMedia: 0.17.7
 - Can you reproduce this in the demo app? No, because I need the browser to debug.
If you are reporting a crash: No
 - Are you using bitcode supported binaries? No.
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section. N/A

**Additional context**
Browser to browser does not exhibit this issue.

**Comment by notapplicableio** [comment]
To each of your points, in order:

- It seems like there's a non-deterministic aspect to this. Based on further experiments I've run the characters change but the problem persists.
- 0.22.4 reliably breaks, so I've rolled back to 0.22.3
- My bad, at first I thought this was 0.22.3 but I think I may have run a version of the app using 0.22.4. The problem is just in 0.22.4 which makes sense based on the changes in that version.

The test data is at the top of the original message, repeating here:

The data I'm passing to `realtimeSendDataMessage`:
`{"currentControllerUserId":"","controlType":"Host","type":"Control","userId":""}`

The data Chrome is receiving:
`{"currentControllerUserId":"","controlType":"Host","type":"Control","userId":""}\x01`

Note the `\x01` on the end. This causes `JSON.parse(new TextDecoder().decode(data))` to crash.

**Comment by linsang21** [comment]
Thanks for reporting the issue, I think you're right, the second change reverts the first one. We also have an unreleased change to get the correct length: https://github.com/aws/amazon-chime-sdk-ios/pull/531
Will post when it's out.

**Comment by zhinang-amazon** [comment]
Hi this should be addressed in the v0.22.5 release. Let us know if this is still an issue

**Comment by notapplicableio** [comment]
@zhinang-amazon Looks like this is working fine now. Thank you very much. 😀
