### ISSUE TITLE
WebRTC Version?

### ISSUE THREAD

**Issue by jhiat00** [aws/amazon-chime-sdk-ios#539]
Recently the Android version of our app was flagged as having a WebRTC version with "serious security vulnerabilities" due to dependencies with the Android Chime SDK. There is an open issue for it [here](https://github.com/aws/amazon-chime-sdk-android/issues/513). 

Which version of WebRTC is being used by this SDK? 
Are there plans to update the WebRTC library in the Swift SDK as well?

**Comment by zhinang-amazon** [comment]
We are on the same version of libWebRTC between iOS and Android, M99, and the version update that the team is actively working on will apply to both iOS and Android. Let us know if you have more question on this.

**Comment by manghwanitin** [comment]
@zhinang-amazon Any ETA please by which new SDK version with new WebRTC versions will be available?

**Comment by zhinang-amazon** [comment]
The team is still working on this since the effort to update a libWebRTC version is quite significant. We do not have a concrete ETA for this, rough estimate would be a few weeks, but will keep the Android issue updated regarding this once closer to a release.
