### ISSUE TITLE
joining Meeting

### ISSUE THREAD

**Issue by yousefmoosavi** [aws/amazon-chime-sdk-ios#541]
JoiningViewController.swift  >>  joinMeeting()

- what is primaryExternalMeetingId value in this joining method?

        MeetingModule.shared().prepareMeeting(meetingId: meetingId,
                                              selfName: name,
                                              audioVideoConfig: audioVideoConfig,
                                              option: callKitOption,
                                              overriddenEndpoint: debugSettingsModel.endpointUrl,
                                              primaryExternalMeetingId: debugSettingsModel.primaryExternalMeetingId) { success in
            DispatchQueue.main.async {
                if !success {
                    self.view.hideToast()
                    self.view.makeToast("Unable to join meeting please try different meeting ID",
                                        duration: self.toastDisplayDuration)
                }
            }
        }

**Comment by SUWW** [comment]
> JoiningViewController.swift >> joinMeeting（）
> 
> * 此连接方法中的 primaryExternalMeetingId 值是什么？
>   ```
>     MeetingModule.shared().prepareMeeting(meetingId: meetingId,
>                                           selfName: name,
>                                           audioVideoConfig: audioVideoConfig,
>                                           option: callKitOption,
>                                           overriddenEndpoint: debugSettingsModel.endpointUrl,
>                                           primaryExternalMeetingId: debugSettingsModel.primaryExternalMeetingId) { success in
>         DispatchQueue.main.async {
>             if !success {
>                 self.view.hideToast()
>                 self.view.makeToast("Unable to join meeting please try different meeting ID",
>                                     duration: self.toastDisplayDuration)
>             }
>         }
>     }
>   ```

PrimaryExternalMeetingId This is a conference ID generated by your server

**Comment by zhinang-amazon** [comment]
Thanks @SUWW for answering. Let us know if you still have question on this @yousefmoosavi
