### ISSUE TITLE
How to add and display multiple tiles, and the image can control the size display

### ISSUE THREAD

**Issue by SUWW** [aws/amazon-chime-sdk-ios#544]
amazon-chime-sdk-ios@0.22.4

I refer to the case of Amazon Chime SDK DemoObjC.

There are two questions.

Problem 1: When displaying the portraits of the other party and myself, there is deformation. I set the fixed width and height of the DefaultVideoRenderView myself. How can I adjust the portrait to the condition of no deformation?

Question 2: How do I display multiple tiles? I looked at the historical problem. It was introduced that using videoFrameBroadcast could not exist in ObjC. The following is the code in the demo

# pragma mark - VideoTileObserver

- (void)videoTileDidAddWithTileState:(VideoTileState *)tileState {

[self.logger infoWithMsg:[NSString stringWithFormat:@"Adding Video Tile tileId: %ld, attendeeId: %@", (long)tileState.tileId, tileState.attendeeId]];

DefaultVideoRenderView *renderView = nil;

if (tileState.isLocalTile) {

[self.logger infoWithMsg:[NSString stringWithFormat:@"Binding self video"]];

renderView = self.selfVideoView;

// Flip front camera video on rendering

if (self.meetingSession.audioVideo.getActiveCamera.type == MediaDeviceTypeVideoFrontCamera) {

renderView. mirror = YES;

}

} else {

[self.logger infoWithMsg:[NSString stringWithFormat:@"Binding remote video"]];

renderView = self.remoteVideoView;

//How can I add multiple remoteVideoViews? Is there an array like this? Let me add multiple DefaultVideoRenderViews. I should judge whether it has been added or what other methods are available according to what. thank you

}

[self.meetingSession.audioVideo bindVideoViewWithVideoView:renderView tileId:tileState.tileId];

}

How do I add? Is there an array like this paper? Let me add multiple nickels like DefaultVideoRenderView. I should judge whether it has been added or what other methods are available according to what. thank you

**Comment by zhinang-amazon** [comment]
Hi, our ObjC demo does not have as many functionalities comparing to the Swift one. I would recommend referencing the Swift demo for your questions.

**Comment by dingyishen-amazon** [comment]
Closed the issue for now, feel free to reopen it if you have further questions.
