### ISSUE TITLE
App Store Connect: ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by Tomomir** [aws/amazon-chime-sdk-ios#552]
After updating to the newest version (AmazonChimeSDK-No-Bitcode 0.22.6, AmazonChimeSDKMedia-No-Bitcode 0.17.10) we've encountered the following issue from App Store Connect:

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia: terminate. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

Any idea what's the cause of the issue or how to fix it? We've downgraded back to AmazonChimeSDKMedia-No-Bitcode (0.17.6) and the issue disappeared.

**Comment by georgezy-amzn** [comment]
Hi @Tomomir, sorry for the inconvenience, I'll look into it and let you know.

**Comment by georgezy-amzn** [comment]
We have identified the root cause, and will try to apply the fix in a future release. Will let you know once the release is available.

**Comment by hvsw** [comment]
Just got the same message:


> ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia: terminate. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by DavidKnight-Bluescape** [comment]
Hitting this too, using AmazonChimeSDK-0.22.6 with bitcode support and AmazonChimeSDKMedia-0.17.10 with bitcode support:

> "original_server_error" =     {
>         code = "STATE_ERROR.VALIDATION_ERROR.50";
>         detail = "The app references non-public selectors in Payload/REDACTED/Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia: terminate";
>         id = "e7314e1d-3fbd-4453-a5cd-ec23aa922b5e";
>         status = 409;
>         title = "Asset validation failed";
>     };

**Comment by NicolasMarzullo** [comment]
Same issue here, the problem appears after upgrading this:

![image](https://user-images.githubusercontent.com/42591388/211637461-ecaed7aa-f5d4-49a4-ac87-c806097ad869.png)

**Comment by georgezy-amzn** [comment]
Hi all, sorry for the inconvenience. We are working on this issue on the double, will let you know once the fix is ready.

**Comment by malyshkoserhii** [comment]
Hello! I have got the same message: App Store Connect: ITMS-90338: Non-public API usage.

I am using AmazonChimeSDK-Bitcode (0.22.6) and AmazonChimeSDKMedia-Bitcode (0.17.10), Xcode 13.0, mac mini M1, OS version 12.0.1 Monterey.

**Comment by lewisdonovan** [comment]
We are also experiencing this issue. Please fix asap, it is blocking us from publishing our app.

**Comment by zhinang-amazon** [comment]
We are currently preparing the release candidate, and targeting end of next week to publish the release if all testing goes smoothly. If you are blocked by this, one suggestion would be using [v0.22.5](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.22.5) in the meantime

**Comment by lewisdonovan** [comment]
@zhinang-amazon thanks for the update, we have tried this and are still getting the same rejection. 

Podfile:
`   pod 'AmazonChimeSDK-Bitcode'`

Podfile.lock:
`   - AmazonChimeSDK-Bitcode (= 0.22.5)`.

**Comment by georgezy-amzn** [comment]
Hi all, 

`AmazonChimeSDKMedia-Bitcode 0.17.11` is available now, it should fix this issue. Sorry for the inconvenience.

@Tomomir @hvsw @NicolasMarzullo @malyshkoserhii @lewisdonovan
