### ISSUE TITLE
How we can use sendDataMessage to send a data message to all attendees ?

### ISSUE THREAD

**Issue by Saifak34** [aws/amazon-chime-sdk-ios#554]
This is not a bug but a help request, how we can send data messages in react-native application? do we need to add extra native code in kotlin and C# ? or we can just add it in Bridge.js as a Native function and use it ?

How to use [DataMessageObserver](https://aws.github.io/amazon-chime-sdk-ios/Protocols/DataMessageObserver.html) observer to receive messages ?

why we are triggering  `NativeFunction.sendDataMessage(dataMessage.topic, str, 1000);` while subscribing 

```
const onDataMessageReceivedSubscription = getSDKEventEmitter().addListener(
             MobileSDKEvent.OnDataMessageReceive, 
            (dataMessage) => {
            const str = `Received Data message (topic: ${dataMessage.topic}) ${dataMessage.data} from ${dataMessage.senderAttendeeId}:${dataMessage.senderExternalUserId} at ${dataMessage.timestampMs} throttled: ${dataMessage.throttled}`;
            console.log('received',dataMessage);
            NativeFunction.sendDataMessage(dataMessage.topic, str, 1000);
          })
```

**Comment by hokyungh** [comment]
Hi could you open the ticket in the react native repo? I think this commit already implemented https://github.com/aws-samples/amazon-chime-react-native-demo/commit/232668d5909a8240f714b5a8bc2276fcf870cc8e#diff-507328caaa4c633907645ed5c210987ee518742d3590e75f6a02723fca11ecaf data message.

Also these lines is handling what to do when data message comes in. In our case, in order to demonstrate our data message feature, we echo back.
```
(dataMessage) => {
            const str = `Received Data message (topic: ${dataMessage.topic}) ${dataMessage.data} from ${dataMessage.senderAttendeeId}:${dataMessage.senderExternalUserId} at ${dataMessage.timestampMs} throttled: ${dataMessage.throttled}`;
            console.log('received',dataMessage);
            NativeFunction.sendDataMessage(dataMessage.topic, str, 1000);
          }
```

**Comment by Saifak34** [comment]
Hello , just opened ticket on react native repo : https://github.com/aws-samples/amazon-chime-react-native-demo/issues/169
