### ISSUE TITLE
Unable To Join Meeting

### ISSUE THREAD

**Issue by sridharvthink** [aws/amazon-chime-sdk-ios#555]
Hi,
Issue: Unable To Join Meeting
Error: Description
The example app we run with our endpoint and click join meeting button. 

Error Response:
AmazonChimeSDKDemo[12727:5236927] [ERROR] JoiningRequestService - Key 'CodingKeys(stringValue: "Meeting", intValue: nil)' not found: No value associated with key CodingKeys(stringValue: "Meeting", intValue: nil) ("Meeting")., codingPath: [CodingKeys(stringValue: "JoinInfo", intValue: nil), CodingKeys(stringValue: "Meeting", intValue: nil)]

Please suggest what was the issue?

The meeting started by web app first and mobile app trying to join but cannot able to join vice versa

**Comment by georgezy-amzn** [comment]
Hi @sridharvthink,

Looks like the payload returned from your endpoint is malformed. Please check if the payload structure matches this [model](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/data/JoinMeetingResponse.swift#L83).

**Comment by sridharvthink** [comment]
Hi @georgezy-amzn
Am using given example from here without any change except end point and region

**Comment by georgezy-amzn** [comment]
Please share me the payload, I can take a look.

**Comment by alnlau** [comment]
Let us know if you are still experiencing issues joining the meeting with the demo app
