### ISSUE TITLE
Add filters to videos in a video conference

### ISSUE THREAD

**Issue by usayuki** [aws/amazon-chime-sdk-ios#56]
**Is your feature request related to a problem? Please describe.**
Can Chime Mobile SDK add filters to my meeting video?

**Describe the solution you'd like**
My requirement is to perform color correction and image composition on my conference video.

**Comment by hokyungh** [comment]
Thanks for the request. We are sorry, but we currently do not provide options for custom filter for video. You can request the feature.

We would love to hear more about your use case which would help us in prioritizing this feature. Could you please fill out the form [here](https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html) and somebody from our team would contact you. In the form there is a field "“Tell us about your project:”. You can put the link of this GitHub issue there.

**Comment by usayuki** [comment]
Thank you for your reply.

If you want to add a custom filter for video, I would like you to pass the filtered SampleBuffer to the Chime Mobile SDK so that you can apply the filter you created in our application.

**Comment by hensmi-amazon** [comment]
Hi @usayuki , this should now be possible with custom video source support added in latest release.  You can see a guide [here](https://github.com/aws/amazon-chime-sdk-ios/blob/master/guides/custom_video.md#implementing-a-custom-video-processing-step-for-local-source).
