### ISSUE TITLE
Swift 5.8 Build Error

### ISSUE THREAD

**Issue by shgew** [aws/amazon-chime-sdk-ios#572]
**Describe the bug**
The SDK fails to build using Swift 5.8 SDK (Xcode 14.3 Beta 1)

**To Reproduce**
1. Install Xcode 14.3 Beta 1
2. Try to build a project that has Amazon Chime SDK as a dependency

**Expected behavior**
The project should build without errors.

**Logs**
```
Failed to build module 'AmazonChimeSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)'). Please select a toolchain which matches the SDK.
```

**Screenshots**

**Test environment Info (please complete the following information):**
 - OS: macOS 13.2
 - Version AmazonChimeSDK: 0.22.7
 - Version AmazonChimeSDKMedia: 0.17.11
 - Can you reproduce this in the demo app? Yes

**Comment by dylonChime** [comment]
Since Swift 5.7 ships with Xcode 14, I suspect this issue will be resolved when we support Xcode 14 builds as part of this PR: https://github.com/aws/amazon-chime-sdk-ios/pull/527

**Comment by shgew** [comment]
Got it, thank you. Is there an ETA for that PR?

**Comment by dingyishen-amazon** [comment]
Hi @shgew, it will be merged soon. And the change will be included in the next release, which is planned on 03/09.

**Comment by shgew** [comment]
> Hi @shgew, it will be merged soon. And the change will be included in the next release, we are currently targeting mid March

Thanks 🙂

**Comment by ethanjanadrake** [comment]
Verified that XCode14.3 can now build from Cocoapods and manual add of binaries. Let us know if there are any further issues.

**Comment by shgew** [comment]
Yes, forgot to update this. Everything works now. Thanks.
