### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by devgauravs** [aws/amazon-chime-sdk-ios#574]
**Describe the bug**
When submitting to Apple you get the error ITMS-90338. Doing a distribution

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia: terminate. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at

**To Reproduce**
Product -> Archive
Once archived open the Organizer (should open automatically).
Click Distribute App -> Development -> Make sure "Rebuild from Bitcode" is enabled -> either signing method -> You should see the error

**Screenshots**
![Screenshot 2023-02-23 at 4 02 00 PM](https://user-images.githubusercontent.com/92422650/220925233-1447a5dc-dcf8-451d-99f6-c2651fd75a0b.png)

**Comment by zhinang-amazon** [comment]
Hi @devgauravs 
What version of the AmazonChimeSDK and AmazonChimeSDKMedia are you using?
This should be addressed in AmazonChimeSDK v0.22.7 and AmazonChimeSDKMedia v0.17.11 as discussed in this issue #552

**Comment by zhinang-amazon** [comment]
Feel free to reopen if this is still an issue after you upgrade to the latest version
