### ISSUE TITLE
Using Chime for messaging I cannot create a Channel

### ISSUE THREAD

**Issue by jwarmkessel** [aws/amazon-chime-sdk-ios#575]
**Describe the bug**
Using Chime for messaging I cannot create a Channel. I also can't seem to find any iOS documentation pertaining to this feature.

```
        var requestBody = [
           "AppInstanceArn": appInstanceArn, // required
           "ClientRequestToken": clientRequestToken, // required
           
           "Mode": mode, // not required
           "Name": name, // required
           "Privacy": privacy, // not required
        ]

        do {
            let channelService = try AWSChimeSDKMessagingSendChannelMessageRequest(dictionary: requestBody, error: error())
        } catch {
            print("Failed to create channel")
        }
```

When I run this code I get a crash 

**Expected behavior**
I expect that a channel is created.

**Logs**
```
2023-02-26 13:30:47.091721-0800 Motcha[4953:14223341] *** Caught exception setting key "Name" : [<AWSChimeSDKMessagingSendChannelMessageRequest 0x6000027ec580> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key Name.
2023-02-26 13:30:47.111911-0800 Motcha[4953:14223341] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<AWSChimeSDKMessagingSendChannelMessageRequest 0x6000027ec580> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key Name.'
*** First throw call stack:
```

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]
```
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AWSChimeSDKMessaging'
  pod 'AWSChimeSDKIdentity'
  pod 'Starscream', '~> 4.0.0'
```
 - Can you reproduce this in the demo app? **Yes**
**If you are reporting a crash:**
 - How often is this crash occurring? Every time
 - Are there metrics on CPU or memory use at the time of the crash?
 - Are you using bitcode supported binaries?
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.

**Additional context**

**Comment by ethanjanadrake** [comment]
Hi @jwarmkessel 
`AWSChimeSDKMessagingSendChannelMessageRequest` is for sending message to a channel. You're going to want to use `AWSChimeSDKMessagingCreateChannelRequest`. 

I will close this ticket but if you still experience the same issue after trying this fix, please feel free to reopen.

**Comment by jwarmkessel** [comment]
@ethanjanadrake after I have created a channel request, do I need to make a request to create the channel? I don't see any new channel after calling ```private var channels = [AWSChimeSDKMessagingChannelSummary]()``` again.
