### ISSUE TITLE
No `audioCallEnded` event (or any other event) when the meeting ends

### ISSUE THREAD

**Issue by fridaybyte** [aws/amazon-chime-sdk-ios#578]
**Describe the bug**
No event that would correctly indicate that the Meeting has ended (has been deleted). Thus there is no way for apps to quit meeting properly if the server (another party) has ended the call.

**To Reproduce**
1. Run demo mobile (android or iOS) app on one or more devices
2. Join the same meeting
3. Delete this meeting using API

**What actually happens**
- app stays on the meeting screen for 30 seconds. Only after 30 seconds demo app goes back to the main screen
- `onVideoSessionStopped` is called immediately, but with `VideoServiceFailed` status
- `onAudioSessionStopped` is called only after 30 seconds, with `AudioDisconnected`, which is again described as failed leg

**Expected behavior**
After the meeting is deleted:
- demo app detects that the meeting has ended and goes back to the main screen immediately.
- [audioSessionDidStopWithStatus](https://github.com/aws/amazon-chime-sdk-ios/issues/82#issuecomment-809673469) is called with [audioCallEnded](https://aws.github.io/amazon-chime-sdk-ios/Enums/MeetingSessionStatusCode.html#/c:@M@AmazonChimeSDK@E@MeetingSessionStatusCode@MeetingSessionStatusCodeAudioCallEnded) or [audioServerHangUp](https://aws.github.io/amazon-chime-sdk-ios/Enums/MeetingSessionStatusCode.html#/c:@M@AmazonChimeSDK@E@MeetingSessionStatusCode@MeetingSessionStatusCodeAudioServerHungup)

**Test environment Info (please complete the following information):**
 - Version amazon-chime-sdk: **0.22.6**
 - Version amazon-chime-sdk-media: **0.17.10**
 - Can you reproduce this in the demo app? **Yes**

**Additional context**
This forces all attendees to manually quit the meeting. There is no way to automatically end a call for all attendees by the backend or by one of the attendees (e.g. host). This works properly on JS SDK.

**Comment by glebkravchenko** [comment]
I still see this issue, anybody can help?

**Comment by georgezy-amzn** [comment]
Hi all, we are working on a fix, it will be available soon.

**Comment by yochum** [comment]
This has been fixed. When the `DeleteMeeting` API is called, the client will be sent a `audioServerHungup` and `videoServiceUnavailable` immediately. This will prevent any delay, no retry necessary.

The new behavior will require no change in the SDK.
