### ISSUE TITLE
Add member and moderators to channel

### ISSUE THREAD

**Issue by jwarmkessel** [aws/amazon-chime-sdk-ios#579]
**Describe the bug**
I'm trying to get a list of User's from the User-pool to gain access to their unique ARN's but these properties don't exist on _AWSCognitoIdentityProviderUserType_

```
    func listAllUsers(completion: @escaping (AWSCognitoIdentityProviderListUsersResponse?, Error?) -> Void) {
        //https://stackoverflow.com/questions/42351925/awss3-region-plist-configuration-issue-the-service-configuration-is-nil
        let credentialsProvider = AWSCognitoCredentialsProvider(regionType:.USEast1,identityPoolId: Constants.identityPool)
        let configuration = AWSServiceConfiguration(region:.USEast1, credentialsProvider:credentialsProvider)

        AWSServiceManager.default().defaultServiceConfiguration = configuration
        
        let provider = AWSCognitoIdentityProvider.default()
        guard let request = AWSCognitoIdentityProviderListUsersRequest() else {
            return
        }
        
        
        request.userPoolId = Constants.userPool

        provider.listUsers(request) { response, error in
            completion(response, error)
        }
    }
```

**Expected behavior**
I expect to see a list of user's and their respective ARN so I can add them to the _AWSChimeSDKMessagingCreateChannelRequest_ object. I am capable of successfully getting a response from listing users but when I make a request to add a channel I get the below log.

**Logs**
```
  - some : Error Domain=com.amazonaws.AWSChimeSDKMessagingErrorDomain 

Code=0 "1 validation error detected: Value '[ee1d68cc-593d-432d-ab87-c8bfb4bcedaa]' at 'moderatorArns' failed to satisfy constraint: 

Member must satisfy constraint: 

[Member must have length less than or equal to 1600, 

Member must have length greater than or equal to 5, 

Member must satisfy regular expression pattern: arn:[a-z0-9-.]{1,63}:[a-z0-9-.]{0,63}:[a-z0-9-.]{0,63}:[a-z0-9-.]{0,63}:[^/].{0,1023}, Member must not be null]" 
```

**Test environment Info (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16
 - Version AmazonChimeSDK: 0.4.2
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]
 - Can you reproduce this in the demo app? Yes
**If you are reporting a crash:**
 - How often is this crash occurring?
 - Are there metrics on CPU or memory use at the time of the crash?
 - Are you using bitcode supported binaries?
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.

**Additional context**

**Comment by hokyungh** [comment]
Hi thanks for reporting the issue. Could you try to create ARN based on https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/api/ChimeAPI.js#L13-L14 and see if this works? Thank you.

**Comment by jwarmkessel** [comment]
@hokyungh I'm not sure how this JS code maps to Swift. Can you provide an example? Thanks!

**Comment by jwarmkessel** [comment]
@hokyungh I think I understand. I have this Swift code here: 
```
let userArn = "\(AppConfiguration.appInstanceArn)/user/\(identityId)"
```

Basically, the memberARN is a combination of the AppConfiguration.appInstanceArn + a user's identityId. Is that correct? Also, can you point me to where this is documented?

**Comment by hokyungh** [comment]
Hi @jwarmkessel, your understanding is correct. For the doc, you could refer to [here](https://docs.aws.amazon.com/chime-sdk/latest/dg/create-app-instance-user.html)

**Comment by jwarmkessel** [comment]
@hokyungh 
So then I could take the value of the profile as the _identityId_ from the AWSCognitoIdentityProviderUserType object which is pulled from the user pools and append it to the formatted string?
"<AWSCognitoIdentityProviderAttributeType: 0x6000026c1b20> {\n    name = profile;\n    **value = "us-east-1:e5078c78-6e10-4b38-b976-a87028639fe9";\n}",**  


```
[<AWSCognitoIdentityProviderUserType: 0x6000033a5a80> {  
attributes =     (  
"<AWSCognitoIdentityProviderAttributeType: 0x6000026c1b00> {\n    name = sub;\n    value = "ee1d68cc-593d-432d-ab87-c8bfb4bcedaa";\n}",  
"<AWSCognitoIdentityProviderAttributeType: 0x6000026c1ae0> {\n    name = "email_verified";\n    value = true;\n}",  
"<AWSCognitoIdentityProviderAttributeType: 0x6000026c1b20> {\n    name = profile;\n    value = "us-east-1:e5078c78-6e10-4b38-b976-a87028639fe9";\n}",  
"<AWSCognitoIdentityProviderAttributeType: 0x6000026c1b40> {\n    name = email;\n    value = "[[yaridanjo@gmail.com](mailto:yaridanjo@gmail.com)](mailto:yaridanjo@gmail.com)";\n}"  
);  
enabled = 1;  
userCreateDate = "2023-03-04 07:27:56 +0000";  
userLastModifiedDate = "2023-03-04 07:29:33 +0000";  
userStatus = 2;  
username = Barry;

}]
```

**Comment by jwarmkessel** [comment]
Hmm... it appears that the identityId portion of the userARN created in the React app doesn't use the userId or "sub" from the user pool. Wondering if that's expected?

**Comment by hokyungh** [comment]
Hi I am little confused. Which react app are you referring to? If you are referring to this [app](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat). Might be better to open up questions there. Thanks!
