### ISSUE TITLE
Achive issue

### ISSUE THREAD

**Issue by updev0612** [aws/amazon-chime-sdk-ios#58]
I'm trying to archive my project with this sdk. 
But it shows errors every time. 
Code sigin is failed.

**Comment by hokyungh** [comment]
Hi is this same as https://github.com/aws/amazon-chime-sdk-ios/issues/57? Would you be able to see if this fixes your issue as well?

**Comment by mitankit** [comment]
@updev0612 Any updates on this issue? Did the above mentioned solution work for you?
