### ISSUE TITLE
Unable to find version 0.23.0 of AmazonChimeSDK-Bitcode when running pod install

### ISSUE THREAD

**Issue by Satochaaan** [aws/amazon-chime-sdk-ios#584]
**Describe the bug**
When attempting to run pod install, an error occurs indicating that CocoaPods is unable to find version 0.23.0 of AmazonChimeSDK-Bitcode. The error message is as follows:

**Logs**
```
[!] CocoaPods could not find compatible versions for pod "AmazonChimeSDK-Bitcode":
  In Podfile:
    AmazonChimeSDK-Bitcode (= 0.23.0)

None of your spec sources contain a spec satisfying the dependency: `AmazonChimeSDK-Bitcode (= 0.23.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**To Reproduce**
1. Under /AmazonChimeSDKDemo, run the following command to install pods:

```
$ pod install --repo-update
```

I think we need to deploy the latest version of AmazonChimeSDK to Trunk in cocoapods.

Please let me know if there is another solution.
Thank you in advance.

**Comment by dylonChime** [comment]
The latest release is not in Cocoapods yet, but we are targeting next week for that. Currently 0.23.0 is only available by downloading the zip file from Github.

I'll close this issue for now, but feel free to reopen if you have further questions.

**Comment by shgew** [comment]
Sorry, is there any update on this? 🙂

**Comment by zhinang-amazon** [comment]
Hi, we are actively working on this release to CocoaPods. Apologies on the delay.

**Comment by pbendersky** [comment]
Hi @zhinang-amazon! Sorry to bother again... any update on this release? This is holding us from adopting Xcode 14.3

**Comment by dingyishen-amazon** [comment]
We have released AmazonChimeSDK0.23.0 in Cocoapods, closed the issue.

**Comment by shgew** [comment]
> We have released AmazonChimeSDK0.23.0 in Cocoapods, closed the issue.

It doesn't seem like it. It's still listed as 0.22.7 on https://cocoapods.org/.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/5584672/232002057-041cb4a2-1e82-459c-ac17-7f695b595087.png">
