### ISSUE TITLE
ChimeIdentityService RegisterAppInstanceUserEndpoint is returning "conflictException"

### ISSUE THREAD

**Issue by jwarmkessel** [aws/amazon-chime-sdk-ios#594]
**Describe the bug**
Chat push notifications aren't working because I'm getting a failure when trying to `RegisterAppInstanceUserEndpoint`. 

**Expected behavior**
Expecting successful registration.

**Logs**
"Optional(Error Domain=com.amazonaws.AWSChimeSDKIdentityErrorDomain Code=2 \"null\" UserInfo={NSLocalizedDescription=null, NSLocalizedFailureReason=ConflictException})"

**Test environment Info (please complete the following information):**
 - Device: iPhone 13, 14.
 - OS: iOS 16.4
 - Version AmazonChimeSDK: 3.40

**Additional context**

**Comment by alnlau** [comment]
Hello,

This is not the repo for `RegisterAppInstanceUserEndpoint`. Could you open the issue in [aws-amplify/aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios/issues) instead?
