### ISSUE TITLE
Audio session not starts and rain a lot of errors(failed to open xtl)

### ISSUE THREAD

**Issue by ihor-phillips** [aws/amazon-chime-sdk-ios#595]
**Describe the bug**
Sometimes the audio won't start and rain a lot of errors. This can be reproduces during all day. Could someone help me to understanding what is wrong? My apologise if I missed something and create this topic, but I really not found any information about the errors.

**To Reproduce**
Just initialise the meeting session and **audioVideo.start()**
The audio session not started.

**Logs**

[ERROR] MeetingConsoleLogger - apr_sockaddr_info_get err=nodename nor servname provided, or not known

[ERROR] MeetingConsoleLogger - unable to create remote addr instance

[ERROR] MeetingConsoleLogger - unable to create DTLS peer

[ERROR] MeetingConsoleLogger - audio_client/connector/duplex/dtls/:200: failed to open xtl, err 1

and also

[ERROR] MeetingConsoleLogger - audio cues: others_joined.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: others_left.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: reconnecting.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: reconnected.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: reconnect_failed.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: rumble_strips.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: first_caller.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: remote_muted.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: call_waiting.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: ring_back.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: first_caller_beep.wav err: 7
[ERROR] MeetingConsoleLogger - audio cues: welcome.wav err: 7

**Test environment Info:**
 - Device: iPhone 11 and  simulators.
 - OS: 16
 - Version AmazonChimeSDK: 0.23.0
 - Version AmazonChimeSDKMedia: 0.18.0

**Comment by alnlau** [comment]
Hello,

How are you initializing the meeting session and its meeting session configuration?

**Comment by ihor-phillips** [comment]
Hello
The **MeetingResponseModel** and **AteendeeResponseModel** I get from our server side and after that I generate configuration and **DefaultMeetingSession**.

`let meeting = Meeting(externalMeetingId: meetingUrlData.externalMeetingId,
                              mediaPlacement: meetingUrlData.mediaPlacement.toMediaPlacement(),
                              mediaRegion: meetingUrlData.mediaRegion,
                              meetingId: meetingUrlData.meetingId)
        
        let attendee = Attendee(attendeeId: attendeeData.attendeeId,
                                externalUserId: attendeeData.externalUserId,
                                joinToken: attendeeData.joinToken)
        
        // Construct CreatMeetingResponse and CreateAttendeeResponse.
        let meetingResponse = CreateMeetingResponse(meeting: meeting)
        let attendeeResponse = CreateAttendeeResponse(attendee: attendee)

        // Construct MeetingSessionConfiguration.
        let meetingSessionConfig = MeetingSessionConfiguration(createMeetingResponse: meetingResponse,
                                                               createAttendeeResponse: attendeeResponse)
        
        session = DefaultMeetingSession(configuration: meetingSessionConfig, logger: ConsoleLogger(name: "MeetingConsoleLogger"))`

**Comment by georgezy-amzn** [comment]
Looks like the host cannot be resolved, could you share the implementation of this function: `toMediaPlacement()`?

**Comment by ihor-phillips** [comment]
You're a right. Thanks. Some mistakes in our server side.
