### ISSUE TITLE
SPM Broken

### ISSUE THREAD

**Issue by notapplicableio** [aws/amazon-chime-sdk-ios#603]
**Describe the bug**

Raising here in case the other repo isn't monitored.
https://github.com/aws/amazon-chime-sdk-ios-spm/issues/5

**To Reproduce**
1. Resolve packages

**Expected behavior**
Packages resolve.

**Logs**

Checksum of downloaded artifact of binary target 'AmazonChimeSDKMachineLearning' (92b81aff77420fa8c00b6aa1547621003d84db2acd1ac78c8904fac73fba6066) does not match checksum specified by the manifest (d79e15d11b24ee53219a0c02963e60c4b56cd2f4d121bf8d40c3fe3068a14a9d)

**Screenshots**
See https://github.com/aws/amazon-chime-sdk-ios-spm/issues/5

**Test environment Info (please complete the following information):**
Xcode 14.3.1

**Additional context**
It looks like the contents are missing but the zip is there.

**Comment by oliverfoggin** [comment]
We are also experiencing this as of today. It is currently blocking development on our app. Thanks for raising this.

![image](https://github.com/aws/amazon-chime-sdk-ios/assets/1813244/253c9bbd-ebab-4666-91e2-9205f6f8f24b)

**Comment by yochum** [comment]
Thank you @oliverfoggin & @notapplicableio. We are working to resolve the error with the release. We will update you here when resolved.

**Comment by georgezy-amzn** [comment]
Hi all, sorry for the inconvenience. We have recovered the binary, and verified. Could you also verify?

**Comment by notapplicableio** [comment]
LGTM

Can you add a section to the readme for using SPM. It's a bit obscure/hidden at the moment. The more people that use SPM the sooner we can be alerted to problems. :)

Thanks for fixing.

**Comment by georgezy-amzn** [comment]
Yeah, it has been added to readme in development branch, we are in the phase of merging it to master branch.
