### ISSUE TITLE
Unknown type name 'BackgroundBlurConfiguration' error in Objective-C

### ISSUE THREAD

**Issue by Imamachi-n** [aws/amazon-chime-sdk-ios#607]
Hello,
We are using Amazon Chime SDK for iOS in our react-native iOS app written in Objective-C.

In our iOS project, newly implemented classes in Chime SDK such as `BackgroundBlurConfiguration` cannot be loaded In Objective-C file...

<img width="1358" alt="image" src="https://github.com/aws/amazon-chime-sdk-ios/assets/4005125/e116363a-8ab5-4ca1-bbb3-65f99eda01d9">

We also found that the corresponding classes are not defined in the Bridging Header (`AmazonChimeSDK-Swift.h`).

<img width="1039" alt="image" src="https://github.com/aws/amazon-chime-sdk-ios/assets/4005125/948e50a2-e302-4211-9b29-e85ded8f960c">

The above problem may be due to the `exported_symbols` file not being updated.
https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/exported_symbols

**Test environment Info (please complete the following information):**
 - Version AmazonChimeSDK: 0.23.1
 - Version AmazonChimeSDKMedia: 0.18.1

**Comment by georgezy-amzn** [comment]
Hi Imamachi-n, 

Sorry for the inconvenience. Yeah, looks like some Swift classes are missing obj-c support, it may take some time to fix/release them. Is it blocking you urgently?

**Comment by Imamachi-n** [comment]
Thank you so much for your quick reply!!

This problem is blocking the implementation of background blur in our application...
But we can wait for a while for this problem to be resolved.

**Comment by georgezy-amzn** [comment]
Cool, I'll let you know once it's fixed.

**Comment by Imamachi-n** [comment]
@georgezy-amzn 
When is the above PR expected to be released?

**Comment by georgezy-amzn** [comment]
Hi @Imamachi-n, sorry for the delay, it should be available with v0.23.3 now.
