### ISSUE TITLE
Built-in speaker is identified as MediaDeviceType "other"

### ISSUE THREAD

**Issue by sjmadsen** [aws/amazon-chime-sdk-ios#62]
**Describe the bug**
After starting a video call, the list of audio devices available on my iPhone contains two elements: "iPhone Microphone - audioHandset" and "Build-in Speaker - other". I expected the latter to have a `MediaDeviceType` of `MediaDeviceTypeAudioBuiltInSpeaker`, but it is `MediaDeviceTypeOther`.

Much more minor, but the built-in speaker's description is misspelled and should be "Built-in" (with a "t").

**To Reproduce**
1. Start a video call and query for the list of audio devices.
2. Inspect the returned list for the built-in speaker.

**Expected behavior**
The device with a description of "Build-in Speaker - other" should have a `type` of `MediaDeviceTypeAudioBuiltInSpeaker`.

**Test environment Info (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.5.1
 - Version AmazonChimeSDK: 0.7.1
 - Version AmazonChimeSDKMedia: 0.5.1

**Comment by schonfeld** [comment]
+1 Agreed. This threw me for a quick loop, too. Found the offending code, here: https://github.com/aws/amazon-chime-sdk-ios/blob/410c48858416efc47b7643ed62c007a5a27f075e/AmazonChimeSDK/AmazonChimeSDK/device/DefaultDeviceController.swift#L31 ... I'm inclined to leave the label as-is, since myself (& probably others) are now checking for that misspelling. But we should def use the correct `MediaDeviceType`. I'll start a PR.

**Comment by tianyux-amz** [comment]
Thank you @sjmadsen for reporting the issue and thank you @schonfeld for preparing a PR.

We are in the middle of moving our repos from an internal org to this public aws org. The moving is expected to be done by the end of this week. After that, we will start merging community-contributed code into the repo. Thank you for your patience!

Again, we appreciate your participation in this public repo. Please let us know if you have more questions or concerns.

Best,
Tianyu

**Comment by tianyux-amz** [comment]
Hi @schonfeld,

We've merged our repos from an internal org to this public aws org. Could you please rebase your fix against the `development` branch and update the PR?

Thanks,
Tianyu
