### ISSUE TITLE
SPM no longer goes passes 0.23.1

### ISSUE THREAD

**Issue by bukira** [aws/amazon-chime-sdk-ios#620]
**Describe the bug**
SPM won't find a package after 0.23.1 even thou 0.23.2 and 0.23.3 are released

**Expected behavior**
Can checkout all versions

**Comment by georgezy-amzn** [comment]
Hi @bukira, sorry for the inconvenience. We had some issues releasing to SPM, we are working it.

**Comment by pracheth** [comment]
You should be able to use the latest version (v0.23.3) via SPM 

https://github.com/aws/amazon-chime-sdk-ios-spm/releases/tag/v0.23.3
