### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by amcalgates** [aws/amazon-chime-sdk-ios#624]
**Describe the bug**
According [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc):

> From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

Does ChimeSDK use any APIs mentioned here? If so, are there plans to include a privacy manifest? I'm not 100% sure what that'd even look like, but [this thread](https://developer.apple.com/forums/thread/733537) maybe has a little insight.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Logs**
N/A

**Screenshots**
N/A

**Test environment Info (please complete the following information):**
N/A

**Additional context**
My apologies, as this didn't quite seem like a bug report but also was not quite a feature request.

**Comment by linsang21** [comment]
Thanks for reporting, we're looking into this issue, will keep update.

**Comment by aoi-i10** [comment]
Hi, when can we expect an update regarding this issue?

**Comment by amcalgates** [comment]
Looks like the hard deadline for this is May 1st:

> While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by yochum** [comment]
[Amazon Chime SDK for iOS v0.25.0](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.25.0) has been released including a beta privacy manifest. Please see the [changelog](https://github.com/aws/amazon-chime-sdk-ios/blob/master/CHANGELOG.md) for details.

Please comment on the this Github issue for any suggestions or issues encountered related to the privacy manifest.
