### ISSUE TITLE
Logging with ConsoleLogger

### ISSUE THREAD

**Issue by rama-kundurthi** [aws/amazon-chime-sdk-ios#65]
Hi,

I am trying to build a client app using iOS SDK. I am stuck with binding audio/video sessions to a view element. I wanted to check debug logs that are written by SDK using ConsoleLogger. I could not find in Xcode console or safari browser console. Where do these log entries get written to?

Can you please point me to it?

Following is the snippet of the code that I used just to check where these logs go to:

```
let logger = ConsoleLogger.init(name: "debug")
logger.setLogLevel(level: LogLevel.DEBUG)
logger.info(msg: "foo")
```

Thanks

**Comment by wanghaor-amzn** [comment]
Hi @rama-kundurthi,

Can you try initializing logger by `let logger  = ConsoleLogger(name: "debug")` ?

If you are stuck at something, e.g. binding audio/video sessions to a view element, you can always refer to the code in our AmazonChimeSDKDemo app in this repo.

Please let us know if you have any other questions. Thanks

**Comment by rama-kundurthi** [comment]
Thanks, I was able to access logs, inside the Console app.
