### ISSUE TITLE
Crash in AmazonChimeSDK on calling listAudioDevices() of AudioVideoFacage

### ISSUE THREAD

**Issue by manghwanitin** [aws/amazon-chime-sdk-ios#650]
**Describe the bug**
We have integrated AmazonChimeSDK in our native iOS mobile app.
Below are sdk versions used by our apps
AmazonChimeSDK-No-Bitcode - 0.21.0
AmazonChimeSDKMedia-No-Bitcode - 0.17.0

**Expected behavior**
Application should not crash

**Logs**
[2023-12-28_16-12-28.1496_-0500-d499a5c2c99de0c06a0095bdd66c56c9d53b8ef1.crash.zip](https://github.com/aws/amazon-chime-sdk-ios/files/14437855/2023-12-28_16-12-28.1496_-0500-d499a5c2c99de0c06a0095bdd66c56c9d53b8ef1.crash.zip)

**Test environment Info (please complete the following information):**
 - Device: iPad mini (5th generation)
 - OS: iPadOS 17.1.2
 - Version AmazonChimeSDK:  0.21.0
 - Version AmazonChimeSDKMedia: 0.17.0
 - Can you reproduce this in the demo app? No
 - Are there metrics on CPU or memory use at the time of the crash?
 - Are you using bitcode supported binaries? No
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.
 
[2023-12-28_16-12-28.1496_-0500-d499a5c2c99de0c06a0095bdd66c56c9d53b8ef1.crash.zip](https://github.com/aws/amazon-chime-sdk-ios/files/14437871/2023-12-28_16-12-28.1496_-0500-d499a5c2c99de0c06a0095bdd66c56c9d53b8ef1.crash.zip)

**Comment by manghwanitin** [comment]
Do we have any updates on this please?

**Comment by manghwanitin** [comment]
Any updates on this?
Is Amazon chime product active or you guys have shut down???

**Comment by georgezy-amzn** [comment]
Hi @manghwanitin, since it cannot be reproduced with the demo app, could you compare your code with the demo app, see what's the difference?

**Comment by linsang21** [comment]
Feel free to reopen if you still experience the issue.
