### ISSUE TITLE
Log noise from video_renderer_adapter.cc: 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps

### ISSUE THREAD

**Issue by sjmadsen** [aws/amazon-chime-sdk-ios#67]
**Describe the bug**
Even after silencing the `ConsoleLogger` provided to `DefaultMeetingSession`, `video_renderer_adapter.cc` emits a log message at regular intervals:

```[017:088] [52487] (video_renderer_adapter.cc:194): 10 metrics frames sent with 0 FPS; notify:video_remote_stream_unpaused_with_zero_fps```

**To Reproduce**
1. Configure a meeting session with a logger whose level is set to `OFF`.
2. Initiate a video call.
3. See console messages at regular intervals.

**Expected behavior**
When `ConsoleLogger`'s log level is set to `OFF`, no output should appear on the console from the SDK.

**Test environment Info (please complete the following information):**
 - Devices: iPhone XR, iPad Pro
 - OS: iOS 13.5.1
 - Version AmazonChimeSDK: 0.7.0
 - Version AmazonChimeSDKMedia: 0.5.0

**Comment by sjmadsen** [comment]
This is still a problem with the latest SDKs (ChimeSDK 0.8.0, ChimeSDKMedia 0.5.2). It makes it harder to track down odd behavior with the extra noise on the console.

**Comment by hokyungh** [comment]
Could you let us know how you are obtaining logs? Is it through xcode output or is it through console (Window -> Device and Simulator -> Open Console) or is it some other means.

**Comment by sjmadsen** [comment]
Xcode output when running the app through the debugger.

**Comment by hokyungh** [comment]
Thanks. One of my teammates already labelled as bug. We'll put it in our backlog.
