### ISSUE TITLE
Compilation Errors when using Amazon SDK SPM

### ISSUE THREAD

**Issue by arehman86** [aws/amazon-chime-sdk-ios#672]
**Describe the bug**
I have an objective-c project which I am working on right now. Previously I have downloaded xcframeworks and used it manually but now I have to use SPM. So I removed xcframeworks from the project and used SPM with video. When compiling the code I am getting compilation errors. I am importing the header like this #import <AmazonChimeSDK/AmazonChimeSDK-Swift.h> but getting compilation errors in this header.

**To Reproduce**
Add Amazon chime sdk spm to the project and import the header AmazonChimeSDK/AmazonChimeSDK-Swift.h and try to compile. It will give compilation errors.

**Screenshots**
![image](https://github.com/aws/amazon-chime-sdk-ios/assets/62689814/4dec83a2-506b-49e0-8699-92930d97c1c1)

**Comment by georgezy-amzn** [comment]
Hi @arehman86, did you import AVFoundation? `#import <AVFoundation/AVFoundation.h>`

**Comment by arehman86** [comment]
@georgezy-amzn yes I have done that but it didnt work. There are other errors along with the errors of AVFoundation. Do you want me to prepare a sample project and share it with you guys?

<img width="1840" alt="Screenshot 2024-05-23 at 12 17 28 PM" src="https://github.com/aws/amazon-chime-sdk-ios/assets/62689814/94ec2a65-f8e6-4141-9dd7-b89529d7db44">

**Comment by arehman86** [comment]
@georgezy-amzn 
There is a `ViewController.mm` file in which I added `#import <AmazonChimeSDK/AmazonChimeSDK-Swift.h>`. I think it is due to Objective-C++ because when I use simply with `ViewController.m` then it works fine. But in our case we need to use it with Objective-C++. Code sample is attached.

[amazon-chime-sample.zip](https://github.com/aws/amazon-chime-sdk-ios/files/15427423/amazon-chime-sample.zip)

**Comment by arehman86** [comment]
@georgezy-amzn any update on this one?

**Comment by arehman86** [comment]
@georgezy-amzn Can you please update me on the sample project which I shared with you? Is there anything we need to do on our side to fix the issue?

**Comment by georgezy-amzn** [comment]
Your project is using .mm files, which is for c++, please use .m.
