### ISSUE TITLE
SDK 0.25.1 doesn't resolve

### ISSUE THREAD

**Issue by bukira** [aws/amazon-chime-sdk-ios#674]
**Describe the bug**
SDK 0.25.0 doesnt resolve

**To Reproduce**
set SPM to 0.25.1 and try to remove packages

**Expected behavior**
It download 0.25.1

**Comment by linsang21** [comment]
Thanks @bukira, the SPM release is pending to be done, will update when it's available.

**Comment by georgezy-amzn** [comment]
It's available on SPM now.
