### ISSUE TITLE
App Store Connect Operation Error

### ISSUE THREAD

**Issue by jfredsilva** [aws/amazon-chime-sdk-ios#68]
When I try to upload the archive to the App Store I have several errors.

App Store Connect Operation Error
Unsupported Architectures. The executable for AP App.app/Frameworks/AmazonChimeSDK.framework contains unsupported architectures '[x86_64, i386]'.

App Store Connect Operation Error
Unsupported Architectures. The executable for AP App.app/Frameworks/AmazonChimeSDKMedia.framework contains unsupported architectures '[x86_64, i386]'.

App Store Connect Operation Error
Redundant Binary Upload. You've already uploaded a build with build number '2020007008.1' for version number '0.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).

App Store Connect Operation Error
Invalid Segment Alignment. The app binary at 'AP App.app/Frameworks/AmazonChimeSDK.framework/AmazonChimeSDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

App Store Connect Operation Error
Invalid Segment Alignment. The app binary at 'AP App.app/Frameworks/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

App Store Connect Operation Error
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

If I remove the frameworks from chime sdk I don't have those errors.
Any ideia how to fix this?

**Comment by mitankit** [comment]
@jfredsilva Can you please loot at the solution mentioned in [this github issue](https://github.com/aws/amazon-chime-sdk-ios/issues/57) and see if it works for you.

**Comment by jfredsilva** [comment]
@mitankit Thanks, I'm now able to upload it to the store
