### ISSUE TITLE
Local Network Request alert when joining meeting introduced in 0.25.1

### ISSUE THREAD

**Issue by aaronroggow** [aws/amazon-chime-sdk-ios#681]
**Describe the bug**
Hi! 👋 I'm seeing some new behavior that appears to have been introduced in version 0.25.1. When a user on a fresh install joins the meeting (`meetingSession.audioVideo.start()`), they are getting prompted with an alert reading:
>**"{OUR_APP}" would like to find and connect to devices on your local network**
>This app will be able to discover and connect to devices on the networks you use.
In the exact same scenario, but when using version 0.25.0, this alert is not presented. I checked 0.25.2, and the alert is still present there.

I looked in to this a bit, and it seems that this alert isn't triggered explicitly, but is done automatically by the system when using certain system APIs. The most likely suspect I thought in the 0.25.1 changelog was the new bluetooth device support:
> Allow A2DP Bluetooth speakers to be used as audio outputs
I'm curious if the discovery of those speakers is using an API that's triggering this alert?

The presentation of this alert at the moment of joining a meeting is not ideal for our user experience, and is a blocker for us to upgrade past 0.25.0.

**To Reproduce**
1. Use version 0.25.1
2. Run your app on a physical device (this alert is not presented on simulators)
3. Join a meeting (`meetingSession.audioVideo.start()`)
4. Observe the local network request

**Expected behavior**
Ultimately we want to avoid this alert, as it makes it appear to our user that we are attempting to access data that we are not. If the A2DP BT speaker work is the root cause of this, and it can be refactored to avoid this alert, that's great, but we would also be fine with disabling the feature as a workaround if there were a way to do that.

**Logs**
n/a

**Screenshots**
n/a

**Test environment Info (please complete the following information):**
The specific test device that we observed this on:
 - Device: iPhone 11
 - OS: 17.0.1
 - Version AmazonChimeSDK: 0.25.1
 - Version AmazonChimeSDKMedia: 0.20.1
 - Can you reproduce this in the demo app? unknown, I don't have the demo app set up

Thank you!

**Comment by dinmin-amzn** [comment]
This bug has been fixed in v0.26.1 (see [release notes](https://github.com/aws/amazon-chime-sdk-ios/releases/tag/v0.26.1)).
