### ISSUE TITLE
BackgroundReplacementConfiguration not present when using in Obj-C when importing from AmazonChimeSDK-Swift.h

### ISSUE THREAD

**Issue by vedavtech** [aws/amazon-chime-sdk-ios#685]
**Describe the bug**
BackgroundReplacementConfiguration is not present when using in Obj-C when importing from AmazonChimeSDK-Swift.h

**To Reproduce**
Try to implement BackgroundReplacement in an app in Obj-C

**Expected behavior**
BackgroundReplacementConfiguration should be defined

**Logs**
If applicable, add logs from console to help explain your problem.

**Screenshots**
<img width="796" alt="image" src="https://github.com/user-attachments/assets/19c83407-466a-4432-a0dd-10c08259aa4d">

**Test environment Info (please complete the following information):**
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]
 - Can you reproduce this in the demo app?
**If you are reporting a crash:**
 - How often is this crash occurring?
 - Are there metrics on CPU or memory use at the time of the crash?
 - Are you using bitcode supported binaries?
 - Please provide full crash logs in the form of a ".crash" or ".ips" file with a binary images section.

**Additional context**

**Comment by georgezy-amzn** [comment]
Hi @vedavtech,

Sorry for the innocence, this has been fixed with v0.26.1.
