### ISSUE TITLE
AmazonChimeSDK uses expired chime credentials after providing new credentials.

### ISSUE THREAD

**Issue by aparna-tati-simformsolutions** [aws/amazon-chime-sdk-ios#686]
**Describe the bug**
AmazonChimeSDK uses expired chime credentials even after providing the new chime credentials.

**To Reproduce**
1. We have put 15 min timeout for chime credentials expire time from backend.
2. After expiring the credentials we will taking new credentials and trying to intialise the SDK again.
3. It will give The Security token an expired exception in getSessionEndPoint() function and we have debugged your SDK we have seen, the SDK is still using expired credentials even when we are passing new credentials.

**Expected behavior**
After the chime credentials expire and are initialised with new credentials, The SDK must need to use new chime credentials instead of expired credentials.

**ChimeSDK Version**
I am using 'AWSChimeSDKMessaging', '~> 2.36.3'  this version

**Comment by ziyiz-amzn** [comment]
If this still happens, can you create a new issue in aws-sdk-ios repo please? 
https://github.com/aws-amplify/aws-sdk-ios/issues
