### ISSUE TITLE
RealtimeObserver delegate methods are never called

### ISSUE THREAD

**Issue by senthilece01** [aws/amazon-chime-sdk-ios#75]
if I send a regular push notification when the app is an active state, everything is working fine. But if I send a regular push notification when the app is in terminated state, then I click the notification and launch the app, RealtimeObserver delegates methods are not called. Hence, I am not getting any Audio on either side, no local video.

Kindly share your suggestions

**Comment by tianyux-amz** [comment]
Hi @senthilece01,

Could you provide more details regarding how you register the RealtimeObserver? I'm particularly interested in when you initialize `MeetingSession` in a fresh app launch and how you called `addReadtimeObserver()`. Could you add some logs in your code and make sure 1) the meeting session was properly created; 2) the RealtimeObserver was added properly?

Best,
Tianyu

**Comment by senthilece01** [comment]
**Logs :**

1. When the app is an **active state**, the following logs are received

The Audio successfully started. Reconnecting: false
Attendees joined: 
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e6ace0>]
Video connecting
Video started ok
Adding Video Tile tileId: 0 attendeeId: nil
Adding Video Tile tileId: 2 attendeeId: 
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1cd80>]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1f3e0>]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1ac00>]
Volume updates: [<AmazonChimeSDK.VolumeUpdate: 0x282e1aea0>]


2. When the app is **terminated state**, the following logs are received

The Audio successfully started. Reconnecting: false
Video connecting
Video started ok
Adding Video Tile tileId: 0 attendeeId: nil
Adding Video Tile tileId: 1 attendeeId:

**Issue:** The RealtimeObserver delegates methods are never called. Hence, I am not getting any Audio on either side, no local video.

**Demo Video:**

1. When the app is opened, the RealtimeObserver methods are called and showing the attendee’s list

https://www.dropbox.com/s/xql6m7qvy6glf9b/App%20Active%20State.MP4?dl=0

2. When the app is closed, nothing is working

https://www.dropbox.com/s/ngrc0lqsgaf9ohy/App%20terminated.MP4?dl=0

Kindly see the above demo video in both state and share the suggestions asap.

**Comment by tianyux-amz** [comment]
Hi @senthilece01,

Which SDK and Media version are you using?

Also, could you add some logs right before you register audioVideoFacade observers (e.g. before calling [this](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/MeetingModel.swift#L208)) to make sure you did call `addXXXObservers` properly, when you spining up the app from termination?

Best,
Tianyu
