### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by jorgexgb** [aws/amazon-chime-sdk-ios#8]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An AWS Chime SDK for React Native

**Describe alternatives you've considered**
Creating one myself

**Comment by dchen-aws** [comment]
We are working on a plan on how we can support cross platform framework like React Native. We are currently writing a demo app showcasing how to integrate the Amazon Chime iOS and Android SDK into an existing React Native application. Will update the thread once that's available.

**Comment by jorgexgb** [comment]
@dchen-aws Awesome! A demo app would be great! Anything that can help us integrate it into our existing React Native app.

Thanks!

**Comment by mbokowy** [comment]
Any update? In the coming days we would like add Chime SDK to own React Native App.

**Comment by dchen-aws** [comment]
@jorgexgb @mbokowy we are facing some issue (video client will crash) when embedding the Android SDK into a React Native project. We are actively working on resolving the issue and will have the sample code published once that's resolved. Thanks!

**Comment by jorgexgb** [comment]
Awesome! Thank you so much!

**Comment by jorgexgb** [comment]
@dchen-aws Could you share the React Native iOS SDK? We understand if its not possible. Let me know

**Comment by dchen-aws** [comment]
The issue for Android should have been resolved by now. We are working to get the code cleanup and checked in and go through the legal/open source process to get the sample code published. I don't have an exact date when it can be done, but it should be available sometime in early to Mid May.

We might be able to share early preview under NDA and other terms and conditions in place. So if there is anything we can help meantime, feel free to leave additional comment or question or contact us at https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html.

**Comment by jorgexgb** [comment]
@dchen-aws Thanks! I've reached out to my AWS account manager and referred him to this conversation. Hopefully he can put me in contact with you to arrange early preview under NDA.

Thanks

**Comment by shamoons** [comment]
I’m also looking for access this. I’ll fill out the form for NDA and early accsss

**Comment by daniel-llach** [comment]
Hey! I'm looking fir this too. Aws chime sounds like a good option but we need to integrate it with react-native 🙂do you have some date for this?

**Comment by albertotorresfoltyn** [comment]
I'd like to receive updates about this too! Thanks!

**Comment by TheFrostage** [comment]
I'm extremely interested in this as well! Thank you for your work! Hope to see it soon!

**Comment by vengadanathan** [comment]
I am working on a pet project with react native. It would be great if I can use react native chime SDK to embed video chat support. Do let know ETA for the same, else need to resort to twilio for the same.

**Comment by jorgexgb** [comment]
All those interested, AWS just released a sample on how to do this.

https://github.com/aws-samples/amazon-chime-react-native-demo

Closing this issue.
Thanks AWS Team
