### ISSUE TITLE
audio is very low. I've set audiosession. but remote voice is very low. I can't control volume at all. 

### ISSUE THREAD

**Issue by updev0612** [aws/amazon-chime-sdk-ios#81]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs from console to help explain your problem.

**Screenshots**

**Test environment Info (please complete the following information):**
 - Version AmazonChimeSDK: [e.g. 0.4.0]
 - Version AmazonChimeSDKMedia: [e.g. 0.4.0]

**Additional context**

**Comment by updev0612** [comment]
This code are working well with old SDk but I've exchanged SDK for solving video rendering ratio. after that it happened. 
on my app, it is working with AVPlayer. when AVPlayer play video it's volume louder. but try to have a call it's voice is very low.

**Comment by jpmunoz9** [comment]
@updev0612, could it be that the audio is playing over the ear speaker? I'm experiencing this with the latest sdk, this was not the case with an old version of it.

**Comment by updev0612** [comment]
at old version, everything was okay except for video resize.
but at new sdk, it happened.

**Comment by hokyungh** [comment]
Could you check if audio is played over speaker? For our demo app, you can click on speaker button and click on built-in speaker

**Comment by updev0612** [comment]
solved.
