### ISSUE TITLE
Bind video tiles to multiple render views

### ISSUE THREAD

**Issue by mj8894** [aws/amazon-chime-sdk-ios#95]
**Is your feature request related to a problem? Please describe.**
I would like to implement two set of views, one a list and another an active speaker view. In the active speaker view I would like to bind the tile of the active speaker based on the active speaker callback to the active speaker view(with a single render view)

**Describe the solution you'd like**
A solution wherein we have a separate tile for active speaker like the screenshare tile and localvideo tile which can be used to identify active speaker.

**Describe alternatives you've considered**
Tried binding to multiple render views however it gets stuck after certain amount of time and doesn't recover. 

**Additional context**

**Comment by hokyungh** [comment]
Could you provide little more details on ` it gets stuck` and version of SDK and media library? 

So what you can do is whenever there is active speaker, you can bind tile Id of active speaker to that renderView.

**Comment by mj8894** [comment]
The videos are paused on both render views in case the tile is bound to two video render views.
Using 0.8.2 of chime and 0.6.1 of chimemedia

**Comment by hokyungh** [comment]
Could you be able to provide us logs and how you bind to multiple tiles?
