### ISSUE TITLE
Remote videos paused on orientation change

### ISSUE THREAD

**Issue by mj8894** [aws/amazon-chime-sdk-ios#96]
**Describe the bug**
Whenever the device orientation is changed, all the remote videos are paused and do not recover. And cross view binding happens, same stuck video is being shown in tile 2 and 3 for example.

**Expected behavior**
The Views should recover since rotation methods are called.
 
**Logs**

**Screenshots**

**Test environment Info (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.6
 - Version AmazonChimeSDK: 0.8.1
 - Version AmazonChimeSDKMedia: latest

**Additional context**

**Comment by hokyungh** [comment]
Thank you reporting. This is done using demo application?

**Comment by mj8894** [comment]
No this is a custom application, however the base code is similar to the demo application

**Comment by hokyungh** [comment]
@mj8894 Sorry for late reply. Would you be able to provide full logs and meeting id?

Meeting Id is JSON response for [Meeting](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDK/AmazonChimeSDK/session/CreateMeetingResponse.swift#L23) which correspond to [JoinMeetingResponse](https://github.com/aws/amazon-chime-sdk-ios/blob/master/AmazonChimeSDKDemo/AmazonChimeSDKDemo/data/JoinMeetingResponse.swift#L29)
